'use strict';
Object.assign(filipino,{'Drop ball':'Ihulog ang bola','Twelve rows. One landing.':'Labindalawang hanay. Isang landing.','12 rows · fair left / right':'12 hanay · pantay na kaliwa / kanan','Up to 50×':'Hanggang 50×','Returns include the stake.':'Kasama ang puhunan sa balik.','Ready to drop':'Handa nang ihulog','Dropping…':'Bumabagsak…','Choose a stake from 5 to 500.':'Pumili ng taya mula 5 hanggang 500.','plinkoRules':'Pumili ng taya na 5–500, saka ihulog ang bola. May 12 hakbang; bawat isa ay may pantay at hiwalay na pagkakataong lumiko pakaliwa o pakanan. Ang kabuuang kanan ang tumutukoy sa slot. Ang ipinakitang multiplier × taya ang kabuuang balik, kasama ang puhunan, binibilog pababa sa 0.01. Mas bihira ang mga slot sa gilid. Server ang pumipili ng ruta at nagbabayad; ipinapakita lamang ito ng animation. Isang bola bawat pindot. Hindi naaangkop ang RTP ng Super Ace.'});
Object.assign(english,{plinkoRules:'Choose a stake from 5 to 500, then drop the ball. It takes 12 independent steps, each equally likely to go left or right. The number of right turns determines the slot. Its displayed multiplier × stake is the total return including the stake, rounded down to 0.01. Edge slots are much rarer than central slots. The server chooses the route and settles the wallet; animation only displays that result. One ball per click. Super Ace RTP settings do not apply.'});
const arGames={PLINKO:{name:'PLINKO',tagline:'Twelve rows. One landing.',label:'12 rows · fair left / right',best:'Up to 50×',action:'Drop ball',ready:'Ready to drop',animating:'Dropping…',rules:'plinkoRules'}};
arGames.WHEEL={name:'LUCKY WHEEL',tagline:'One spin. Sixteen possibilities.',label:'16 equal sectors',best:'Up to 7×',action:'Spin wheel',ready:'Ready to spin',animating:'Spinning…',rules:'wheelRules'};
Object.assign(english,{wheelRules:'Choose a stake of 5–500 and spin. Each of the 16 equal sectors is equally likely. The pointer selects one sector. Its multiplier × stake is the total return including your stake, rounded down to 0.01. Zero returns nothing. Outcomes are independent. The server picks and pays the result before animation. The wheel does not use Super Ace RTP settings.'});
Object.assign(filipino,{'One spin. Sixteen possibilities.':'Isang ikot. Labing-anim na posibilidad.','16 equal sectors':'16 pantay na sektor','Up to 7×':'Hanggang 7×','Spin wheel':'Paikutin','Ready to spin':'Handa nang umikot',wheelRules:'Pumili ng taya na 5–500 at paikutin. Pantay ang pagkakataon ng bawat isa sa 16 sektor. Ang multiplier ng sektor × taya ang kabuuang balik kasama ang puhunan, binibilog pababa sa 0.01. Walang balik ang zero. Hiwalay ang bawat resulta. Server ang pumipili at nagbabayad bago ang animation. Hindi naaangkop ang RTP ng Super Ace.'});
arGames.SLOTS={name:'SEVEN SLOTS',tagline:'Three reels. One payline.',label:'3 reels · single line',best:'Up to 100×',action:'Spin reels',ready:'Ready to spin',animating:'Spinning…',rules:'slotsRules'};
Object.assign(english,{slotsRules:'Bet 5–500 on the single center payline. Three cherries pay 5×; three lemons 10×; three bells 25×; three sevens 100×. Exactly two sevens anywhere pay 3×. All other combinations pay zero. Gross returns include the stake. Reels are independent: cherry 40%, lemon 30%, bell 20%, seven 10% on each reel. No wilds, free spins or jackpots. Outcomes come from the server. Super Ace RTP settings do not apply.'});
Object.assign(filipino,{'Three reels. One payline.':'Tatlong reel. Isang payline.','3 reels · single line':'3 reel · iisang linya','Up to 100×':'Hanggang 100×','Spin reels':'Paikutin ang reels',slotsRules:'Tumaya ng 5–500 sa iisang gitnang payline. Tatlong cherry: 5×; tatlong lemon: 10×; tatlong bell: 25×; tatlong seven: 100×. Eksaktong dalawang seven saanman: 3×. Lahat ng ibang kombinasyon: zero. Kasama ang puhunan sa balik. Hiwalay ang reels: cherry 40%, lemon 30%, bell 20%, seven 10% bawat reel. Walang wild, free spin o jackpot. Server ang pumipili. Hindi naaangkop ang RTP ng Super Ace.'});
arGames.SAKLA={name:'SAKLA',tagline:'Forty cards. One winning pair.',label:'40 cards · 20 pairs',best:'19× return',action:'Deal Sakla',ready:'Choose your pair',animating:'Dealing…',rules:'saklaRules'};
Object.assign(english,{saklaRules:'Single-player Sakla: select one of 20 fixed pairs and a stake of 5–500. Each of four Spanish suits contains ranks 1–7, 10, 11 and 12. Pairs within each suit are 1+12, 2+3, 4+5, 6+7 and 10+11. The 40-card deck is shuffled without replacement; cards are dealt until the FIRST pair completes. Only that pair wins. A correct selection returns 19× your stake (18× profit plus stake); every other selection returns zero. One selected pair per ticket, no cancellation. The server settles the full round once; the animation reveals that same deal. Super Ace RTP settings do not apply.'});
Object.assign(filipino,{'Forty cards. One winning pair.':'Apatnapung baraha. Isang panalong pares.','40 cards · 20 pairs':'40 baraha · 20 pares','19× return':'19× na balik','Deal Sakla':'Ipamahagi ang Sakla','Choose your pair':'Piliin ang pares','Dealing…':'Namamahagi…',saklaRules:'Sakla para sa isang manlalaro: pumili ng isa sa 20 pares at tumaya ng 5–500. May ranggong 1–7, 10, 11 at 12 sa bawat isa sa apat na palo. Ang pares sa parehong palo ay 1+12, 2+3, 4+5, 6+7 at 10+11. Binabalasa ang 40 baraha at paisa-isang inilalabas nang walang pag-ulit hanggang makumpleto ang UNANG pares. Iyon lamang ang panalo. Tamang pili: 19× balik, kasama ang puhunan; ibang pili: zero. Isang pares bawat taya, walang pagkansela. Isang beses lang nagbabayad ang server. Hindi naaangkop ang RTP ng Super Ace.'});
arGames.BINGO={name:'BINGO',tagline:'Thirty calls. Make your line.',label:'75 balls · 30 calls',best:'Line wins 6.75×',action:'Play ticket',ready:'One ticket · automatic marking',animating:'Calling balls…',rules:'bingoRules'};
Object.assign(english,{bingoRules:'75-ball quick ticket — single-player. Bet 5–500 for one new 5×5 card. Columns B/I/N/G/O contain distinct numbers from 1–15 / 16–30 / 31–45 / 46–60 / 61–75. The center is FREE. The server independently draws exactly 30 different balls from 1–75 and marks matches automatically. Complete at least one horizontal, vertical or diagonal line to receive 6.75× your stake, including the stake. Multiple lines still pay 6.75× once; no line pays zero. Returns round down to 0.01. You cannot buy extra balls, change the card or cancel an accepted ticket. The server settles the ticket before its visual reveal. This is a personal fixed-payout ticket, not a shared prize pool. Super Ace RTP settings do not apply.'});
Object.assign(filipino,{'Thirty calls. Make your line.':'Tatlumpung tawag. Buuin ang linya.','75 balls · 30 calls':'75 bola · 30 tawag','Line wins 6.75×':'Panalo sa linya: 6.75×','Play ticket':'Laruin ang tiket','One ticket · automatic marking':'Isang tiket · awtomatikong marka','Calling balls…':'Tumatawag ng mga bola…','Called balls':'Mga tinawag na bola','Cards':'Mga baraha',bingoRules:'75-ball quick ticket para sa isang manlalaro. Tumaya ng 5–500 para sa bagong 5×5 na kard. Ang B/I/N/G/O ay may magkakaibang numero mula 1–15 / 16–30 / 31–45 / 46–60 / 61–75. Libre ang gitna. Hiwalay na bumubunot ang server ng eksaktong 30 magkakaibang bola mula 1–75 at awtomatikong minamarkahan ang tugma. Kumpletuhin ang kahit isang pahalang, patayo o pahilis na linya para sa 6.75× balik kasama ang puhunan. Kahit maraming linya, isang 6.75× lang ang bayad. Walang linya: zero. Binibilog pababa sa 0.01. Walang dagdag na bola, palit-kard o pagkansela. Nagbabayad ang server bago ipakita ang resulta. Sariling tiket ito, hindi pinagsamang premyo. Hindi naaangkop ang RTP ng Super Ace.'});
let bgDrawStamp='';
let arSelection=0;
const skSuits=['OROS','COPAS','BASTOS','ESPADAS'],skIcons=['◉','♜','♣','⚔'],skPairs=['1 + 12','2 + 3','4 + 5','6 + 7','10 + 11'];
function skLabel(n){return skSuits[Math.floor(n/5)]+' '+skPairs[n%5]}
for(let n=0;n<20;n++){const b=document.createElement('button');b.type='button';b.dataset.skPair=n;b.innerHTML='<span>'+skIcons[Math.floor(n/5)]+'</span><small>'+skSuits[Math.floor(n/5)]+'</small><b>'+skPairs[n%5]+'</b>';b.onclick=()=>{if(arLocked())return;arSelection=n;arUpdate()};$('arSaklaChoices').append(b);}
let arGame='PLINKO' ,arOwner='',arPending=null,arBusy=false,arLoading=false,arRows=[],arLast=null,arError='',arFrame=0,arGeneration=0,arConfig=null,arAnimationDone=null;
function arKey(){return (player?.id||'guest')+':'+gameMode+':'+arGame}
function arLocked(){arReset();return arBusy||Boolean(arPending)}
function arSave(){try{if(player&&arOwner===arKey()){const key='ar-pending-'+arOwner;arPending?sessionStorage.setItem(key,JSON.stringify(arPending)):sessionStorage.removeItem(key)}}catch{}}
function arReset(){if(arOwner===arKey())return;arOwner=arKey();arGeneration++;arRows=[];arLast=null;arPending=null;arError='';arConfig=null;cancelAnimationFrame(arFrame);if(arAnimationDone){arAnimationDone();arAnimationDone=null;}try{const saved=JSON.parse(sessionStorage.getItem('ar-pending-'+arOwner)||'null');if(saved?.owner===arOwner)arPending=saved;}catch{}$('arResult').textContent='';}
function arCue(win=false){if(document.hidden||!sound||!volume||activeView!=='arcadeView')return;openAudio();(win?[523,659,784]:[610]).forEach((n,i)=>tone(n,.1,'triangle',i*.08))}
function arUpdate(){arReset();if(activeView==='arcadeView')document.querySelectorAll('[data-arcade]').forEach(b=>b.classList.toggle('active',b.dataset.arcade===arGame));$('arSaklaChoices').hidden=arGame!=='SAKLA';document.querySelectorAll('[data-sk-pair]').forEach(b=>{b.disabled=arLocked();b.setAttribute('aria-pressed',String(Number(b.dataset.skPair)===arSelection))});const config=arGames[arGame];$('arTitle').textContent=config.name;$('arTagline').textContent=t(config.tagline);$('arBoardLabel').textContent=t(config.label);$('arBest').textContent=t(config.best);$('arPlay').textContent=t(arBusy?config.animating:config.action);$('arRulesTitle').textContent=config.name;$('arRulesText').textContent=t(config.rules);$('arRuleSummary').textContent=t('Returns include the stake.');$('arBoardNote').textContent=t('Returns include the stake.');$('arBalance').textContent=player?fmt(balance):'—';$('arCurrency').textContent=gameMode==='LOBBY'?'Gold':'chips';$('arStatus').textContent=arError||(!player?t('Sign in to place a bet'):t(config.ready));
 $('arPlay').disabled=arLocked()||arLoading||Boolean(player&&!ready)||busy||pending||autoActive()||free>0||modeChanging||!arConfig;$('arRetry').hidden=!arPending||arBusy;$('arSound').textContent=sound&&volume?'♫':'♫ ×';
 for(const [id,mode]of[['arLobby','LOBBY'],['arClub','CLUB']]){$(id).setAttribute('aria-pressed',String(gameMode===mode));$(id).disabled=arLocked()||busy||modeChanging;}
 for(const el of document.querySelectorAll('#arStake,#arHalf,#arDouble,[data-ar-chip]'))el.disabled=arLocked();
 $('arLastBet').textContent=arLast?money(arLast.betCents):'—';$('arReturn').textContent=arLast?money(arLast.payoutCents):'—';$('arNet').textContent=arLast?money(arLast.payoutCents-arLast.betCents):'—';
 $('arHistory').innerHTML=arRows.length?arRows.map(r=>'<div class="ar-history-row"><span>'+esc(stamp(r.createdAt))+'<small>'+t('Bet')+' '+money(r.betCents)+'</small></span><span>'+(r.outcome.multiplierBps/100)+'×<small>'+t('Total returned')+' '+money(r.payoutCents)+'</small></span><span class="'+(r.payoutCents>r.betCents?'positive':'')+'">'+t('Net')+' '+money(r.payoutCents-r.betCents)+'</span></div>').join(''):'<p>'+t('No bets yet.')+'</p>';
}
async function arLoad(){arReset();if(arLoading||arBusy)return;arLoading=true;const owner=arOwner,generation=arGeneration,mode=gameMode,game=arGame;try{const [config,rows]=await Promise.all([api('arcade/'+game+'/rules'),player?api('arcade/'+game+'/rounds?mode='+mode):[]]);const wallet=player?await api('me?mode='+mode):null;if(owner!==arKey()||generation!==arGeneration)return;arConfig=config;arRows=rows;arLast=rows[0]||null;if(arGame==='SAKLA'&&arLast)arSelection=arPending?.body.selection??arLast.selection??0;if(wallet){applyWallet(wallet);ready=canPlay(wallet);}arRenderBins();arDraw(arLast?.outcome,1);if(arLast)arResult(arLast);}catch(e){if(owner===arKey()){arError=errorText(e);if(e.status===401){ready=false;showLogin();}}}finally{arLoading=false;arUpdate();if(arPending&&ready&&!arBusy)void arSend();}}
function arRenderBins(){$('arBins').hidden=arGame!=='PLINKO';$('arCanvas').setAttribute('aria-label',arGames[arGame].name+' game board');const values=arConfig?.multipliersBps||[];$('arBins').innerHTML=values.map((v,i)=>'<span class="ar-bin '+(i<2||i>10?'edge':i<4||i>8?'near':'')+'" data-bin="'+i+'">'+v/100+'×</span>').join('');}
let arPlinkoBoard=null;
function arMakePlinkoBoard(){const canvas=document.createElement('canvas');canvas.width=1040;canvas.height=840;const ctx=canvas.getContext('2d');ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,520,420);const bg=ctx.createRadialGradient(260,180,0,260,200,300);bg.addColorStop(0,'#194654');bg.addColorStop(1,'#0c182a');ctx.fillStyle=bg;ctx.fillRect(0,0,520,420);
 const gap=37,rowHeight=27,top=48;ctx.strokeStyle='#2d637340';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(260,20);ctx.lineTo(18,396);ctx.lineTo(502,396);ctx.closePath();ctx.stroke();
 for(let row=0;row<12;row++)for(let col=0;col<=row;col++){const x=260+(col-row/2)*gap,y=top+row*rowHeight;ctx.beginPath();ctx.arc(x,y,3.5,0,Math.PI*2);ctx.fillStyle='#b3e2e0';ctx.shadowColor='#56fcdf';ctx.shadowBlur=8;ctx.fill();}ctx.shadowBlur=0;return canvas;}
function arDraw(outcome,progress=0){progress=Number.isFinite(progress)?Math.max(0,Math.min(1,progress)):0;$('bgCalls').hidden=arGame!=='BINGO';if(arGame==='BINGO'){arDrawBingo(outcome,progress);return;}if(arGame==='SAKLA'){arDrawSakla(outcome,progress);return;}if(arGame==='SLOTS'){arDrawSlots(outcome,progress);return;}if(arGame==='WHEEL'){arDrawWheel(outcome,progress);return;}const ctx=$('arCanvas').getContext('2d');ctx.setTransform(2,0,0,2,0,0);if(!arPlinkoBoard)arPlinkoBoard=arMakePlinkoBoard();ctx.drawImage(arPlinkoBoard,0,0,520,420);const gap=37,top=48,rowHeight=27;
 const route=outcome?.values;if(route){const points=[{x:260,y:20},{x:260,y:top-12}];let rights=0;for(let i=0;i<12;i++){rights+=route[i];points.push({x:260+(rights-(i+1)/2)*gap,y:top+(i+1)*rowHeight-12});}points.push({x:260+(outcome.slot-6)*gap,y:401});const amount=Math.min(points.length-1,progress*(points.length-1)),index=Math.min(points.length-2,Math.floor(amount)),f=amount-index,a=points[index],b=points[index+1];const x=a.x+(b.x-a.x)*f,y=index===0?a.y+(b.y-a.y)*f*f:a.y+(b.y-a.y)*f*f-5*Math.sin(f*Math.PI);
 ctx.beginPath();for(let i=0;i<=index;i++)i?ctx.lineTo(points[i].x,points[i].y):ctx.moveTo(points[i].x,points[i].y);ctx.lineTo(x,y);ctx.strokeStyle='#f690bc66';ctx.lineWidth=3;ctx.stroke();const glow=ctx.createRadialGradient(x-3,y-4,1,x,y,11);glow.addColorStop(0,'#fffbd0');glow.addColorStop(.35,'#ffc679');glow.addColorStop(1,'#f668ac');ctx.fillStyle=glow;ctx.shadowColor='#ffa0d1';ctx.shadowBlur=20;ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
 }else{ctx.fillStyle='#f6b4d7';ctx.beginPath();ctx.arc(260,20,9,0,Math.PI*2);ctx.fill();}}
function arResult(row){const net=row.payoutCents-row.betCents;$('arResult').classList.toggle('win',net>0);$('arResult').innerHTML=(arGame==='BINGO'&&row.outcome.slot?'BINGO!<br>':'')+(arGame==='SAKLA'?skLabel(row.outcome.slot)+'<br>':'')+(row.outcome.multiplierBps/100)+'× · '+money(row.payoutCents)+'<small>'+t('Net')+' '+(net>0?'+':'')+money(net)+'</small>';document.querySelectorAll('[data-bin]').forEach(b=>b.classList.toggle('hit',Number(b.dataset.bin)===row.outcome.slot));}
function arAnimate(row){return new Promise((resolve,reject)=>{
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,game=arGame;
 const duration=game==='BINGO'?6000:game==='SAKLA'?3600:game==='WHEEL'?3000:game==='PLINKO'?2600:2000;
 let elapsed=0,last=null,finished=false;
 const finish=()=>{if(finished)return;finished=true;cancelAnimationFrame(arFrame);arAnimationDone=null;try{arDraw(row.outcome,1);resolve();}catch(e){reject(e)}};
 arAnimationDone=finish;
 const frame=now=>{if(finished)return;try{if(document.hidden||reduced){finish();return;}
 // Use rendered frame deltas; a delayed frame must not skip the whole drop.
 if(last!==null)elapsed+=Math.min(40,Math.max(0,now-last));last=now;
 const progress=Math.min(1,elapsed/duration);arDraw(row.outcome,progress);
 if(progress<1)arFrame=requestAnimationFrame(frame);else finish();
 }catch(e){finished=true;cancelAnimationFrame(arFrame);arAnimationDone=null;reject(e)}};
 arDraw(row.outcome,0);arFrame=requestAnimationFrame(frame);
});}

async function arSend(){if(arBusy||!arPending||!ready)return;const owner=arOwner,mode=gameMode,game=arGame,request=arPending;arBusy=true;busy=true;arGeneration++;arDraw(null);document.querySelectorAll('[data-bin]').forEach(b=>b.classList.remove('hit'));$('arResult').textContent=t('Receiving result…');$('arResult').classList.remove('win');hideVictory();arUpdate();try{if(request.body.expectedRevision===undefined){const w=await api('me?mode='+mode);if(owner!==arKey())return;applyWallet(w);request.body.expectedRevision=revision;arSave();}const row=await api('arcade/'+game+'/rounds?mode='+mode,'POST',request.body);if(owner!==arKey())return;$('arResult').textContent='';await arAnimate(row);if(owner!==arKey())return;arLast=row;arRows=[row,...arRows.filter(r=>r.requestId!==row.requestId)].slice(0,20);arPending=null;arSave();arError='';arResult(row);arCue(row.payoutCents>row.betCents);celebrateWin('arcadeView',game+':'+row.requestId,row.betCents,row.payoutCents);applyWallet(await api('me?mode='+mode));}
 catch(e){if(owner===arKey()){if(e.code==='STALE_STATE'){delete request.body.expectedRevision;arSave();}else if(e.status===401){ready=false;showLogin();}else if(e.status>=400&&e.status<500){arPending=null;arSave();}arError=e.status?errorText(e):t('Connection lost. Retry uses the same request and cannot charge twice.');}}finally{arBusy=false;busy=false;arUpdate();}}
$('arPlay').onclick=()=>{if(!player){showLogin();return}if(arLocked()||!ready)return;const amount=Number($('arStake').value);if(!Number.isFinite(amount)||amount<5||amount>500){arError=t('Choose a stake from 5 to 500.');arUpdate();return}arPending={owner:arOwner,body:{requestId:requestUuid(),betCents:Math.round(amount*100),selection:arGame==='SAKLA'?arSelection:0}};arSave();void arSend();};
$('arRetry').onclick=()=>arSend();$('arHalf').onclick=()=>$('arStake').value=Math.max(5,Math.floor(Number($('arStake').value)*50)/100);$('arDouble').onclick=()=>$('arStake').value=Math.min(500,Number($('arStake').value)*2);document.querySelectorAll('[data-ar-chip]').forEach(b=>b.onclick=()=>$('arStake').value=b.dataset.arChip);$('arLobby').onclick=()=>switchMode('LOBBY');$('arClub').onclick=()=>switchMode('CLUB');$('arSound').onclick=()=>{$('sound').click();arUpdate();};$('arRulesButton').onclick=()=>$('arRules').showModal();$('arRulesClose').onclick=()=>$('arRules').close();
const arOldLanguage=setLanguage;setLanguage=value=>{arOldLanguage(value);arUpdate();if(arLast)arResult(arLast);};const arOldHelp=$('help').onclick;$('help').onclick=()=>activeView==='arcadeView'?$('arRules').showModal():arOldHelp();document.addEventListener('visibilitychange',()=>{if(document.hidden&&arAnimationDone){cancelAnimationFrame(arFrame);const done=arAnimationDone;arAnimationDone=null;done();}else if(!document.hidden&&activeView==='arcadeView')void arLoad();});localize();

function arDrawWheel(outcome,progress){const ctx=$('arCanvas').getContext('2d');ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,520,420);const values=arConfig?.multipliersBps||[],count=values.length||16,step=Math.PI*2/count,slot=outcome?.slot??0;const angle=outcome?(Math.PI*10-slot*step-step/2)*(1-Math.pow(1-progress,4)):0;const cx=260,cy=212,radius=173;
 const bg=ctx.createRadialGradient(cx,cy,20,cx,cy,270);bg.addColorStop(0,'#80316b');bg.addColorStop(1,'#181932');ctx.fillStyle=bg;ctx.fillRect(0,0,520,420);ctx.save();ctx.translate(cx,cy);ctx.rotate(angle-Math.PI/2);
 for(let i=0;i<count;i++){ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,radius,i*step,(i+1)*step);ctx.closePath();ctx.fillStyle=['#2f2b56','#bd477e','#383562','#327d84'][i%4];ctx.fill();ctx.strokeStyle='#e7b782';ctx.lineWidth=1;ctx.stroke();ctx.save();ctx.rotate((i+.5)*step);ctx.translate(135,0);ctx.rotate(Math.PI/2);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=values[i]>=300?'#ffe095':'#fff4e8';ctx.font='900 18px system-ui';ctx.fillText((values[i]||0)/100+'×',0,0);ctx.restore();}
 ctx.restore();ctx.beginPath();ctx.arc(cx,cy,radius+6,0,Math.PI*2);ctx.strokeStyle='#f4d69f';ctx.lineWidth=7;ctx.stroke();for(let i=0;i<32;i++){const a=i*Math.PI/16;ctx.beginPath();ctx.arc(cx+Math.cos(a)*(radius+7),cy+Math.sin(a)*(radius+7),2.5,0,Math.PI*2);ctx.fillStyle=i%2?'#fff3cf':'#c18a53';ctx.fill();}
 const hub=ctx.createRadialGradient(cx-9,cy-10,4,cx,cy,43);hub.addColorStop(0,'#ffeec3');hub.addColorStop(1,'#b27d45');ctx.fillStyle=hub;ctx.beginPath();ctx.arc(cx,cy,40,0,Math.PI*2);ctx.fill();ctx.fillStyle='#683256';ctx.font='900 13px system-ui';ctx.textAlign='center';ctx.fillText('LUCKY',cx,cy-2);ctx.fillText('SEVEN',cx,cy+14);ctx.beginPath();ctx.moveTo(cx-13,23);ctx.lineTo(cx+13,23);ctx.lineTo(cx,58);ctx.closePath();ctx.fillStyle='#ffe6aa';ctx.shadowColor='#ffe6aa';ctx.shadowBlur=12;ctx.fill();ctx.shadowBlur=0;}
async function selectArcade(kind){if(!arGames[kind]||(typeof lnLocked==='function'&&lnLocked())||(typeof mnLocked==='function'&&mnLocked())||arLocked()||busy||pending||autoActive()||free>0||(typeof crLocked==='function'&&crLocked())||(typeof cgLocked==='function'&&cgLocked())||(typeof dtLocked==='function'&&dtLocked()))return;if(typeof hideVictory==='function')hideVictory();arGame=kind;try{sessionStorage.setItem('arcade-game',kind)}catch{}arReset();await showView('arcadeView');document.querySelectorAll('[data-arcade]').forEach(b=>b.classList.toggle('active',b.dataset.arcade===kind));}
document.querySelectorAll('[data-arcade]').forEach(b=>b.onclick=()=>selectArcade(b.dataset.arcade));
try{const saved=sessionStorage.getItem('arcade-game');if(arGames[saved])arGame=saved;}catch{}

function arDrawSlots(outcome,progress){const ctx=$('arCanvas').getContext('2d');ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,520,420);const bg=ctx.createRadialGradient(260,210,0,260,200,330);bg.addColorStop(0,'#652d4c');bg.addColorStop(1,'#18182b');ctx.fillStyle=bg;ctx.fillRect(0,0,520,420);ctx.fillStyle='#f9d292';ctx.textAlign='center';ctx.font='900 20px system-ui';ctx.fillText('★  LUCKY SEVEN  ★',260,66);ctx.fillStyle='#a18ab5';ctx.font='11px system-ui';ctx.fillText('5× CHERRY · 10× LEMON · 25× BELL · 100× SEVEN',260,365);ctx.fillText('2 SEVENS = 3×',260,385);
 for(let reel=0;reel<3;reel++){const x=50+reel*143;ctx.fillStyle='#e8c18c';ctx.beginPath();ctx.roundRect(x-5,100,139,219,16);ctx.fill();ctx.fillStyle='#f5eddc';ctx.beginPath();ctx.roundRect(x,106,129,207,12);ctx.fill();ctx.save();ctx.beginPath();ctx.roundRect(x,106,129,207,12);ctx.clip();const spinning=outcome&&progress<.65+reel*.15;const value=spinning?Math.floor(progress*30+reel)%4:outcome?.values[reel]??3;const y=210+(spinning?Math.sin(progress*80+reel)*60:0);arSlotSymbol(ctx,value,x+64,y);const shade=ctx.createLinearGradient(0,106,0,313);shade.addColorStop(0,'#62425d66');shade.addColorStop(.25,'#ffffff00');shade.addColorStop(.75,'#ffffff00');shade.addColorStop(1,'#62425d66');ctx.fillStyle=shade;ctx.fillRect(x,106,129,207);ctx.restore();}ctx.strokeStyle='#ffbc6d66';ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(35,210);ctx.lineTo(485,210);ctx.stroke();ctx.setLineDash([]);}
function arSlotSymbol(ctx,s,x,y){ctx.save();ctx.translate(x,y);if(s===3){ctx.font='italic 900 100px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=5;ctx.strokeStyle='#a35321';ctx.strokeText('7',0,4);ctx.fillStyle='#df385e';ctx.fillText('7',0,4);}else if(s===0){ctx.strokeStyle='#39825e';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-18,14);ctx.quadraticCurveTo(-10,-32,20,-35);ctx.quadraticCurveTo(22,-10,20,20);ctx.stroke();ctx.fillStyle='#d73e69';for(const [a,b]of[[-20,14],[22,22]]){ctx.beginPath();ctx.arc(a,b,23,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffc1c8';ctx.beginPath();ctx.arc(a-6,b-7,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d73e69';}}else if(s===1){ctx.rotate(-.45);ctx.fillStyle='#f1c841';ctx.beginPath();ctx.ellipse(0,0,42,29,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff2ac';ctx.beginPath();ctx.ellipse(-5,-10,22,6,0,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle='#c6922d';ctx.beginPath();ctx.arc(0,32,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#edb846';ctx.beginPath();ctx.moveTo(-38,25);ctx.quadraticCurveTo(-27,15,-27,-6);ctx.arc(0,-6,27,Math.PI,0);ctx.quadraticCurveTo(27,15,38,25);ctx.closePath();ctx.fill();ctx.fillStyle='#ffe5a7';ctx.fillRect(-10,-32,10,45);}ctx.restore();}

function arDrawSakla(outcome,progress){const ctx=$('arCanvas').getContext('2d');ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,520,420);const bg=ctx.createRadialGradient(260,200,0,260,200,350);bg.addColorStop(0,'#80422e');bg.addColorStop(1,'#291e32');ctx.fillStyle=bg;ctx.fillRect(0,0,520,420);ctx.textAlign='center';ctx.fillStyle='#f5d59c';ctx.font='900 24px Georgia';ctx.fillText('SAKLA',260,40);ctx.font='12px system-ui';ctx.fillText(outcome?Math.ceil(progress*outcome.values.length)+' / '+outcome.values.length+' '+t('Cards'):'OROS · COPAS · BASTOS · ESPADAS',260,64);
 if(!outcome){for(let i=0;i<5;i++){ctx.fillStyle='#ae5748';ctx.strokeStyle='#e7bb7c';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(170+i*4,130-i*3,156,209,12);ctx.fill();ctx.stroke();}ctx.fillStyle='#f4d293';ctx.font='54px Georgia';ctx.fillText('♜',257,248);return;}
 const visible=Math.max(1,Math.ceil(outcome.values.length*progress));outcome.values.slice(0,visible).forEach((card,i)=>{const x=26+(i%7)*68,y=88+Math.floor(i/7)*99,suit=Math.floor(card/10),rank=[1,2,3,4,5,6,7,10,11,12][card%10],pair=suit*5+(card%10===0||card%10===9?0:card%10<=2?1:card%10<=4?2:card%10<=6?3:4),win=progress===1&&pair===outcome.slot;ctx.fillStyle=win?'#fff0b5':'#f8edda';ctx.strokeStyle=win?'#ffbf4c':'#a78d76';ctx.lineWidth=win?3:1;ctx.beginPath();ctx.roundRect(x,y,58,84,6);ctx.fill();ctx.stroke();ctx.fillStyle=suit<2?'#a34034':'#29364e';ctx.textAlign='left';ctx.font='bold 18px Georgia';ctx.fillText(rank,x+6,y+21);ctx.textAlign='center';ctx.font='27px Georgia';ctx.fillText(skIcons[suit],x+29,y+55);ctx.font='7px system-ui';ctx.fillText(skSuits[suit],x+29,y+75);});}

function bgLines(){return [...Array.from({length:5},(_,r)=>Array.from({length:5},(_,c)=>r*5+c)),...Array.from({length:5},(_,c)=>Array.from({length:5},(_,r)=>r*5+c)),[0,6,12,18,24],[4,8,12,16,20]];}
function arDrawBingo(outcome,progress){const ctx=$('arCanvas').getContext('2d');ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,520,420);const bg=ctx.createRadialGradient(240,170,0,260,210,350);bg.addColorStop(0,'#176581');bg.addColorStop(1,'#12203d');ctx.fillStyle=bg;ctx.fillRect(0,0,520,420);const card=outcome?.values.slice(0,25),calls=outcome?.values.slice(25)||[],n=outcome?Math.min(30,Math.floor(progress*30)):0,seen=new Set([0,...calls.slice(0,n)]),colors=['#e9617e','#e9af4b','#75ac63','#618bdf','#b177d2'];let mask=0;if(card)bgLines().forEach((line,i)=>{if(line.every(cell=>seen.has(card[cell])))mask|=1<<i});const winning=new Set();bgLines().forEach((line,i)=>{if(mask>>i&1)line.forEach(c=>winning.add(c))});
 ctx.textAlign='center';ctx.fillStyle='#cceaf7';ctx.font='bold 13px system-ui';ctx.fillText('LUCKY SEVEN · 75 BALL',260,25);for(let col=0;col<5;col++){ctx.fillStyle=colors[col];ctx.font='900 28px system-ui';ctx.fillText('BINGO'[col],53+col*56,67);}
 for(let i=0;i<25;i++){const x=28+i%5*56,y=84+Math.floor(i/5)*57,number=card?.[i],marked=card&&seen.has(number);ctx.fillStyle=winning.has(i)?'#ffe59b':marked?'#59d9c5':'#e5f0ef';ctx.beginPath();ctx.roundRect(x,y,49,49,7);ctx.fill();if(winning.has(i)){ctx.strokeStyle='#ffcf64';ctx.lineWidth=3;ctx.stroke();}ctx.fillStyle=marked?'#145961':'#294260';ctx.font=i===12?'900 11px system-ui':'800 20px system-ui';ctx.fillText(i===12?'FREE':number??'·',x+24.5,y+31);}
 const ball=calls[n-1],col=ball?Math.floor((ball-1)/15):0,cx=414,cy=151,ballColor=colors[col];ctx.save();ctx.translate(cx,cy);if(outcome&&progress<1){const f=(progress*30)%1;ctx.translate(0,-Math.sin(Math.PI*f)*7);}const shine=ctx.createRadialGradient(-18,-22,0,0,0,64);shine.addColorStop(0,'#fff2fb');shine.addColorStop(.3,ballColor);shine.addColorStop(1,'#172045');ctx.fillStyle=shine;ctx.shadowColor=ballColor;ctx.shadowBlur=18;ctx.beginPath();ctx.arc(0,0,57,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff6e5';ctx.beginPath();ctx.arc(0,0,34,0,Math.PI*2);ctx.fill();ctx.fillStyle='#34334b';ctx.font='800 11px system-ui';ctx.fillText(ball?'BINGO'[col]:'BINGO',0,-11);ctx.font='900 30px system-ui';ctx.fillText(ball||'?',0,21);ctx.restore();ctx.fillStyle='#acd5e7';ctx.font='12px system-ui';ctx.fillText(n+' / 30',414,238);ctx.fillStyle='#e5ce91';ctx.font='bold 12px system-ui';ctx.fillText(mask?'BINGO!':'6.75×',414,263);
 calls.slice(Math.max(0,n-6),n).forEach((b,i)=>{const x=373+(i%3)*41,y=299+Math.floor(i/3)*41;ctx.fillStyle=colors[Math.floor((b-1)/15)];ctx.beginPath();ctx.arc(x,y,16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 13px system-ui';ctx.fillText(b,x,y+5)});
 const stamp=language+':'+(card?.join(',')||'')+':'+n;if(stamp!==bgDrawStamp){bgDrawStamp=stamp;$('bgCalls').innerHTML='<small>'+t('Called balls')+' · '+n+'/30</small><div>'+calls.slice(0,n).map(b=>'<span style="--ball:'+colors[Math.floor((b-1)/15)]+'">'+b+'</span>').join('')+'</div>';if(arBusy&&n>0&&!document.hidden&&sound&&volume)tone(card?.includes(ball)?880:520,.035,'sine');}
 const label=card?'BINGO: '+card.map((v,i)=>i===12?'FREE':v+(seen.has(v)?' ✓':'')).join(', ')+'. '+t('Called balls')+': '+calls.slice(0,n).join(', '):'BINGO 75-ball card';$('arCanvas').setAttribute('aria-label',label);
}
