'use strict';
Object.assign(english,{cgJackpotRules:'Three BLUE dice trigger one shared jackpot for all players with accepted bets in that round, regardless of the color bet. There is no minimum beyond the normal bet. At settlement, 1% of total stakes funds the pool without an extra wallet charge. One tier is drawn on the server. Its prize is split in proportion to each player’s total stake; fractions are distributed to the nearest cent. Base Color Game payouts are separate. The percentages below are conditional on three BLUE dice; fair dice give that result in 1 of 216 rounds on average. This does not guarantee a win.',cgJackpotClub:'Club Jackpot is not enabled. Club chips and the Lobby Gold pool are separate.'});
Object.assign(filipino,{'Jackpot won!':'Nanalo ng Jackpot!','Live pool':'Aktibong pondo','Prize share':'Bahagi ng premyo','Tier chance':'Tsansa ng antas','Recent jackpots':'Mga nakaraang jackpot','My jackpot awards':'Aking mga premyo sa jackpot','No jackpot awards yet.':'Wala pang premyo sa jackpot.','Add to pool':'Dagdagan ang pondo','Pool top-up (Gold)':'Dagdag sa pondo (Gold)','Retry same top-up':'Ulitin ang parehong dagdag','Pool updated':'Na-update ang pondo','Loading jackpot…':'Kinukuha ang jackpot…','Jackpot unavailable':'Hindi makuha ang jackpot',cgJackpotRules:'Tatlong ASUL na dice ang nagbibigay ng isang pinagsasaluhang jackpot sa lahat ng may tinanggap na taya sa larong iyon, anuman ang kulay na tinayaan. Walang dagdag na minimum. Sa pagtatapos, 1% ng kabuuang taya ang idinadagdag sa pondo nang walang dagdag na bawas sa wallet. Server ang pumipili ng isang antas. Hinahati ang premyo ayon sa kabuuang taya ng bawat manlalaro, hanggang sentimo. Hiwalay ang karaniwang balik ng Color Game. Ang tsansa ng antas sa ibaba ay para lamang sa tatlong ASUL; sa pantay na dice, karaniwan itong 1 sa 216 laro. Walang garantisadong panalo.',cgJackpotClub:'Hindi pa aktibo ang Club Jackpot. Hiwalay ang Club chips at Lobby Gold.'});
let cjpState=null,cjpKey='',cjpBusy=false,cjpTopUp=null,cjpOwner=null;
const cjpDialog=$('cgJackpotDialog');
cjpDialog.innerHTML='<button id="cgJackpotClose" type="button" class="icon close" aria-label="Close">×</button><h2>♛ JACKPOT</h2><p id="cjpStatus" role="status"></p><p id="cjpRules"></p><div id="cjpLevels" class="cjp-levels"></div><form id="cjpTopUp" hidden><label><span id="cjpTopUpLabel"></span><input id="cjpAmount" type="number" min="1" max="100000000" step="0.01" value="1000" required></label><button id="cjpAdd" type="submit"></button></form><p id="cjpMessage" role="status"></p><h3 id="cjpHistoryTitle"></h3><ol id="cjpHistory" class="cjp-history"></ol><section id="cjpMineSection" hidden><h3 id="cjpMineTitle"></h3><ol id="cjpMine" class="cjp-history"></ol></section>';
function cjpRender(){
 const valid=cjpState&&cjpKey===gameMode,enabled=valid&&cjpState.enabled,unit=gameMode==='LOBBY'?'Gold':'chips';
 const digits=document.querySelector('.cg-jackpot-digits'),caption=document.querySelector('.cg-jackpot-body>small');caption.removeAttribute('data-i18n');
 const value=enabled?Math.floor(cjpState.balanceCents/100).toString().padStart(9,'0'):'—————————';digits.style.gridTemplateColumns=`repeat(${value.length},minmax(0,1fr))`;digits.replaceChildren(...[...value].map(v=>{const n=document.createElement('span');n.textContent=v;return n;}));digits.setAttribute('aria-label',enabled?`${fmt(cjpState.balanceCents/100)} ${unit}`:t('Jackpot not active'));
 caption.textContent=enabled?`${t('Live pool')} · ${fmt(cjpState.balanceCents/100)} ${unit}`:t(valid?'Jackpot not active':'Loading jackpot…');
 $('cjpStatus').textContent=caption.textContent;$('cjpRules').textContent=t(gameMode==='LOBBY'?'cgJackpotRules':'cgJackpotClub');
 $('cjpLevels').replaceChildren(...(enabled?cjpState.levels:[]).map(l=>{const node=document.createElement('article');const title=document.createElement('strong');title.textContent=l.tier;const prize=document.createElement('b');prize.textContent=`${l.prizeBps/100}%`;const detail=document.createElement('small');detail.textContent=`${t('Prize share')} · ${t('Tier chance')}: ${l.probabilityBps/100}%`;node.append(title,prize,detail);return node;}));
 $('cjpTopUp').hidden=!(enabled&&player?.role==='CREATOR');$('cjpTopUpLabel').textContent=t('Pool top-up (Gold)');$('cjpAdd').textContent=t(cjpTopUp?'Retry same top-up':'Add to pool');$('cjpAmount').disabled=Boolean(cjpTopUp);
 $('cjpHistoryTitle').textContent=t('Recent jackpots');$('cjpMineTitle').textContent=t('My jackpot awards');$('cjpMineSection').hidden=!player;
}
function cjpList(id,rows,mine){const list=$(id);list.replaceChildren();if(!rows.length){const li=document.createElement('li');li.textContent=t('No jackpot awards yet.');list.append(li);return;}for(const r of rows){const li=document.createElement('li');const label=document.createElement('span'),amount=document.createElement('strong');label.textContent=`#${r.roundId} · ${r.tier}`;amount.textContent=`+${fmt((mine?r.amountCents:r.awardCents)/100)} ${gameMode==='LOBBY'?'Gold':'chips'}`;li.append(label,amount);list.append(li);}}
async function cjpFetch(){
 if(cjpBusy||activeView!=='colorGameView')return;const mode=gameMode,owner=player?.id;cjpBusy=true;
 if(cjpKey!==mode||cjpOwner!==owner){cjpOwner=owner;cjpState=null;cjpKey=mode;cjpRender();$('cjpHistory').replaceChildren();$('cjpMine').replaceChildren();}
 try{const state=await api('color-game/jackpot?mode='+mode);if(mode!==gameMode||owner!==player?.id)return;cjpState=state;cjpRender();
  if(cjpDialog.open){const [history,mine]=await Promise.all([api('color-game/jackpot/history?mode='+mode),owner?api('color-game/jackpot/awards?mode='+mode):Promise.resolve([])]);if(mode!==gameMode||owner!==player?.id)return;cjpList('cjpHistory',history,false);cjpList('cjpMine',mine,true);}
 }catch{if(mode===gameMode)$('cjpStatus').textContent=t('Jackpot unavailable');}finally{cjpBusy=false;}
}
$('cgJackpotHelp').onclick=()=>{cjpRender();cjpDialog.showModal();void cjpFetch();};$('cgJackpotClose').onclick=()=>cjpDialog.close();
$('cjpTopUp').onsubmit=async e=>{e.preventDefault();const button=$('cjpAdd');if(button.disabled)return;const owner=player?.id,mode=gameMode;if(!owner||player.role!=='CREATOR')return;
 if(!cjpTopUp){const cents=Math.round(Number($('cjpAmount').value)*100);if(!Number.isSafeInteger(cents)||cents<100||cents>10000000000)return;cjpTopUp={owner,mode,requestId:requestUuid(),amountCents:cents};}if(cjpTopUp.owner!==owner||cjpTopUp.mode!==mode){$('cjpMessage').textContent=t('Retry same top-up');return;}
 button.disabled=true;try{const result=await api('color-game/jackpot/top-up?mode='+mode,'POST',{requestId:cjpTopUp.requestId,amountCents:cjpTopUp.amountCents});cjpTopUp=null;if(owner===player?.id&&mode===gameMode){cjpState=result;cjpKey=mode;$('cjpMessage').textContent=t('Pool updated');cjpRender();}}catch(error){$('cjpMessage').textContent=errorText(error);if(error.status>=400&&error.status<500)cjpTopUp=null;cjpRender();}finally{button.disabled=false;}};
const cjpOldRole=applyRole;applyRole=()=>{cjpOldRole();if(cjpOwner!==player?.id){cjpOwner=player?.id;$('cjpMine').replaceChildren();$('cjpMessage').textContent='';cjpTopUp=null;cjpRender();}};
const cjpOldLanguage=setLanguage;setLanguage=value=>{cjpOldLanguage(value);cjpRender();void cjpFetch();};
setInterval(()=>{if(activeView==='colorGameView')void cjpFetch();},2000);cjpRender();
