'use strict';
Object.assign(english,{crRulesText:'Each round starts with 10 seconds to bet. Place one bet per round, from 5 up to 500. The multiplier begins at 1.00× and may crash immediately. Cash out before the crash to receive stake × multiplier (rounded down to 0.01). At the exact crash time, the crash wins. Auto cash out can be set from 1.01× to 99.99× before betting and runs on the server even while offline. Uncashed bets lose their full stake. Bets cannot be cancelled. Manual cash out uses server receipt time; the animated multiplier is indicative and network delay matters. The flight is capped at 100×. Lobby Gold and Club chips are separate. Super Ace RTP settings do not apply.'});
Object.assign(filipino,{'Live table':'Live na mesa','Next flight in':'Susunod na lipad sa','Place your bet before takeoff':'Tumaya bago lumipad','Auto cash out':'Awtomatikong cash out','Target multiplier':'Target na multiplier','Place bet':'Tumaya','Cash out':'Kunin ang panalo','Bet amount':'Halaga ng taya','My last 20 bets':'Huling 20 taya ko','Confirmed bets in this wallet only. Results are independent.':'Mga kumpirmadong taya lamang sa wallet na ito. Hiwalay ang bawat resulta.','Manual cash out uses server receipt time. Network delay matters. Auto cash out runs on the server.':'Oras ng pagtanggap ng server ang gamit sa manual cash out. Mahalaga ang pagkaantala ng network. Sa server tumatakbo ang auto cash out.','Waiting for takeoff':'Naghihintay ng paglipad','Bet confirmed':'Kumpirmado ang taya','Cashed out':'Nakuha na','Crashed':'Bumagsak','Flying':'Lumilipad','Next round':'Susunod na laro','No bets yet.':'Wala pang taya.','One bet per round':'Isang taya bawat laro','Choose a valid bet and auto cash out target.':'Pumili ng wastong taya at target ng auto cash out.',crRulesText:'May 10 segundo para tumaya bago lumipad. Isang taya bawat laro, mula 5 hanggang 500. Nagsisimula sa 1.00× at maaaring bumagsak kaagad. Mag-cash out bago bumagsak para makuha ang taya × multiplier, binibilog pababa sa 0.01. Kapag sabay ang crash at cash out, crash ang mananaig. Maaaring itakda ang auto cash out mula 1.01× hanggang 99.99× bago tumaya. Gumagana ito sa server kahit offline. Mawawala ang buong taya kapag hindi nakapag-cash out. Hindi maaaring kanselahin ang taya. Oras ng pagtanggap ng server ang gamit sa manual cash out; gabay lamang ang animation. Hanggang 100× ang lipad. Hiwalay ang Lobby Gold at Club chips. Hindi naaangkop ang RTP ng Super Ace.'});
let crState=null,crBets=[],crPending=null,crOwner='',crPoll=false,crSending=false,crFetched=0,crOffset=0,crGeneration=0,crError='',crHistoryStamp='',crRowsStamp='',crFrame=0,crCelebrateKey='';
function crKey(){return (player?.id||'guest')+':'+gameMode}
function crMine(){return crBets.find(b=>b.tableRoundId===crState?.roundId)}
function crLocked(){crReset();return crSending||Boolean(crPending)||crBets.some(b=>b.status==='ACTIVE')}
function crSave(){try{if(player&&crOwner===crKey()){const key='cr-pending-'+crOwner;crPending?sessionStorage.setItem(key,JSON.stringify(crPending)):sessionStorage.removeItem(key)}}catch{}}
function crReset(){if(crOwner===crKey())return;crOwner=crKey();crGeneration++;crState=null;crBets=[];crPending=null;crFetched=0;crError='';crHistoryStamp='';crRowsStamp='';$('crWin').hidden=true;try{const saved=JSON.parse(sessionStorage.getItem('cr-pending-'+crOwner)||'null');if(saved?.owner===crOwner)crPending=saved;}catch{}}
function crCue(win=false){if(activeView!=='crashView'||document.hidden||!sound||!volume)return;openAudio();(win?[523,659,784]:[420]).forEach((n,i)=>tone(n,.13,'triangle',i*.1))}
function crUpdate(){
 crReset();const mine=crMine(),fresh=Date.now()-crFetched<3000,phase=crState?.phase,betting=phase==='BETTING'&&Date.now()+crOffset<crState.flightAt;
 $('crBalance').textContent=player?fmt(balance):'—';$('crCurrency').textContent=gameMode==='LOBBY'?'Gold':'chips';$('crOwn').textContent=mine?money(mine.betCents):'—';$('crReturn').textContent=mine?money(mine.payoutCents):'—';
 for(const [id,mode]of[['crLobby','LOBBY'],['crClub','CLUB']]){$(id).setAttribute('aria-pressed',String(gameMode===mode));$(id).disabled=crLocked()||busy||modeChanging;}
 const action=$('crAction'),cash=mine?.status==='ACTIVE'&&phase==='FLYING';action.classList.toggle('cash',cash);action.textContent=t(crSending?'Confirming your bet…':cash?'Cash out':mine?.status==='ACTIVE'?'Waiting for takeoff':mine?'Next round':'Place bet');
 action.disabled=crSending||Boolean(crPending)||!fresh||Boolean(player&&!ready)||modeChanging||busy||pending||autoActive()||free>0||!(cash||betting&&!mine);
 $('crStatus').textContent=crError||(!player?t('Sign in to place a bet'):!fresh?t('Reconnecting…'):mine?t(mine.status==='ACTIVE'?'Bet confirmed':mine.status==='CASHED_OUT'?'Cashed out':'Crashed'):t('Place your bet before takeoff'));
 $('crRetry').hidden=!crPending||crSending;$('crSound').textContent=sound&&volume?'♫':'♫ ×';
 for(const el of document.querySelectorAll('#crStake,#crHalf,#crDouble,[data-cr-chip],#crAutoEnabled,#crAuto'))el.disabled=Boolean(mine)||crSending||Boolean(crPending);$('crAuto').disabled||=!$('crAutoEnabled').checked;
 if(crState){$('crRound').textContent='#'+crState.roundId;$('crSky').dataset.phase=phase;$('crPhase').textContent=t(phase==='BETTING'?'BETTING OPEN':phase==='FLYING'?'Flying':'Crashed');$('crPlayers').textContent=crState.bettors;$('crPool').textContent=money(crState.wagerCents);$('crPaid').textContent=money(crState.paidCents);}
 const stamp=language+JSON.stringify(crBets);if(stamp!==crRowsStamp){crRowsStamp=stamp;$('crBetsHistory').innerHTML=crBets.length?crBets.map(b=>'<div class="cr-bet-row"><span>#'+b.tableRoundId+'<small>'+t('Bet')+' '+money(b.betCents)+'</small></span><span>'+t(b.status==='ACTIVE'?'Bet confirmed':b.status==='CASHED_OUT'?'Cashed out':'Crashed')+'<small>'+(b.cashoutBps?(b.cashoutBps/100).toFixed(2)+'×':'—')+'</small></span><span class="'+(b.payoutCents>b.betCents?'won':'')+'">'+money(b.payoutCents)+'<small>'+t('Net')+' '+(b.status==='ACTIVE'?'—':money(b.payoutCents-b.betCents))+'</small></span></div>').join(''):'<p class="cr-disclaimer">'+t('No bets yet.')+'</p>';}
 if(mine?.status==='CASHED_OUT'&&mine.payoutCents>mine.betCents&&crCelebrateKey!==crOwner+mine.requestId){crCelebrateKey=crOwner+mine.requestId;celebrateWin('crashView',mine.requestId,mine.betCents,mine.payoutCents);$('crWin').innerHTML='<small>'+t('Cashed out')+' · '+(mine.cashoutBps/100).toFixed(2)+'×</small>'+t('Net win')+' +'+money(mine.payoutCents-mine.betCents);$('crWin').hidden=false;crCue(true);}
}
async function crLoad(){
 crReset();if(crPoll||crSending)return;crPoll=true;const owner=crOwner,generation=crGeneration,mode=gameMode;
 const current=()=>owner===crKey()&&generation===crGeneration&&!crSending;
 try{const state=await api('crash/table?mode='+mode),received=Date.now();const [bets,history]=await Promise.all([player?api('crash/bets?mode='+mode):[],api('crash/history')]);const wallet=player?await api('me?mode='+mode):null;if(!current())return;
  if(crState?.roundId!==state.roundId)$('crWin').hidden=true;crState=state;crOffset=state.serverTime-received;crBets=bets;crFetched=Date.now();if(wallet){applyWallet(wallet);ready=canPlay(wallet);}crError='';
  const stamp=JSON.stringify(history);if(stamp!==crHistoryStamp){crHistoryStamp=stamp;$('crHistory').innerHTML=history.map(r=>'<span class="'+(r.crashBps>=200?'high':'')+'" title="#'+r.roundId+'">'+(r.crashBps/100).toFixed(2)+'×</span>').join('');}
 }catch(e){if(current()){crError=t('Reconnecting…')+' '+errorText(e);if(e.status===401){ready=false;showLogin();}}}finally{crPoll=false;crUpdate();if(crPending&&ready&&!crSending)void crSend();}
}
async function crSend(){
 if(crSending||!crPending||!ready)return;const owner=crOwner,mode=gameMode,request=crPending;crSending=true;crGeneration++;busy=true;crUpdate();
 try{if(request.kind==='bet'&&request.body.expectedRevision===undefined){const wallet=await api('me?mode='+mode);if(owner!==crKey())return;applyWallet(wallet);request.body.expectedRevision=revision;crSave();}
  const result=await api(request.kind==='bet'?'crash/bets?mode='+mode:'crash/cashout?mode='+mode,'POST',request.body);if(owner!==crKey())return;crBets=[result,...crBets.filter(b=>b.requestId!==result.requestId)].slice(0,20);crPending=null;crSave();crError='';crCue();applyWallet(await api('me?mode='+mode));
 }catch(e){if(owner===crKey()){if(e.code==='STALE_STATE'&&request.kind==='bet'){delete request.body.expectedRevision;crSave();}else if(e.status===401){ready=false;showLogin();}else if(e.status>=400&&e.status<500){crPending=null;crSave();}crError=e.status?errorText(e):t('Connection lost. Retry uses the same request and cannot charge twice.');}}
 finally{crSending=false;busy=false;crUpdate();}
}
$('crAction').onclick=()=>{if(!player){showLogin();return}if(!ready||crSending||crPending||Date.now()-crFetched>=3000)return;const mine=crMine();if(mine?.status==='ACTIVE'&&crState?.phase==='FLYING')crPending={owner:crOwner,kind:'cash',body:{requestId:mine.requestId}};else{
 const amount=Number($('crStake').value),target=Number($('crAuto').value),auto=$('crAutoEnabled').checked?Math.round(target*100):0;if(!Number.isFinite(amount)||amount<5||amount>500||!Number.isFinite(target)||auto&&(auto<101||auto>9999)){crError=t('Choose a valid bet and auto cash out target.');crUpdate();return}if(!crState||crState.phase!=='BETTING'||mine)return;
 crPending={owner:crOwner,kind:'bet',body:{requestId:requestUuid(),tableRoundId:crState.roundId,betCents:Math.round(amount*100),autoCashoutBps:auto}};}crSave();void crSend();};
function crAnimate(){cancelAnimationFrame(crFrame);if(activeView!=='crashView'||document.hidden)return;const s=crState;if(s){const now=Date.now()+crOffset,phase=s.phase,point=phase==='FLYING'?Date.now()-crFetched<3000?Math.min(10000,Math.floor(100*Math.exp(Math.max(0,now-s.flightAt)/8000))):s.multiplierBps:s.multiplierBps;
 $('crCaption').textContent=t(phase==='BETTING'?'Next flight in':phase==='FLYING'?'Flying':'Crashed');$('crMultiplier').textContent=phase==='BETTING'?Math.max(0,Math.ceil((s.flightAt-now)/1000)).toString().padStart(2,'0'):(point/100).toFixed(2)+'×';$('crHint').textContent=t(phase==='BETTING'?'Place your bet before takeoff':phase==='FLYING'?'Cash out':'Next round');
 const progress=phase==='BETTING'||matchMedia('(prefers-reduced-motion: reduce)').matches?0:Math.min(1,Math.log(point/100)/Math.log(100)),x=.16+progress*.66,y=.8-progress*.49;$('crRocket').style.setProperty('--rx',x);$('crRocket').style.setProperty('--ry',y);$('crTrail').setAttribute('d',`M 40 330 Q ${x*640*.55} 330 ${x*640} ${y*380}`);
 }crFrame=requestAnimationFrame(crAnimate);}
$('crLobby').onclick=()=>switchMode('LOBBY');$('crClub').onclick=()=>switchMode('CLUB');$('crRetry').onclick=()=>crSend();$('crAutoEnabled').onchange=crUpdate;$('crHalf').onclick=()=>$('crStake').value=Math.max(5,Math.floor(Number($('crStake').value)*50)/100);$('crDouble').onclick=()=>$('crStake').value=Math.min(500,Number($('crStake').value)*2);document.querySelectorAll('[data-cr-chip]').forEach(b=>b.onclick=()=>$('crStake').value=b.dataset.crChip);
$('crRulesButton').onclick=()=>$('crRules').showModal();$('crRulesClose').onclick=()=>$('crRules').close();$('crSound').onclick=()=>{$('sound').click();crUpdate();};
const crOldLanguage=setLanguage;setLanguage=value=>{crOldLanguage(value);crUpdate();};const crOldHelp=$('help').onclick;$('help').onclick=()=>activeView==='crashView'?$('crRules').showModal():crOldHelp();
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&activeView==='crashView'){void crLoad();crAnimate();}else cancelAnimationFrame(crFrame);});
setInterval(()=>{if(activeView==='crashView'){crUpdate();if(!crFrame||document.hidden===false)crAnimate();if(Date.now()-crFetched>700)void crLoad();}else{cancelAnimationFrame(crFrame);crFrame=0;}},200);localize();
