'use strict';
let gameMode='LOBBY',modeChanging=false;try{gameMode=sessionStorage.getItem('ace-mode')==='CLUB'?'CLUB':'LOBBY'}catch{}
const $=id=>document.getElementById(id), bets=[10,20,50,100,200,500];
const defs={A:{suit:'♠',cls:'ace',pay:.34},K:{suit:'♥',cls:'red',pay:.2125},Q:{suit:'♦',cls:'red',pay:.2125},J:{suit:'♣',cls:'',pay:.1275},'10':{suit:'♠',cls:'',pay:.1275},'9':{suit:'♥',cls:'red',pay:.085},'8':{suit:'♣',cls:'',pay:.068},'7':{suit:'♦',cls:'red',pay:.051},W:{suit:'♛',cls:'wild'},S:{suit:'',cls:'scatter'}};
const weights={A:8,K:10,Q:12,J:14,'10':16,'9':18,'8':20,'7':22,W:1,S:3};
const bag=Object.entries(weights).flatMap(([symbol,weight])=>Array(weight).fill(symbol));
const autoOptions=[10,25,50,100,250,500];let selectedAuto=10,autoRun=null;
const autoActive=()=>Boolean(autoRun?.active);
let autoTimer=null,activeFree=false;
let ready=false,player=null,revision=0,pending=null;
let balance=0,betIndex=1,free=0,busy=false,turbo=false,auto=0,sound=true,audioCtx,board=[],last=0;
const fmt=n=>new Intl.NumberFormat(language==='fil'?'fil-PH':'en-PH',{maximumFractionDigits:2}).format(n);
const round=n=>Math.round(n*100)/100;
const sleep=ms=>new Promise(r=>setTimeout(r,document.hidden?0:matchMedia('(prefers-reduced-motion: reduce)').matches?Math.min(ms,90):ms));
function cardNode(s,c,r){const d=defs[s],el=document.createElement('div');el.className=`card ${d.cls} ${s==='K'?'court king':s==='Q'?'court queen':s==='J'?'court jack':''}`;el.dataset.pos=c+','+r;el.setAttribute('aria-label',s==='W'?'Wild':s==='S'?'Scatter':s);const label=s==='W'?'W':s==='S'?'✦':s;el.innerHTML=`<span class="card-corner">${label}<small>${d.suit||'✦'}</small></span><span class="card-center"><span class="card-emblem">${s==='W'?'♛':s==='S'?'✦':d.suit}</span><span class="rank">${s==='W'?'WILD':s==='S'?'SCATTER':s}</span></span><span class="card-corner opposite" aria-hidden="true">${label}<small>${d.suit||'✦'}</small></span>`;return el}
const themes={emerald:{name:'EMERALD CLUB',colors:['#f4d37b','#c4ffe3'],glyph:'✦'},ruby:{name:'ROYAL RUBY',colors:['#ffd094','#ff8fac'],glyph:'♦'},sapphire:{name:'MIDNIGHT SAPPHIRE',colors:['#c9e6ff','#91edff'],glyph:'✧'},neon:{name:'NEON TOKYO',colors:['#f09aff','#76ffed'],glyph:'✶'},classic:{name:'CLASSIC ROYALE',colors:['#ffe496','#eab34b'],glyph:'♠'}};
let currentTheme='emerald';
function setTheme(key){if(busy||autoActive())return false;if(!Object.hasOwn(themes,key))return false;currentTheme=key;document.body.dataset.theme=key;$('clubName').textContent='LUCKY SEVEN';$('winKicker').textContent='✦ '+themes[key].name+' ✦';for(const k of Object.keys(themes))$('theme-'+k).setAttribute('aria-pressed',String(k===key));try{localStorage.setItem('superace-theme',key)}catch{}if(typeof update==='function')update();return true}
const reduced=()=>document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches;
const activeAnimations=new Set();
// One compositor-animated strip per reel; no repeated card resets or per-frame DOM writes.
const tracks=()=>[...$('board').children].map(column=>column.firstElementChild);
async function animateNode(el,frames,options){if(reduced()||!el.animate)return;const animation=el.animate(frames,{...options,fill:'both'});activeAnimations.add(animation);try{await animation.finished}catch{}finally{activeAnimations.delete(animation);animation.cancel()}}
function render(){const frag=document.createDocumentFragment();board.forEach((col,c)=>{const column=document.createElement('div'),track=document.createElement('div');column.className='column';track.className='reel-track';col.forEach((s,r)=>track.append(cardNode(s,c,r)));column.append(track);frag.append(column)});$('board').replaceChildren(frag)}
async function rollReels(next){const reelTracks=tracks(),fast=turbo;const metrics=reelTracks.map(track=>{const first=track.children[0],second=track.children[1];return second.offsetTop-first.offsetTop});const jobs=reelTracks.map((track,c)=>{const step=metrics[c],count=(fast?8:18)+c*3,old=[...track.children];const fillers=Array.from({length:count},()=>cardNode(bag[Math.floor(Math.random()*bag.length)],c,-1));const final=next[c].map((s,r)=>cardNode(s,c,r));const fragment=document.createDocumentFragment();fragment.append(...final,...fillers,...old);track.replaceChildren(fragment);track.classList.add('running');const distance=(count+4)*step;return animateNode(track,[{transform:`translate3d(0,${-distance}px,0)`},{transform:'translate3d(0,0,0)'}],{duration:(fast?480:1120)+c*(fast?55:115),easing:'cubic-bezier(.18,.03,.20,1)'}).then(()=>{track.replaceChildren(...final);track.classList.remove('running');tone(260+c*50,.085);if(next[c].includes('S'))playCue('scatter');else if(next[c].includes('W'))playCue('wild');const seen=next.slice(0,c+1).flat().filter(s=>s==='S').length;for(let j=1;j<=3;j++)$('scatter'+j).classList.toggle('lit',seen>=j);if(seen>=3)$('scatterLabel').textContent='BONUS +8 '+t('FREE SPINS')})});await Promise.all(jobs);board=next}
async function tumble(hits,nextBoard){const reelTracks=tracks(),fast=turbo;const plans=reelTracks.map((track,c)=>{const old=[...track.children],step=old[1].offsetTop-old[0].offsetTop;return{track,c,old,step,survivors:old.map((el,r)=>({el,r,s:board[c][r]})).filter(o=>!hits.has(c+','+o.r))}});
await Promise.all(plans.flatMap(({old,c})=>old.filter((_,r)=>hits.has(c+','+r)).map(el=>animateNode(el,[{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(.82)'}],{duration:fast?90:160,easing:'ease-out'}))));
const jobs=[];for(const{track,c,old,step,survivors}of plans){const count=4-survivors.length;if(!count)continue;const fresh=nextBoard[c].slice(0,count);board[c]=[...nextBoard[c]];old.filter((_,r)=>hits.has(c+','+r)).forEach(el=>el.remove());const nodes=fresh.map((s,r)=>cardNode(s,c,r));track.prepend(...nodes);nodes.forEach((el,r)=>jobs.push(animateNode(el,[{transform:`translate3d(0,${-count*step}px,0)`},{transform:'translate3d(0,0,0)'}],{duration:fast?220:410,delay:r*(fast?8:16),easing:'cubic-bezier(.25,.05,.35,1)'})));survivors.forEach((o,i)=>{o.el.classList.remove('win');o.el.dataset.pos=c+','+(count+i);const distance=(o.r-count-i)*step;if(distance)jobs.push(animateNode(o.el,[{transform:`translate3d(0,${distance}px,0)`},{transform:'translate3d(0,0,0)'}],{duration:fast?220:410,easing:'cubic-bezier(.25,.05,.35,1)'}))})}await Promise.all(jobs)}
function update(){
 if(typeof modeUI==='function')modeUI();
 document.querySelectorAll('[data-guest]').forEach(el=>el.hidden=Boolean(player));
 $('balance').textContent=fmt(balance);$('bet').textContent=fmt(bets[betIndex]);$('free').textContent=String(free).padStart(2,'0');$('lastWin').textContent=fmt(last);$('roundTotal').textContent=fmt(last);
 const locked=!ready||modeChanging||Boolean(pending)||busy||autoActive();document.body.classList.toggle('free-mode',free>0||(busy&&activeFree));$('minus').disabled=locked||free>0||betIndex===0;$('plus').disabled=locked||free>0||betIndex===bets.length-1;$('spin').disabled=busy||modeChanging||!ready||autoActive();$('reset').disabled=busy;$('autoCount').disabled=locked;$('auto').disabled=!ready||Boolean(pending)||(busy&&!autoActive());$('turbo').disabled=busy||autoActive();
 $('spinLabel').textContent=busy?'…':t(pending?'RETRY':free>0?'FREE':'SPIN');$('mode').textContent=busy&&activeFree?t('FREE SPIN IN PROGRESS'):free>0?free+' '+t('FREE SPINS'):'♠ '+themes[currentTheme].name;
 auto=autoRun?Math.max(0,autoRun.planned-autoRun.completed):0;$('auto').textContent=autoActive()?'■ '+t('Stop')+' · '+auto+' '+t('paid'):'↻ '+t('Autoplay')+' · '+selectedAuto;$('auto').classList.toggle('on',autoActive());$('auto').setAttribute('aria-pressed',String(autoActive()));
 $('autoProgress').textContent=autoRun?t(({RUNNING:'Running',COMPLETED:'Completed',STOPPED:'Stopped',INSUFFICIENT_FUNDS:'Not enough chips.',ACCOUNT_DISABLED:'Stopped'})[autoRun.reason]||'Stopped')+' · '+autoRun.completed+'/'+autoRun.planned+' '+t('paid')+' + '+autoRun.freeCompleted+' '+t('free')+' · '+t('Net')+' '+fmt(autoRun.netCents/100):t('Autoplay counts paid spins only. Free spins are additional.');
 for(const key of Object.keys(themes))$('theme-'+key).disabled=busy||autoActive();
}
let masterGain,volume=.6;
function soundUI(message){$('sound').textContent=sound?'♪':'♪ ×';$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?t('Sound off'):t('Sound on'));if(message)$('audioState').textContent=message}
function openAudio(){if(!sound)return null;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('unsupported');if(!audioCtx||audioCtx.state==='closed'){audioCtx=new Audio();masterGain=audioCtx.createGain();masterGain.connect(audioCtx.destination)}masterGain.gain.setValueAtTime(volume,audioCtx.currentTime);if(audioCtx.state==='suspended'){Promise.resolve(audioCtx.resume()).then(()=>soundUI(audioCtx.state==='running'?t('Sound on'):t('Tap Test sound to enable audio.'))).catch(()=>soundUI(t('Tap Test sound to enable audio.')))}else soundUI(volume?t('Sound on'):t('Volume')+' 0%');return audioCtx}catch{soundUI(t('Audio unavailable in this browser.'));return null}}
function tone(freq=440,duration=.12,type='triangle',delay=0,endFreq=freq){const ctx=openAudio();if(!ctx)return;const time=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,time);o.frequency.exponentialRampToValueAtTime(endFreq,time+duration);g.gain.setValueAtTime(.001,time);g.gain.linearRampToValueAtTime(.16,time+.008);g.gain.exponentialRampToValueAtTime(.001,time+duration);o.connect(g);g.connect(masterGain);o.onended=()=>{o.disconnect();g.disconnect()};o.start(time);o.stop(time+duration+.02)}
function playCue(kind){if(kind==='spin'){tone(110,.24,'triangle',0,350);tone(180,.18,'sine',.06,520)}else if(kind==='wild'){tone(660,.16,'sine');tone(990,.22,'triangle',.09)}else if(kind==='scatter'){[659,880,1319].forEach((f,i)=>tone(f,.22,'sine',i*.08))}else if(kind==='bonus'){[523,659,784,1047,1319].forEach((f,i)=>tone(f,.32,'triangle',i*.1))}}
function winTier(win,wager){return win>=wager*50?'SUPER ACE WIN!':win>=wager*20?'MEGA WIN!':win>=wager*5?'BIG WIN!':null}
function scatterAward(grid){return grid.flat().filter(s=>s==='S').length>=3?8:0}
const counters=new Map();
function countTo(el,from,to,duration=500){const previous=counters.get(el);if(previous){cancelAnimationFrame(previous.id);previous.resolve()}el.textContent=fmt(from);if(reduced()){el.textContent=fmt(to);return Promise.resolve()}return new Promise(resolve=>{const state={id:0,resolve},start=performance.now();counters.set(el,state);function frame(now){const t=Math.min(1,(now-start)/duration);el.textContent=fmt(round(from+(to-from)*(1-(1-t)**3)));if(t<1)state.id=requestAnimationFrame(frame);else{counters.delete(el);resolve()}}state.id=requestAnimationFrame(frame)})}
function burst(x,y,count=16,large=false){if(reduced())return;const fragment=document.createDocumentFragment(),nodes=[];for(let i=0;i<count;i++){const p=document.createElement('span');p.className='spark';p.textContent=large?(i%3?'◉':themes[currentTheme].glyph):themes[currentTheme].glyph;p.style.cssText=`left:${x}px;top:${y}px;font-size:${large?16+Math.random()*14:12+Math.random()*10}px;color:${themes[currentTheme].colors[i%3?0:1]};`;nodes.push(p);fragment.append(p)}document.body.append(fragment);nodes.forEach((p,i)=>{const angle=Math.PI*2*i/count,reach=(large?110:25)+Math.random()*(large?210:55),dx=Math.cos(angle)*reach,dy=Math.sin(angle)*reach;void animateNode(p,[{transform:'translate3d(-50%,-50%,0) scale(.4)',opacity:0},{transform:`translate3d(${dx*.5}px,${dy*.5}px,0) scale(1)`,opacity:1,offset:.22},{transform:`translate3d(${dx}px,${dy+(large?210:35)}px,0) rotate(${i*47}deg) scale(.4)`,opacity:0}],{duration:large?1300:600,easing:'cubic-bezier(.15,.4,.5,1)'}).finally(()=>p.remove())})}
function winChime(level=0){const notes=level>1?[392,523,659,784,1047,1319]:[523,659,784];notes.forEach((f,i)=>tone(f,.18+level*.05,'triangle',i*.075))}
async function celebrateCascade(hits,won,multiplier,previous){$('chainValue').textContent='×'+multiplier;const machine=document.querySelector('.machine');machine.classList.remove('paying');requestAnimationFrame(()=>machine.classList.add('paying'));$('board').classList.add('has-wins');const cards=[...document.querySelectorAll('.card')].filter(el=>hits.has(el.dataset.pos));const rects=cards.slice(0,7).map(el=>el.getBoundingClientRect());rects.forEach(r=>burst(r.x+r.width/2,r.y+r.height/2,5));const pop=$('payoutPop');pop.textContent='+'+fmt(won)+'  ·  ×'+multiplier;winChime(multiplier>=3?1:0);await Promise.all([countTo($('roundTotal'),previous,last,turbo?220:480),countTo($('balance'),round(balance-won),balance,turbo?220:480),animateNode(pop,[{opacity:0,transform:'translate(-50%,-25%) scale(.8)'},{opacity:1,transform:'translate(-50%,-50%) scale(1)',offset:.2},{opacity:1,transform:'translate(-50%,-50%) scale(1)',offset:.72},{opacity:0,transform:'translate(-50%,-80%) scale(.96)'}],{duration:turbo?330:750,easing:'ease-out'})]);$('board').classList.remove('has-wins')}
async function announce(title,amount){const numeric=typeof amount==='number';$('winTitle').textContent=title;$('winCaption').textContent=numeric?t('TOTAL WIN'):t('BONUS ACTIVATED');$('winAmount').textContent=numeric?'0':amount;$('overlay').classList.add('show');const r=$('overlay').getBoundingClientRect();burst(r.x+r.width/2,r.y+r.height*.45,44,true);winChime(2);await Promise.all([numeric?countTo($('winAmount'),0,amount,turbo?550:1150):Promise.resolve(),sleep(turbo?850:1750)]);$('overlay').classList.remove('show')}
function requestUuid(){if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=[...b].map(v=>v.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)}
function savePending(value){pending=value;try{if(value)sessionStorage.setItem('ace-pending-'+gameMode,JSON.stringify(value));else sessionStorage.removeItem('ace-pending-'+gameMode)}catch{}}
let refreshPromise=null;
async function api(path,method='GET',data,retried=false){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),15000);try{const response=await fetch('/api/'+path+(path.includes('?')?'&':'?')+'mode='+gameMode,{method,credentials:'same-origin',cache:'no-store',signal:abort.signal,headers:{'Content-Type':'application/json','X-Game-Client':'web',...(player?{'X-CSRF-Token':player.csrf}:{})},...(data?{body:JSON.stringify(data)}:{})});const body=await response.json();if(response.status===401&&!retried&&!['login','register','refresh'].includes(path)){if(!refreshPromise)refreshPromise=api('refresh','POST',null,true).then(me=>{applyWallet(me);return me}).finally(()=>refreshPromise=null);await refreshPromise;return api(path,method,data,true)}if(!response.ok){const error=new Error(body.code||'SERVER_ERROR');error.status=response.status;error.code=body.code;throw error}return body}finally{clearTimeout(timer)}}
function applyWallet(wallet){if(wallet.role!=='PLAYER')gameMode='CLUB';player=wallet;revision=wallet.revision;balance=wallet.balanceCents/100;free=wallet.freeSpins;if(free>0){const index=bets.indexOf(wallet.lockedBetCents/100);if(index>=0)betIndex=index}$('connection').textContent=wallet.displayName;}
let seenRound=0,polling=false,pollTimer=null;
function snapshot(result){if(!result)return;board=result.outcome.finalBoard;last=result.outcome.winCents/100;seenRound=Math.max(seenRound,result.revision);render()}
async function displayRound(response){
 activeFree=response.freeSpin;const wager=response.betCents/100;balance=(response.balanceBeforeCents-(response.freeSpin?0:response.betCents))/100;free=response.freeSpins;last=0;$('chainValue').textContent='×1';document.querySelectorAll('.multi').forEach((e,i)=>e.classList.toggle('active',i===0));for(let i=1;i<=3;i++)$('scatter'+i).classList.remove('lit');$('scatterLabel').textContent='3 SCATTER → 8 '+t('FREE SPINS');update();playCue('spin');await rollReels(response.outcome.initialBoard);
 if(response.outcome.freeAward){playCue('bonus');await announce(response.outcome.freeAward+' '+t('FREE SPINS'),'✦ ✦ ✦')}
 for(let i=0;i<response.outcome.cascades.length;i++){const step=response.outcome.cascades[i],hits=new Set(step.hits),won=step.winCents/100;last=round(last+won);balance=round(balance+won);document.querySelectorAll('.multi').forEach((el,j)=>el.classList.toggle('active',j===Math.min(i,3)));document.querySelectorAll('.card').forEach(el=>el.classList.toggle('win',hits.has(el.dataset.pos)));$('status').textContent=t('Cascade')+' '+(i+1)+' · +'+fmt(won);update();await celebrateCascade(hits,won,step.multiplier,round(last-won));await tumble(hits,step.nextBoard)}
 snapshot(response);balance=response.balanceCents/100;free=response.freeSpins;const tier=winTier(last,wager);if(tier)await announce(tier,last);const net=last-(response.freeSpin?0:wager);$('netResult').textContent=(response.freeSpin?t('FREE'):t('Bet')+' '+fmt(wager))+' · '+t('Payout')+' '+fmt(last)+' · '+t('Net')+' '+(net>=0?'+':'')+fmt(net);$('netResult').className='session-result '+(net>0?'positive':net<0?'negative':'');$('status').textContent=t('Payout')+' '+fmt(last)+' · '+free+' '+t('FREE SPINS');
}
async function spin(){if(modeChanging||!ready||busy||polling||autoActive()||$('rules').open)return;if(player?.role!=='PLAYER'){showLogin();return}busy=true;let response=null;if(!pending)savePending({playerId:player.id,mode:gameMode,body:{requestId:requestUuid(),betCents:Math.round(bets[betIndex]*100),expectedRevision:revision}});$('status').textContent=t('Receiving result…');update();try{response=await api('spins','POST',pending.body);await displayRound(response);savePending(null);applyWallet(await api('me'));}catch(error){$('board').classList.remove('has-wins');$('overlay').classList.remove('show');if(response){snapshot(response);savePending(null);balance=response.balanceCents/100;free=response.freeSpins;revision=response.revision;}if(error.status>=400&&error.status<500){savePending(null);try{applyWallet(await api('me'))}catch{}if(error.status===401){ready=false;showLogin()}}$('status').textContent=response?t('Server result recovered.'):error.status?errorText(error):t('Connection lost. Retry uses the same request and cannot charge twice.');}finally{busy=false;activeFree=false;update()}return response}
async function syncAuto(animate=true){if(modeChanging||polling||busy||!ready||player?.role!=='PLAYER')return;polling=true;try{const state=await api('auto');autoRun=state.job;const latest=state.latest;if(latest&&latest.revision>seenRound){if(animate&&!document.hidden&&!$('gameView').hidden&&latest.revision===revision+1){busy=true;update();await displayRound(latest)}else snapshot(latest)}applyWallet(state.wallet);if(autoRun?.active){turbo=autoRun.turbo;$('turbo').classList.toggle('on',turbo)}$('connection').textContent=player.displayName;}catch(error){if(error.status===401){ready=false;showLogin()}else $('connection').textContent='OFFLINE';}finally{busy=false;activeFree=false;polling=false;update();}}
async function connect(){if(busy||polling)return;try{applyWallet(await api('me'));ready=player.role==='PLAYER';seenRound=0;autoRun=null;try{const saved=JSON.parse(sessionStorage.getItem('ace-pending-'+gameMode)||'null');if(saved?.playerId===player.id&&(saved.mode||'CLUB')===gameMode)pending=saved;else savePending(null)}catch{savePending(null)}if(pending){const i=bets.indexOf(pending.body.betCents/100);if(i>=0)betIndex=i}$('status').textContent=t(pending?'A spin is awaiting confirmation. Tap RETRY to recover the same result.':'Connected. Your wallet is saved on the server.');applyRole();await syncAuto(false);if($('loginDialog').open)$('loginDialog').close();}catch(error){ready=false;player=null;$('connection').textContent=t('Guest');$('status').textContent=t('Sign in to play.');applyRole();}update()}
$('spin').onclick=()=>{if(!player)showLogin();else spin()};$('minus').onclick=()=>{if(ready&&!pending&&!busy&&!autoActive()&&!free&&betIndex>0){betIndex--;update()}};$('plus').onclick=()=>{if(ready&&!pending&&!busy&&!autoActive()&&!free&&betIndex<bets.length-1){betIndex++;update()}};
$('turbo').onclick=()=>{if(busy||autoActive())return;turbo=!turbo;$('turbo').classList.toggle('on',turbo);$('turbo').setAttribute('aria-pressed',String(turbo))};$('autoCount').onchange=e=>{const count=Number(e.target.value);if(ready&&!pending&&!busy&&!autoActive()&&autoOptions.includes(count))selectedAuto=count;$('autoCount').value=String(selectedAuto);update()};
$('auto').onclick=async()=>{if(modeChanging||!ready||pending||polling||(busy&&!autoActive()))return;openAudio();$('auto').disabled=true;try{if(autoActive())autoRun=await api('auto/stop','POST',{runId:autoRun.runId});else autoRun=await api('auto/start','POST',{runId:requestUuid(),count:selectedAuto,betCents:Math.round(bets[betIndex]*100),expectedRevision:revision,turbo});}catch(e){toast(errorText(e))}finally{update();await syncAuto()}};
$('sound').onclick=()=>{sound=!sound;if(!sound&&masterGain)masterGain.gain.setValueAtTime(0,audioCtx.currentTime);soundUI(t(sound?'Sound on':'Sound off'));if(sound){openAudio();tone(660,.2)}};$('testSound').onclick=()=>{sound=true;openAudio();playCue('bonus')};$('volume').oninput=e=>{volume=Number(e.target.value)/100;if(masterGain)masterGain.gain.setValueAtTime(sound?volume:0,audioCtx.currentTime);soundUI(t('Volume')+' '+Math.round(volume*100)+'%')};$('reset').onclick=()=>connect();$('help').onclick=()=>$('rules').showModal();$('close').onclick=()=>$('rules').close();
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!document.querySelector('dialog[open]')&&!$('gameView').hidden&&!['BUTTON','INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();spin()}});
board=[['A','K','Q','J'],['K','A','10','Q'],['Q','J','A','10'],['J','Q','K','A'],['S','10','W','K']];render();for(const key of Object.keys(themes))$('theme-'+key).onclick=()=>setTheme(key);let savedTheme='emerald';try{savedTheme=localStorage.getItem('superace-theme')||'emerald'}catch{}setTheme(Object.hasOwn(themes,savedTheme)?savedTheme:'emerald');update();
$('paytable').innerHTML=Object.entries(defs).filter(([,d])=>d.pay).map(([symbol,d])=>`<tr><td>${symbol}</td>${[1,2,4].map(m=>'<td>×'+d.pay*m+'</td>').join('')}</tr>`).join('');
document.addEventListener('visibilitychange',()=>{if(document.hidden){activeAnimations.forEach(a=>{try{a.finish()}catch{a.cancel()}});for(const [el,c]of counters){cancelAnimationFrame(c.id);c.resolve();counters.delete(el)}}else void syncAuto(false)});
async function poll(){await syncAuto();pollTimer=setTimeout(poll,document.hidden?5000:900)}
