'use strict';
Object.assign(filipino,{'Guest':'Bisita','Register':'Magrehistro','Agent ID (6 digits)':'Agent ID (6 na numero)','Edit':'Baguhin','Enabled':'Aktibo','Save changes':'I-save ang mga pagbabago','Transfer chips':'Maglipat ng chips','Give chips':'Magbigay ng chips','Take chips':'Bawiin ang chips','Issue chips (Creator)':'Lumikha ng chips (Creator)','Target account':'Tatanggap na account','Amount':'Halaga','Cancel':'Kanselahin','Move children first before changing this role.':'Ilipat muna ang mga nasasakupan bago baguhin ang tungkulin.','Finish free spins and stop autoplay first.':'Tapusin muna ang libreng ikot at ihinto ang autoplay.','RTP target':'Target na RTP','Switch date':'Petsa ng pagbabago','Observed RTP':'Naobserbahang RTP','Enter your Agent ID to join their group.':'Ilagay ang Agent ID upang sumali sa kanilang grupo.'});
const registerBox=document.createElement('form');registerBox.id='registerForm';registerBox.hidden=true;
registerBox.innerHTML='<label><span data-i18n="Username">Username</span><input name="username" pattern="[A-Za-z0-9_]{3,40}" maxlength="40" autocomplete="username" required></label><label><span data-i18n="Password (6+ characters)">Password (6+ characters)</span><input name="password" type="password" minlength="6" maxlength="72" autocomplete="new-password" required></label><label><span data-i18n="Repeat password">Repeat password</span><input name="rePassword" type="password" minlength="6" maxlength="72" autocomplete="new-password" required></label><button type="submit" class="primary" data-i18n="Register">Register</button>';
$('loginForm').after(registerBox);const toggle=document.createElement('button');toggle.id='registerToggle';toggle.className='textbutton';toggle.dataset.i18n='Register';toggle.textContent=t('Register');registerBox.after(toggle);function showAuth(register=false){registerBox.hidden=!register;$('loginForm').hidden=register;toggle.dataset.i18n=register?'Sign in':'Register';toggle.textContent=t(toggle.dataset.i18n);const title=$('loginDialog').querySelector('h2');title.dataset.i18n=register?'Register':'Welcome to the table';title.textContent=t(title.dataset.i18n);if(!$('loginDialog').open)$('loginDialog').showModal();(register?registerBox:$('loginForm')).querySelector('input').focus();}
showLogin=()=>showAuth(false);toggle.onclick=()=>showAuth(registerBox.hidden);$('registerNav').onclick=()=>showAuth(true);
Object.assign(filipino,{
 'Ask your Agent for their 6-digit ID. Your Player ID is generated automatically.':'Hingin sa iyong Agent ang kanilang 6 na numerong ID. Awtomatikong gagawin ang iyong Player ID.',
 'Agent ID was not found, is inactive, or does not belong to an Agent. Ask your Agent for the correct ID.':'Hindi nakita ang Agent ID, hindi ito aktibo, o hindi ito ID ng isang Agent. Hingin sa iyong Agent ang tamang ID.',
 'This username is already taken. Choose another username.':'Ginagamit na ang username na ito. Pumili ng ibang username.',
 'Repeat password':'Ulitin ang password',
 'Passwords do not match.':'Hindi magkatugma ang mga password.',
 'Check the username and password.':'Suriin ang username at password.',
 'Create an account with your username and password.':'Gumawa ng account gamit ang iyong username at password.',
 'Password (6+ characters)':'Password (6+ na character)',
 'Password must contain at least 6 characters and at most 72 UTF-8 bytes.':'Ang password ay dapat may hindi bababa sa 6 na character at hindi hihigit sa 72 UTF-8 byte.'
});
const registrationError=document.createElement('p');registrationError.id='registerError';registrationError.className='error';registrationError.setAttribute('role','alert');registrationError.setAttribute('aria-live','polite');registerBox.querySelector('button').before(registrationError);
registerBox.noValidate=true;
function registrationMessage(error){const messages={PASSWORD_MISMATCH:'Passwords do not match.',DUPLICATE:'This username is already taken. Choose another username.',INVALID_REQUEST:'Check the username and password.',PASSWORD_LENGTH:'Password must contain at least 6 characters and at most 72 UTF-8 bytes.'};return t(messages[error.code]||'')||errorText(error);}
registerBox.addEventListener('input',()=>{registrationError.textContent='';registerBox.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'))});
registerBox.onsubmit=async e=>{e.preventDefault();const button=registerBox.querySelector('button');if(button.disabled)return;registrationError.textContent='';registerBox.elements.username.value=registerBox.elements.username.value.trim();
 if(!registerBox.reportValidity()){registrationError.textContent=t('Check the username and password.');return;}
 const password=registerBox.elements.password.value;if(password.length<6||new TextEncoder().encode(password).length>72){registrationError.textContent=t('Password must contain at least 6 characters and at most 72 UTF-8 bytes.');registerBox.elements.password.setAttribute('aria-invalid','true');registerBox.elements.password.focus();return;}
 if(password!==registerBox.elements.rePassword.value){registrationError.textContent=t('Passwords do not match.');registerBox.elements.rePassword.setAttribute('aria-invalid','true');registerBox.elements.rePassword.focus();return;}
 button.disabled=true;try{gameMode='LOBBY';try{sessionStorage.setItem('ace-mode','LOBBY')}catch{}const data=Object.fromEntries(new FormData(registerBox));const me=await api('register','POST',data);applyWallet(me);registerBox.reset();await connect();await showView('gameView');}catch(error){registrationError.textContent=registrationMessage(error)+(error.code?' ['+error.code+']':'');const field=error.code==='DUPLICATE'?'username':error.code==='PASSWORD_LENGTH'?'password':null;if(field){registerBox.elements[field].setAttribute('aria-invalid','true');registerBox.elements[field].focus();}}finally{button.disabled=false;}};

const editor=document.createElement('dialog');editor.id='accountEditor';editor.innerHTML='<h2 data-i18n="Edit">Edit</h2><form id="editAccountForm"><label><span data-i18n="Role">Role</span><select name="role" id="editRole"></select></label><label><span data-i18n="Parent account">Parent account</span><select name="parentId" id="editParent"></select></label><label><span data-i18n="Enabled">Enabled</span><input type="checkbox" name="enabled" id="editEnabled"></label><button type="submit" class="primary" data-i18n="Save changes">Save changes</button><button type="button" id="cancelEdit" data-i18n="Cancel">Cancel</button></form>';document.body.append(editor);let editing=null;
function editParents(){const ordinal=roles.indexOf($('editRole').value);$('editParent').innerHTML=accountRows.filter(a=>a.id!==editing.id&&roles.indexOf(a.role)===ordinal-1&&a.enabled).map(a=>'<option value="'+a.id+'">'+esc(a.publicCode+' · '+a.displayName)+'</option>').join('');$('editParent').disabled=ordinal===0;$('editParent').required=ordinal!==0;if(editing.parentId)$('editParent').value=editing.parentId;}
$('editRole').onchange=editParents;$('cancelEdit').onclick=()=>editor.close();$('editAccountForm').onsubmit=e=>{e.preventDefault();submit(e.target,async data=>{await api('accounts/'+editing.id,'PUT',{role:data.role,parentId:data.role==='CREATOR'?null:data.parentId,enabled:$('editEnabled').checked});editor.close();await loadAccounts()})};
const moveForm=document.createElement('form');moveForm.id='moveChipsForm';moveForm.dataset.admin='';moveForm.hidden=true;moveForm.className='panel form-grid';moveForm.innerHTML='<h2 data-i18n="Transfer chips">Transfer chips</h2><label><span data-i18n="Target account">Target account</span><select name="targetId" id="chipTarget" required></select></label><label><span data-i18n="Type">Type</span><select name="direction" id="chipDirection"><option value="GIVE" data-i18n="Give chips">Give chips</option><option value="TAKE" data-i18n="Take chips">Take chips</option></select></label><label><span data-i18n="Amount">Amount</span><input name="amount" type="number" min="0.01" max="1000000" step="0.01" required></label><button type="submit" data-i18n="Transfer chips">Transfer chips</button>';$('accountsTable').after(moveForm);let movement=null;
moveForm.onsubmit=e=>{e.preventDefault();submit(moveForm,async data=>{const b={targetId:data.targetId,direction:data.direction,amountCents:Math.round(Number(data.amount)*100)},key=JSON.stringify(b);if(!movement||movement.key!==key)movement={key,body:{...b,requestId:requestUuid()}};await api('chips/move','POST',movement.body);movement=null;applyWallet(await api('me'));applyRole();toast(t('Saved.'));await loadAccounts()})};
const baseErrorText=errorText;errorText=e=>e.code==='MOVE_CHILDREN_FIRST'?t('Move children first before changing this role.'):e.code==='FINISH_GAME_FIRST'?t('Finish free spins and stop autoplay first.'):baseErrorText(e);
const originalAccounts=loadAccounts;loadAccounts=async()=>{await originalAccounts();table('accountsTable',['ID','Username','Display name','Role','Parent account','Actions'],accountRows.filter(a=>player.role==='CREATOR'||a.id!==player.id).map(a=>[esc(a.publicCode),esc(a.username),esc(a.displayName),esc(a.role),esc(accountRows.find(p=>p.id===a.parentId)?.publicCode||'—'),a.id!==player.id&&['CREATOR','SUPER_AGENT'].includes(player.role)&&(player.role==='CREATOR'||roles.indexOf(a.role)>1)?'<button data-edit="'+a.id+'">'+esc(t('Edit'))+'</button>':'—']));$('accountsTable').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=accountRows.find(a=>a.id===b.dataset.edit);$('editRole').innerHTML=roles.filter((r,i)=>player.role==='CREATOR'||i>1).map(r=>'<option value="'+r+'">'+esc(r.replaceAll('_',' '))+'</option>').join('');$('editRole').value=editing.role;$('editEnabled').checked=editing.enabled;editParents();editor.showModal()});$('chipTarget').innerHTML=accountRows.filter(a=>a.id!==player.id&&a.enabled).map(a=>'<option value="'+a.id+'">'+esc(a.publicCode+' · '+a.displayName)+'</option>').join('');const issue=$('chipDirection').querySelector('[value="ISSUE"]');if(player.role==='CREATOR'&&!issue){const option=document.createElement('option');option.value='ISSUE';option.dataset.i18n='Issue chips (Creator)';option.textContent=t(option.dataset.i18n);$('chipDirection').append(option)}else if(player.role!=='CREATOR')issue?.remove();};
Object.assign(filipino,{'RTP settings':'Mga setting ng RTP','Target RTP (%)':'Target na RTP (%)','Save RTP':'I-save ang RTP','Use 1–100%, with up to two decimal places. Changes apply to new paid spins. Existing free spins keep their original rate.':'Gumamit ng 1–100%, hanggang dalawang decimal. Sa mga bagong bayad na ikot lamang ang pagbabago. Hindi magbabago ang kasalukuyang libreng ikot.','RTP saved.':'Na-save ang RTP.','Enter an RTP from 1 to 100 with at most two decimals.':'Ilagay ang RTP mula 1 hanggang 100 na may hanggang dalawang decimal.'});
const rtpPanel=document.createElement('section');rtpPanel.className='panel';rtpPanel.hidden=true;rtpPanel.dataset.creator='';
rtpPanel.innerHTML='<h2>Super Ace · <span data-i18n="RTP settings">RTP settings</span></h2><div class="rtp-settings-grid">'+['LOBBY','CLUB'].map(mode=>{const suffix=mode==='LOBBY'?'':'Club';return '<section class="rtp-setting-card"><h3>'+ (mode==='LOBBY'?'LOBBY · Gold':'LUCKY SEVEN · Club chips')+'</h3><p id="rtpInfo'+suffix+'" class="muted" role="status"></p><form id="rtpForm'+suffix+'" class="form-grid"><label><span data-i18n="Target RTP (%)">Target RTP (%)</span><input id="rtpTarget'+suffix+'" name="targetPercent" type="number" min="1" max="100" step="0.01" inputmode="decimal" required></label><button type="submit" data-i18n="Save RTP">Save RTP</button></form></section>';}).join('')+'</div><p data-i18n="Use 1–100%, with up to two decimal places. Changes apply to new paid spins. Existing free spins keep their original rate.">Use 1–100%, with up to two decimal places. Changes apply to new paid spins. Existing free spins keep their original rate.</p>';
$('gameView').append(rtpPanel);
let rtpLoaded=null,rtpSaving=false;
const rtpStates={LOBBY:{value:null,sequence:0},CLUB:{value:null,sequence:0}};
const rtpElement=(id,mode)=>$(id+(mode==='LOBBY'?'':'Club'));
function rtpButtons(){for(const mode of ['LOBBY','CLUB'])rtpElement('rtpForm',mode).querySelector('button').disabled=rtpSaving||!rtpStates[mode].value;}
function rtpVisibility(){const allowed=player?.role==='CREATOR';rtpPanel.hidden=!allowed;if(!allowed){rtpLoaded=null;for(const mode of ['LOBBY','CLUB']){rtpStates[mode].value=null;rtpStates[mode].sequence++;rtpElement('rtpInfo',mode).textContent='';rtpElement('rtpTarget',mode).value='';}rtpButtons();}return allowed;}
async function loadRtp(mode){
 if(!rtpVisibility())return;
 if(!mode)return Promise.all(['LOBBY','CLUB'].map(loadRtp));
 const owner=player.id,state=rtpStates[mode],sequence=++state.sequence;
 state.value=null;if(mode==='LOBBY')rtpLoaded=null;rtpButtons();
 try{
  const r=await api('rtp?mode='+mode);if(owner!==player?.id||player?.role!=='CREATOR'||sequence!==state.sequence)return;
  state.value=r;if(mode==='LOBBY')rtpLoaded=r;rtpElement('rtpTarget',mode).value=r.targetPercent;
  rtpElement('rtpInfo',mode).textContent=t('RTP target')+': '+r.targetPercent+'% · '+t('Observed RTP')+': '+(r.observedPercent==null?'—':r.observedPercent.toFixed(2)+'%');
 }catch(error){if(owner===player?.id&&sequence===state.sequence)rtpElement('rtpInfo',mode).textContent=errorText(error);}
 finally{rtpButtons();}
}
for(const mode of ['LOBBY','CLUB'])rtpElement('rtpForm',mode).onsubmit=e=>{
 e.preventDefault();const state=rtpStates[mode];if(rtpSaving||!state.value||player?.role!=='CREATOR')return;
 const owner=player.id,revision=state.value.revision,targetPercent=Number(rtpElement('rtpTarget',mode).value);rtpSaving=true;rtpButtons();
 void task(async()=>{try{await api('rtp?mode='+mode,'PUT',{targetPercent,revision});const wallet=await api('me');if(player?.id===owner){applyWallet(wallet);toast(mode+' · '+t('RTP saved.'));}}finally{rtpSaving=false;if(player?.id===owner)await loadRtp(mode);rtpButtons();}});
};
const rtpRoleBase=applyRole;applyRole=()=>{rtpRoleBase();if(rtpVisibility())void loadRtp();};
const rtpErrorBase=errorText;errorText=e=>e.code==='INVALID_RTP'?t('Enter an RTP from 1 to 100 with at most two decimals.'):rtpErrorBase(e);
const originalApplyWallet=applyWallet;applyWallet=wallet=>{originalApplyWallet(wallet);rtpVisibility();if(wallet.payoutScale)$('paytable').innerHTML=Object.entries(defs).filter(([,d])=>d.pay).map(([symbol,d])=>'<tr><td>'+symbol+'</td>'+[1,2,4].map(m=>'<td>×'+(d.pay*m*wallet.payoutScale).toFixed(6)+'</td>').join('')+'</tr>').join('');};
void loadRtp();setInterval(()=>{if(!document.hidden&&!rtpSaving&&!rtpPanel.contains(document.activeElement))void loadRtp()},60000);localize();
