 'use strict';
Object.assign(english,{luckyNineRules:'Lucky 9 — house variant. Bet 5–500. A fresh 52-card deck is shuffled without replacement for every round. You and the banker receive two cards. A=1, 2–9 face value, 10/J/Q/K=0. Only the last digit of the sum counts. If either initial hand is 8 or 9, both stand and settle immediately. Otherwise choose Draw one card or Stand. Only one extra card is allowed. The banker automatically draws on 0–5 and stands on 6–9. Higher final total wins; equal totals return the stake. A win returns 1.95× the stake (0.95× profit), a tie 1×, a loss 0. Returns round down to 0.01. Banker cards remain hidden until settlement. An unfinished round survives reload; you must finish it before starting another. These are the rules of this implementation, not a shared live-dealer table. Super Ace RTP settings do not apply.'});
Object.assign(filipino,{'Two cards. Your next move.':'Dalawang baraha. Ikaw ang pipili.','Banker':'Bangko','Your hand':'Iyong baraha','Draw one card':'Bumunot ng isa','Stand':'Manatili','Deal two cards':'Mamigay ng dalawang baraha','Choose draw or stand':'Pumili: bunot o manatili','Natural':'Natural','Points':'Puntos','Win returns 1.95× · Tie returns 1×':'Panalo 1.95× · Tabla 1×','House variant · one extra card':'Bersiyon ng bahay · isang dagdag na baraha',luckyNineRules:'Lucky 9 — bersiyon ng bahay. Tumaya ng 5–500. Bagong 52-barahang deck sa bawat laro, walang pag-ulit. Dalawang baraha sa iyo at sa bangko. A=1, 2–9 ayon sa bilang, 10/J/Q/K=0. Huling digit lang ng kabuuan ang puntos. Kapag 8 o 9 ang unang kamay ng alinman, walang bunot at agad ihahambing. Kung hindi, pumili ng isang dagdag na baraha o manatili. Isang bunot lang. Ang bangko ay bumubunot sa 0–5 at nananatili sa 6–9. Mas mataas na puntos ang panalo. Panalo: 1.95× balik kasama ang puhunan; tabla: 1×; talo: zero. Binibilog pababa sa 0.01. Nakatago ang baraha ng bangko hanggang matapos. Nananatili ang hindi tapos na laro kahit mag-reload. Tapusin ito bago magsimula ng bago. Hindi ito live-dealer table. Hindi naaangkop ang RTP ng Super Ace.'});
let lnOwner='',lnRows=[],lnRound=null,lnPending=null,lnBusy=false,lnLoading=false,lnError='',lnGeneration=0,lnCardStamp='';
function lnKey(){return (player?.id||'guest')+':'+gameMode}
function lnLocked(){lnReset();return lnBusy||Boolean(lnPending)||lnRound?.status==='ACTIVE'}
function lnSave(){try{if(player&&lnOwner===lnKey()){const key='ln-pending-'+lnOwner;lnPending?sessionStorage.setItem(key,JSON.stringify(lnPending)):sessionStorage.removeItem(key)}}catch{}}
function lnReset(){if(lnOwner===lnKey())return;lnOwner=lnKey();lnGeneration++;lnRows=[];lnRound=null;lnPending=null;lnError='';lnCardStamp='';try{const p=JSON.parse(sessionStorage.getItem('ln-pending-'+lnOwner)||'null');if(p?.owner===lnOwner)lnPending=p;}catch{}}
function lnCards(cards){return (cards||[null,null]).map((c,i)=>{const suit=c===null?0:Math.floor(c/13),rank=c===null?'?':['A','2','3','4','5','6','7','8','9','10','J','Q','K'][c%13],icon=['♠','♥','♣','♦'][suit];return '<div class="ln-card '+(c===null?'back':suit%2?'red':'black')+'" style="--card-delay:'+i*.1+'s" aria-label="'+(c===null?'Hidden card':rank+' '+icon)+'">'+(c===null?'<span>♛</span>':'<b>'+rank+'<small>'+icon+'</small></b><span>'+icon+'</span><b class="ln-corner">'+rank+'<small>'+icon+'</small></b>')+'</div>'}).join('')}
function lnUpdate(){lnReset();const row=lnRound,active=row?.status==='ACTIVE',locked=lnLocked();$('luckyNineView').dataset.active=String(Boolean(active));$('lnBalance').textContent=player?fmt(balance):'—';$('lnCurrency').textContent=gameMode==='LOBBY'?'Gold':'chips';$('lnStart').disabled=locked||lnLoading||Boolean(player&&!ready)||modeChanging||busy||pending||autoActive()||free>0;for(const id of ['lnHit','lnStand'])$(id).disabled=!active||lnBusy||Boolean(lnPending)||!ready;$('lnRetry').hidden=!lnPending||lnBusy;
 $('lnStatus').textContent=lnError||(!player?t('Sign in to place a bet'):active?t('Choose draw or stand'):t('Deal two cards'));$('lnSound').textContent=sound&&volume?'♫':'♫ ×';
 for(const [id,mode]of[['lnLobby','LOBBY'],['lnClub','CLUB']]){$(id).setAttribute('aria-pressed',String(gameMode===mode));$(id).disabled=locked||busy||modeChanging;}
 for(const el of document.querySelectorAll('#lnStake,#lnHalf,#lnDouble,[data-ln-chip]'))el.disabled=locked;
 const signature=JSON.stringify([row?.requestId,row?.playerCards,row?.bankerCards]);if(signature!==lnCardStamp){lnCardStamp=signature;$('lnPlayerCards').innerHTML=lnCards(row?.playerCards);$('lnBankerCards').innerHTML=lnCards(row?.bankerCards);}
 $('lnPlayerTotal').textContent=row?row.playerTotal:'—';$('lnBankerTotal').textContent=row?.bankerTotal??'?';$('lnNatural').hidden=row?.action!=='NATURAL';$('lnResult').classList.toggle('win',row?.status==='WIN');$('lnResult').textContent=!row?'':active?t('Choose draw or stand'):t(row.status==='WIN'?'YOU WIN':row.status==='TIE'?'Tie game':'No win')+' · '+t('Net')+' '+(row.payoutCents>row.betCents?'+':'')+money(row.payoutCents-row.betCents);
 $('lnLastBet').textContent=row?money(row.betCents):'—';$('lnReturn').textContent=row&& !active?money(row.payoutCents):'—';$('lnNet').textContent=row&&!active?money(row.payoutCents-row.betCents):'—';
 $('lnHistory').innerHTML=lnRows.length?lnRows.map(r=>'<div class="ar-history-row"><span>'+esc(stamp(r.createdAt))+'<small>'+t('Bet')+' '+money(r.betCents)+'</small></span><span>'+r.playerTotal+' : '+(r.bankerTotal??'?')+'<small>'+t(r.status==='ACTIVE'?'Choose draw or stand':r.status==='WIN'?'YOU WIN':r.status==='TIE'?'Tie game':'No win')+'</small></span><span>'+t('Total returned')+' '+(r.status==='ACTIVE'?'—':money(r.payoutCents))+'<small>'+t('Net')+' '+(r.status==='ACTIVE'?'—':money(r.payoutCents-r.betCents))+'</small></span></div>').join(''):'<p>'+t('No bets yet.')+'</p>';
}
async function lnLoad(){lnReset();if(lnBusy||lnLoading)return;lnLoading=true;const owner=lnOwner,generation=lnGeneration,mode=gameMode;try{const rows=player?await api('lucky-nine/rounds?mode='+mode):[];const w=player?await api('me?mode='+mode):null;if(owner!==lnKey()||generation!==lnGeneration)return;lnRows=rows;lnRound=rows.find(r=>r.status==='ACTIVE')||rows[0]||null;if(w){applyWallet(w);ready=canPlay(w);}lnError='';}catch(e){if(owner===lnKey()){lnError=errorText(e);if(e.status===401){ready=false;showLogin();}}}finally{lnLoading=false;lnUpdate();if(lnPending&&ready&&!lnBusy)void lnSend();}}
function lnCue(){if(document.hidden||!sound||!volume||activeView!=='luckyNineView')return;openAudio();[430,580].forEach((hz,i)=>tone(hz,.07,'triangle',i*.12))}
async function lnSend(){if(!lnPending||lnBusy||!ready)return;const owner=lnOwner,mode=gameMode,request=lnPending;lnBusy=true;busy=true;lnGeneration++;lnUpdate();try{if(request.kind==='start'&&request.body.expectedRevision===undefined){const w=await api('me?mode='+mode);if(owner!==lnKey())return;applyWallet(w);request.body.expectedRevision=revision;lnSave();}const row=await api('lucky-nine/'+request.kind+'?mode='+mode,'POST',request.body);if(owner!==lnKey())return;lnRound=row;lnRows=[row,...lnRows.filter(r=>r.requestId!==row.requestId)].slice(0,20);lnPending=null;lnSave();lnError='';lnCue();lnUpdate();if(row.status==='WIN')celebrateWin('luckyNineView',row.requestId,row.betCents,row.payoutCents);applyWallet(await api('me?mode='+mode));}catch(e){if(owner===lnKey()){if(e.code==='STALE_STATE'&&request.kind==='start'){delete request.body.expectedRevision;lnSave();}else if(e.status===401){ready=false;showLogin();}else if(e.status>=400&&e.status<500){lnPending=null;lnSave();}lnError=e.status?errorText(e):t('Connection lost. Retry uses the same request and cannot charge twice.');}}finally{lnBusy=false;busy=false;lnUpdate();}}
function lnMove(action){if(!player){showLogin();return}if(lnBusy||lnPending||!ready||lnRound?.status!=='ACTIVE')return;lnPending={owner:lnOwner,kind:'move',body:{requestId:lnRound.requestId,action}};lnSave();void lnSend();}
$('lnStart').onclick=()=>{if(!player){showLogin();return}if(lnLocked()||!ready)return;const amount=Number($('lnStake').value);if(!Number.isFinite(amount)||amount<5||amount>500){lnError=t('Choose a stake from 5 to 500.');lnUpdate();return;}lnPending={owner:lnOwner,kind:'start',body:{requestId:requestUuid(),betCents:Math.round(amount*100)}};lnSave();void lnSend();};$('lnHit').onclick=()=>lnMove('HIT');$('lnStand').onclick=()=>lnMove('STAND');$('lnRetry').onclick=()=>lnSend();$('lnHalf').onclick=()=>$('lnStake').value=Math.max(5,Math.floor(Number($('lnStake').value)*50)/100);$('lnDouble').onclick=()=>$('lnStake').value=Math.min(500,Number($('lnStake').value)*2);document.querySelectorAll('[data-ln-chip]').forEach(b=>b.onclick=()=>$('lnStake').value=b.dataset.lnChip);$('lnLobby').onclick=()=>switchMode('LOBBY');$('lnClub').onclick=()=>switchMode('CLUB');$('lnRulesButton').onclick=()=>$('lnRules').showModal();$('lnRulesClose').onclick=()=>$('lnRules').close();$('lnSound').onclick=()=>{$('sound').click();lnUpdate();};
const lnOldLanguage=setLanguage;setLanguage=value=>{lnOldLanguage(value);lnUpdate();};const lnOldHelp=$('help').onclick;$('help').onclick=()=>activeView==='luckyNineView'?$('lnRules').showModal():lnOldHelp();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&activeView==='luckyNineView')void lnLoad();});localize();
