'use strict';
Object.assign(english,{minesRules:'Choose a stake of 5–500 and 1, 3, 5 or 10 mines on a 5×5 board. Mine locations are selected uniformly and stored on the server before the first tile opens. Open safe tiles to increase the multiplier. After at least one safe tile, you may cash out for stake × multiplier, rounded down to 0.01. Opening a mine loses the entire stake. Opening every safe tile automatically cashes out. You cannot cancel a started round or change its mine count. An unfinished round survives reload and server restart. The current multiplier and the multiplier for the next safe tile are shown on the board. Super Ace RTP settings do not apply.'});
Object.assign(filipino,{'Open a safe tile':'Magbukas ng ligtas na tile','Find gems. Choose when to collect.':'Humanap ng hiyas. Piliin kung kailan kukunin.','Safe tiles':'Ligtas na tile','Mines':'Mga mina','Current multiplier':'Kasalukuyang multiplier','Next safe tile':'Susunod na ligtas na tile','Number of mines':'Bilang ng mina','Start round':'Simulan ang laro','Cash out value':'Halagang makukuha','Open a safe tile before cashing out. Hitting a mine loses the stake.':'Magbukas muna ng ligtas na tile bago mag-cash out. Mawawala ang taya kapag may mina.','Choose a covered tile':'Pumili ng saradong tile','Mine hit':'May mina','Collect your gems':'Kunin ang mga hiyas',minesRules:'Pumili ng taya na 5–500 at 1, 3, 5 o 10 mina sa 5×5 na board. Pantay na pinipili at iniimbak ng server ang lokasyon ng mga mina bago magbukas ng tile. Tumataas ang multiplier sa bawat ligtas na tile. Pagkatapos ng kahit isang ligtas na tile, maaaring mag-cash out ng taya × multiplier, binibilog pababa sa 0.01. Mawawala ang buong taya kapag may mina. Awtomatikong cash out kapag nabuksan ang lahat ng ligtas na tile. Hindi maaaring kanselahin o palitan ang bilang ng mina. Nananatili ang laro matapos mag-reload o mag-restart ang server. Makikita sa board ang kasalukuyang multiplier at ang multiplier ng susunod na ligtas na tile. Hindi naaangkop ang RTP ng Super Ace.'});
let mnOwner='',mnRows=[],mnRound=null,mnPending=null,mnBusy=false,mnLoading=false,mnError='',mnGeneration=0;
function mnKey(){return (player?.id||'guest')+':'+gameMode}
function mnLocked(){mnReset();return mnBusy||Boolean(mnPending)||mnRound?.status==='ACTIVE'}
function mnSave(){try{if(player&&mnOwner===mnKey()){const key='mn-pending-'+mnOwner;mnPending?sessionStorage.setItem(key,JSON.stringify(mnPending)):sessionStorage.removeItem(key)}}catch{}}
function mnReset(){if(mnOwner===mnKey())return;mnOwner=mnKey();mnGeneration++;mnRows=[];mnRound=null;mnPending=null;mnError='';try{const p=JSON.parse(sessionStorage.getItem('mn-pending-'+mnOwner)||'null');if(p?.owner===mnOwner)mnPending=p;}catch{}}
for(let i=0;i<25;i++){const button=document.createElement('button');button.type='button';button.className='mn-tile covered';button.dataset.tile=i;button.setAttribute('aria-label','Tile '+(i+1));button.innerHTML='<span class="mn-mark">◆</span>';button.onclick=()=>mnMove(i);$('mnGrid').append(button);}
function mnUpdate(){mnReset();const row=mnRound,active=row?.status==='ACTIVE',count=row?.mineCount||Number($('mnCount').value),opened=row?.opened||[],mines=row?.mines||[];
 $('mnBalance').textContent=player?fmt(balance):'—';$('mnCurrency').textContent=gameMode==='LOBBY'?'Gold':'chips';$('mnMineTotal').textContent=count;$('mnSafe').textContent=25-count-opened.filter(i=>!mines.includes(i)).length;$('mnMultiplier').textContent=((row?.multiplierBps||100)/100).toFixed(2)+'×';$('mnNext').textContent=active?(row.nextMultiplierBps/100).toFixed(2)+'×':'—';$('mnBet').textContent=row?money(row.betCents):'—';$('mnValue').textContent=active&&opened.length?money(Math.floor(row.betCents*row.multiplierBps/100)):row&&row.status!=='ACTIVE'?money(row.payoutCents):'—';
 $('minesView').dataset.active=String(Boolean(active));$('mnCash').textContent=t(active&&!opened.length?'Open a safe tile':'Cash out')+(active&&opened.length?' · '+money(Math.floor(row.betCents*row.multiplierBps/100)):'');
 $('mnStart').disabled=mnLocked()||mnLoading||Boolean(player&&!ready)||modeChanging||busy||pending||autoActive()||free>0;$('mnCash').disabled=!active||!opened.length||mnBusy||Boolean(mnPending)||!ready;$('mnRetry').hidden=!mnPending||mnBusy;$('mnStatus').textContent=mnError||(!player?t('Sign in to place a bet'):active?t('Choose a covered tile'):t('Start round'));$('mnSound').textContent=sound&&volume?'♫':'♫ ×';
 for(const [id,mode]of[['mnLobby','LOBBY'],['mnClub','CLUB']]){$(id).setAttribute('aria-pressed',String(gameMode===mode));$(id).disabled=mnLocked()||busy||modeChanging;}
 for(const el of document.querySelectorAll('#mnStake,#mnCount,#mnHalf,#mnDouble,[data-mn-chip]'))el.disabled=mnLocked();
 for(const el of document.querySelectorAll('[data-tile]')){const i=Number(el.dataset.tile),isMine=mines.includes(i),isOpen=opened.includes(i),state=isMine?'mine':isOpen?'gem':'covered';el.disabled=!active||isOpen||mnBusy||Boolean(mnPending)||!ready;el.className='mn-tile '+state+(isMine&&isOpen?' hit-mine':'');el.setAttribute('aria-label',(language==='fil'?'Tile ':'Tile ')+(i+1)+' · '+(isMine?t('Mines'):isOpen?t('Safe tiles'):'?'));if(el.dataset.state!==state){el.dataset.state=state;el.innerHTML=state==='gem'?'<span class="mn-jewel" aria-hidden="true"></span>':state==='covered'?'<span class="mn-mark" aria-hidden="true">◆</span>':'';}}
 $('mnResult').classList.toggle('win',row?.status==='CASHED_OUT');$('mnResult').textContent=!row?'':active?t('Collect your gems'):row.status==='LOST'?t('Mine hit')+' · '+t('Net')+' −'+money(row.betCents):t('Cashed out')+' · '+money(row.payoutCents);
 $('mnHistory').innerHTML=mnRows.length?mnRows.map(r=>'<div class="ar-history-row"><span>'+esc(stamp(r.createdAt))+'<small>'+r.mineCount+' '+t('Mines')+' · '+t('Bet')+' '+money(r.betCents)+'</small></span><span>'+t(r.status==='ACTIVE'?'Choose a covered tile':r.status==='LOST'?'Mine hit':'Cashed out')+'<small>'+(r.multiplierBps/100).toFixed(2)+'×</small></span><span>'+t('Total returned')+' '+money(r.payoutCents)+'<small>'+t('Net')+' '+(r.status==='ACTIVE'?'—':money(r.payoutCents-r.betCents))+'</small></span></div>').join(''):'<p>'+t('No bets yet.')+'</p>';
}
async function mnLoad(){mnReset();if(mnBusy||mnLoading)return;mnLoading=true;const owner=mnOwner,generation=mnGeneration,mode=gameMode;try{const rows=player?await api('mines/rounds?mode='+mode):[];const w=player?await api('me?mode='+mode):null;if(owner!==mnKey()||generation!==mnGeneration)return;mnRows=rows;mnRound=rows.find(r=>r.status==='ACTIVE')||rows[0]||null;if(w){applyWallet(w);ready=canPlay(w);}mnError='';}catch(e){if(owner===mnKey()){mnError=errorText(e);if(e.status===401){ready=false;showLogin();}}}finally{mnLoading=false;mnUpdate();if(mnPending&&ready&&!mnBusy)void mnSend();}}
function mnCue(status){if(document.hidden||!sound||!volume)return;openAudio();const notes=status==='LOST'?[180,130]:status==='CASHED_OUT'?[523,659,784]:[700];notes.forEach((n,i)=>tone(n,.12,'triangle',i*.09))}
async function mnSend(){if(!mnPending||mnBusy||!ready)return;const owner=mnOwner,mode=gameMode,request=mnPending;mnBusy=true;busy=true;mnGeneration++;mnUpdate();try{if(request.kind==='start'&&request.body.expectedRevision===undefined){const w=await api('me?mode='+mode);if(owner!==mnKey())return;applyWallet(w);request.body.expectedRevision=revision;mnSave();}const row=await api('mines/'+request.kind+'?mode='+mode,'POST',request.body);if(owner!==mnKey())return;mnRound=row;mnRows=[row,...mnRows.filter(r=>r.requestId!==row.requestId)].slice(0,20);mnPending=null;mnSave();mnError='';mnCue(row.status);if(row.status==='CASHED_OUT')celebrateWin('minesView',row.requestId,row.betCents,row.payoutCents);applyWallet(await api('me?mode='+mode));}catch(e){if(owner===mnKey()){if(e.code==='STALE_STATE'&&request.kind==='start'){delete request.body.expectedRevision;mnSave();}else if(e.status===401){ready=false;showLogin();}else if(e.status>=400&&e.status<500){mnPending=null;mnSave();}mnError=e.status?errorText(e):t('Connection lost. Retry uses the same request and cannot charge twice.');}}finally{mnBusy=false;busy=false;mnUpdate();}}
function mnMove(tile){if(!player){showLogin();return}if(mnBusy||mnPending||!ready||mnRound?.status!=='ACTIVE')return;mnPending={owner:mnOwner,kind:'move',body:{requestId:mnRound.requestId,tile}};mnSave();void mnSend();}
$('mnStart').onclick=()=>{if(!player){showLogin();return}if(mnLocked()||!ready)return;const amount=Number($('mnStake').value);if(!Number.isFinite(amount)||amount<5||amount>500){mnError=t('Choose a stake from 5 to 500.');mnUpdate();return;}mnPending={owner:mnOwner,kind:'start',body:{requestId:requestUuid(),betCents:Math.round(amount*100),mineCount:Number($('mnCount').value)}};mnSave();void mnSend();};$('mnCash').onclick=()=>mnMove(null);$('mnRetry').onclick=()=>mnSend();$('mnCount').onchange=mnUpdate;$('mnHalf').onclick=()=>$('mnStake').value=Math.max(5,Math.floor(Number($('mnStake').value)*50)/100);$('mnDouble').onclick=()=>$('mnStake').value=Math.min(500,Number($('mnStake').value)*2);document.querySelectorAll('[data-mn-chip]').forEach(b=>b.onclick=()=>$('mnStake').value=b.dataset.mnChip);$('mnLobby').onclick=()=>switchMode('LOBBY');$('mnClub').onclick=()=>switchMode('CLUB');$('mnRulesButton').onclick=()=>$('mnRules').showModal();$('mnRulesClose').onclick=()=>$('mnRules').close();$('mnSound').onclick=()=>{$('sound').click();mnUpdate();};
const mnOldLanguage=setLanguage;setLanguage=value=>{mnOldLanguage(value);mnUpdate();};const mnOldHelp=$('help').onclick;$('help').onclick=()=>activeView==='minesView'?$('mnRules').showModal():mnOldHelp();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&activeView==='minesView')void mnLoad();});localize();
