'use strict';
const views=['gameView','dragonTigerView','colorGameView','crashView','arcadeView','minesView','luckyNineView','rankingView','chipsView','reportsView','accountsView','settlementsView','profileView'];let activeView='gameView',accountRows=[],reportData=null,chipPage=0,settingsData=null,decision=null,toastTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=c=>fmt(c/100),stamp=ms=>ms?new Intl.DateTimeFormat(language==='fil'?'fil-PH':'en-PH',{dateStyle:'medium',timeStyle:'short',timeZone:reportTimezone}).format(new Date(ms)):'—';let reportTimezone='Asia/Manila';
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500)}
$('signInNav').onclick=()=>showLogin();
function showLogin(){if(!$('loginDialog').open)$('loginDialog').showModal()}
function applyRole(){document.querySelectorAll('[data-admin]').forEach(el=>el.hidden=!player||player.role==='PLAYER');document.querySelectorAll('[data-creator]').forEach(el=>el.hidden=player?.role!=='CREATOR');document.querySelectorAll('[data-player-nav]').forEach(el=>el.hidden=!canPlay());document.querySelectorAll('[data-player]').forEach(el=>el.hidden=!canPlay());document.querySelector('[data-view="gameView"]').hidden=!!player&&!canPlay();$('profileInfo').textContent=player?player.displayName+' · '+player.username+' · '+player.role.replaceAll('_',' ')+' · ID '+player.publicCode+' · '+money(player.balanceCents)+' chips':'';document.querySelectorAll('[data-guest]').forEach(el=>el.hidden=!!player);if(player&&!canPlay()&&activeView==='gameView')void showView('reportsView')}
function table(target,headers,rows){$(target).innerHTML=rows.length?'<table><thead><tr>'+headers.map(h=>'<th>'+esc(t(h))+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'<p class="empty">'+esc(t('No records for this period.'))+'</p>'}
function range(p){reportTimezone=p.timezone;return p.start+' → '+p.endExclusive+' '+t('(end excluded)')+' · '+p.timezone}
function netCell(n){return '<span class="number '+(n>0?'positive':n<0?'negative':'')+'">'+(n>0?'+':'')+money(n)+'</span>'}
function labelState(s){return t(({PENDING:'Pending',APPROVED:'Approved',REJECTED:'Rejected',DRAFT:'Draft',PAID:'Paid',DEPOSIT:'Deposit',WITHDRAWAL:'Withdrawal',WELCOME:'Welcome'})[s]||s)}
async function task(fn){try{await fn()}catch(e){toast(errorText(e));if(e.status===401){ready=false;player=null;balance=0;free=0;updateConnectionControl();applyRole();showLogin()}}}
async function showView(id){if(!views.includes(id))return;if(typeof lnLocked==='function'&&lnLocked()&&id!=='luckyNineView'&&id!==activeView){toast(t('Finish or recover the current round first.'));return;}if(typeof mnLocked==='function'&&mnLocked()&&id!=='minesView'&&id!==activeView){toast(t('Finish or recover the current round first.'));return;}if(typeof arLocked==='function'&&arLocked()&&id!=='arcadeView'&&id!==activeView){toast(t('Finish or recover the current round first.'));return;}if(typeof crLocked==='function'&&crLocked()&&id!=='crashView'&&id!==activeView){toast(t('Finish or recover the current round first.'));return;}if(typeof dtLocked==='function'&&dtLocked()&&id!=='dragonTigerView'&&id!==activeView){toast(t('Finish or recover the current round first.'));return;}if(typeof cgLocked==='function'&&cgLocked()&&id!=='colorGameView'&&id!==activeView){toast(t('Finish or recover the current round first.'));return;}if(['dragonTigerView','colorGameView','crashView','arcadeView','minesView','luckyNineView'].includes(id)&&(busy||pending||autoActive()||free>0)){toast(t('Finish free spins and stop autoplay first.'));return;}if(!player&&!['gameView','dragonTigerView','colorGameView','crashView','arcadeView','minesView','luckyNineView'].includes(id)){showLogin();return}if(player?.role==='PLAYER'&&['accountsView','settlementsView'].includes(id))return;activeView=id;views.forEach(v=>$(v).hidden=v!==id);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));await task(async()=>{if(id==='dragonTigerView')await dtLoad();if(id==='colorGameView')await cgLoad();if(id==='arcadeView')await arLoad();if(id==='minesView')await mnLoad();if(id==='luckyNineView')await lnLoad();if(id==='crashView'){await crLoad();crAnimate();}if(id==='rankingView')await loadRanking();if(id==='reportsView')await loadReport();if(id==='chipsView')await loadChips();if(id==='accountsView')await loadAccounts();if(id==='settlementsView')await loadSettlements();if(id==='gameView')await syncAuto(false)})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function setLanguage(value){language=value;localize();update();soundUI();if(player)void showView(activeView)}$('language').onchange=e=>setLanguage(e.target.value);$('loginLanguage').onclick=()=>setLanguage(language==='en'?'fil':'en');
 $('previewTheme').onclick=()=>{$('loginDialog').close();$('status').textContent=t('Choose a theme, then sign in to play.');updateConnectionControl();document.querySelector('[data-view="gameView"]').hidden=false};
$('loginForm').onsubmit=e=>{e.preventDefault();const form=e.target,b=form.querySelector('button');b.disabled=true;$('loginError').textContent='';const data=Object.fromEntries(new FormData(form));api('login','POST',data).then(async me=>{applyWallet(me);form.reset();await connect();await showView(canPlay(me)?'gameView':'reportsView')}).catch(error=>$('loginError').textContent=errorText(error)).finally(()=>b.disabled=false)};
$('logout').onclick=()=>task(async()=>{await api('logout','POST');ready=false;player=null;balance=0;free=0;revision=0;last=0;autoRun=null;seenRound=0;savePending(null);updateConnectionControl();applyRole();views.forEach(v=>$(v).hidden=v!=='gameView');activeView='gameView';update();showLogin()});
$('passwordForm').onsubmit=e=>{e.preventDefault();submit(e.target,async data=>{await api('password','POST',data);ready=false;player=null;autoRun=null;savePending(null);updateConnectionControl();update();toast(t('Password changed. Please sign in again.'));showLogin()})};
async function submit(form,fn){const b=form.querySelector('button[type="submit"]')||form.querySelector('button');b.disabled=true;try{await fn(Object.fromEntries(new FormData(form)));form.reset()}catch(e){toast(errorText(e));}finally{b.disabled=false}}
async function loadRanking(){const data=await api('ranking?period='+$('rankingPeriod').value);$('rankingRange').textContent=range(data.period);table('rankingTable',['Ranking','Player','Wagered'],data.players.map(r=>['<span class="rank-medal">'+r.rank+'</span>',esc(r.displayName),money(r.wagerCents)]))}$('rankingPeriod').onchange=()=>task(loadRanking);
async function loadReport(){reportData=await api('reports?period='+$('reportPeriod').value+'&date='+$('reportDate').value);$('reportRange').textContent=range(reportData.period);$('reportTotals').innerHTML=[['Wagered',reportData.wagerCents],['Payout',reportData.payoutCents],['Player net',reportData.netCents]].map(([k,v])=>'<div class="metric"><small>'+esc(t(k))+'</small><strong>'+money(v)+'</strong></div>').join('');table('reportTable',['Player','Agent','Wagered','Payout','Player net','Paid rounds','FREE SPINS'],reportData.players.map(r=>[esc(r.displayName),esc(r.agentName),money(r.wagerCents),money(r.payoutCents),netCell(r.netCents),r.paidSpins,r.freeSpins]))}
$('reportLoad').onclick=()=>task(loadReport);$('reportPeriod').onchange=()=>task(loadReport);
$('reportExport').onclick=()=>{if(!reportData)return;const safe=v=>'"'+(typeof v==='string'?v.replace(/^[=+@\-]/,"'$&"):String(v)).replaceAll('"','""')+'"';const rows=[['Player','Agent','Wagered','Payout','Player net','Paid rounds','FREE SPINS'].map(t),...reportData.players.map(r=>[r.displayName,r.agentName,r.wagerCents/100,r.payoutCents/100,r.netCents/100,r.paidSpins,r.freeSpins])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='win-loss-'+reportData.period.type+'-'+reportData.period.start+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
async function loadChips(){const rows=await api('chips?page='+chipPage);$('chipsPage').textContent=chipPage+1;$('chipsPrev').disabled=chipPage===0;$('chipsNext').disabled=rows.length<100;table('chipTable',['Date','Player','Type','Chips','Status','Reference / note'],rows.map(r=>[esc(stamp(r.createdAt)),esc(r.displayName),esc(labelState(r.kind)),money(r.amountCents),'<span class="tag">'+esc(labelState(r.status))+'</span>',esc(r.reference)]));}
$('chipsLoad').onclick=()=>task(loadChips);$('chipsPrev').onclick=()=>{if(chipPage>0)chipPage--;task(loadChips)};$('chipsNext').onclick=()=>{chipPage++;task(loadChips)};
const roles=['CREATOR','SUPER_AGENT','AGENT','PLAYER'];
function parentOptions(){const role=$('newRole').value,ordinal=roles.indexOf(role);$('newParent').innerHTML=accountRows.filter(r=>roles.indexOf(r.role)===ordinal-1).map(r=>'<option value="'+r.id+'">'+esc(r.displayName)+' ('+esc(r.username)+')</option>').join('')}
async function loadAccounts(){accountRows=await api('accounts');const level=roles.indexOf(player.role);$('newRole').innerHTML=roles.filter((r,i)=>i>level).map(r=>'<option value="'+r+'">'+r.replaceAll('_',' ')+'</option>').join('');parentOptions();table('accountsTable',['Username','Display name','Role','Parent account'],accountRows.map(r=>[esc(r.username),esc(r.displayName),'<span class="tag">'+r.role.replaceAll('_',' ')+'</span>',esc(accountRows.find(p=>p.id===r.parentId)?.displayName||'—')]))}
$('newRole').onchange=parentOptions;$('accountsLoad').onclick=()=>task(loadAccounts);$('accountForm').onsubmit=e=>{e.preventDefault();submit(e.target,async data=>{await api('accounts','POST',data);toast(t('Account created.'));await loadAccounts()})};
async function loadSettlements(){settingsData=await api('settings');$('commissionRate').value=settingsData.commissionBps/100;$('commissionMode').value=settingsData.commissionMode;const rows=await api('settlements?date='+$('settlementDate').value);table('settlementTable',['Agent','Week','Wagered','Payout','Loss base','Rate','Commission','Status','Actions'],rows.map((r,i)=>[esc(r.agentName),r.weekStart,money(r.wagerCents),money(r.payoutCents),money(r.lossBaseCents),fmt(r.rateBps/100)+'%',money(r.commissionCents),'<span class="tag">'+esc(labelState(r.status))+'</span>','<button data-detail="'+i+'">'+esc(t('Details'))+'</button> '+(player.role==='CREATOR'&&r.status!=='PAID'?'<button data-settle="'+i+'">'+esc(t(r.status==='DRAFT'?'Approve':'Mark paid'))+'</button>':'')]));if(!rows.length)$('settlementTable').innerHTML='<p class="empty">'+esc(t('No closed report yet. Choose a previous week.'))+'</p>';
 $('settlementTable').querySelectorAll('[data-settle]').forEach(b=>b.onclick=()=>{const r=rows[+b.dataset.settle];decision=r;$('decisionTitle').textContent=t(r.status==='DRAFT'?'Approve':'Mark paid')+' · '+r.agentName+' · '+r.weekStart;$('decisionRate').value=r.rateBps/100;$('decisionRate').disabled=r.status!=='DRAFT';$('decisionNote').value=r.note||'';$('decisionDialog').showModal()});
 $('settlementTable').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{const r=rows[+b.dataset.detail];const old=document.getElementById('settlementDetail');if(old)old.remove();const box=document.createElement('div');box.id='settlementDetail';box.className='panel';const h=document.createElement('h2');h.textContent=r.agentName+' · '+r.weekStart;const detail=document.createElement('div');detail.id='settlementDetailTable';detail.className='table-wrap';box.append(h,detail);$('settlementsView').append(box);table('settlementDetailTable',['Player','Wagered','Payout','Player net'],r.players.map(p=>[esc(p.displayName),money(p.wagerCents),money(p.payoutCents),netCell(p.netCents)]));box.scrollIntoView({behavior:'smooth',block:'nearest'})})}
$('settlementsLoad').onclick=()=>task(loadSettlements);$('decisionCancel').onclick=()=>$('decisionDialog').close();$('decisionForm').onsubmit=e=>{e.preventDefault();const b=e.target.querySelector('.primary');b.disabled=true;task(async()=>{await api('settlements/decide','POST',{agentId:decision.agentId,weekStart:decision.weekStart,action:decision.status==='DRAFT'?'APPROVE':'PAID',rateBps:Math.round(Number($('decisionRate').value)*100),revision:decision.revision,note:$('decisionNote').value});$('decisionDialog').close();await loadSettlements()}).finally(()=>b.disabled=false)};
$('settingsForm').onsubmit=e=>{e.preventDefault();task(async()=>{await api('settings','POST',{commissionBps:Math.round(Number($('commissionRate').value)*100),commissionMode:$('commissionMode').value,revision:settingsData.revision});toast(t('Saved.'));await loadSettlements()})};
function localDateInput(date){return new Intl.DateTimeFormat('en-CA',{timeZone:reportTimezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
$('reportDate').value=localDateInput(new Date());$('settlementDate').value=localDateInput(new Date(Date.now()-7*86400000));
void connect().then(()=>poll());
