package vn.emerald.ace;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.http.MediaType;
import jakarta.servlet.http.Cookie;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest(properties={"spring.datasource.url=${TEST_DB_URL:jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1}","spring.datasource.username=${TEST_DB_USER:sa}","spring.datasource.password=${TEST_DB_PASSWORD:}","ace.creator-password=test-only-creator-password","ace.spin-cooldown-ms=0","ace.jobs-enabled=false","ace.jwt-secret=test-only-secret-at-least-32-characters"})
@AutoConfigureMockMvc
class ServerTest {
 @Autowired GameService game;@Autowired Accounts accounts;@Autowired AutoService auto;@Autowired Reports reports;@Autowired Chips chips;@Autowired JdbcTemplate db;@Autowired MockMvc mvc;
 String id(){return UUID.randomUUID().toString();}
 Accounts.User creator(){return accounts.login("creator","test-only-creator-password").auth().user();}
 Accounts.User create(Accounts.User actor,Accounts.User parent,Accounts.Role role){String name="u"+id().replace("-","");return accounts.create(actor,name,name,"test-only-user-password",role,parent.id());}
 record Tree(Accounts.User root,Accounts.User sa,Accounts.User agent,Accounts.User player){}
 Tree tree(){var root=creator();var sa=create(root,root,Accounts.Role.SUPER_AGENT);var agent=create(root,sa,Accounts.Role.AGENT);var player=create(root,agent,Accounts.Role.PLAYER);db.update("UPDATE wallets SET balance=1000000 WHERE player_id=?",player.id());return new Tree(root,sa,agent,player);}
 @Test void roleHierarchyAndScope(){var a=tree();var b=tree();assertFalse(accounts.inScope(a.agent(),b.player()));assertTrue(accounts.inScope(a.sa(),a.player()));assertEquals("INVALID_PARENT",assertThrows(GameService.ApiError.class,()->create(a.agent(),b.agent(),Accounts.Role.PLAYER)).code);assertEquals("FORBIDDEN",assertThrows(GameService.ApiError.class,()->create(a.player(),a.agent(),Accounts.Role.PLAYER)).code);assertEquals("INVALID_PARENT",assertThrows(GameService.ApiError.class,()->create(a.root(),a.root(),Accounts.Role.PLAYER)).code);assertTrue(accounts.list(a.agent()).stream().allMatch(u->u.id().equals(a.agent().id())||u.id().equals(a.player().id())));}
 @Test void duplicateSpinIsExactlyOnceEvenConcurrent()throws Exception{var t=tree();String request=id();try(var pool=Executors.newFixedThreadPool(2)){Callable<GameService.SpinResult> task=()->game.spin(t.player(),request,2000,0);var a=pool.submit(task);var b=pool.submit(task);var ra=a.get(15,TimeUnit.SECONDS);var rb=b.get(15,TimeUnit.SECONDS);assertEquals(ra.balanceCents(),rb.balanceCents());assertEquals(ra.revision(),rb.revision());assertEquals(1,game.wallet(t.player().id(),false).revision());assertEquals(1000000-2000+ra.outcome().winCents(),ra.balanceCents());assertEquals(1,db.queryForObject("SELECT COUNT(*) FROM round_ledger WHERE player_id=?",Integer.class,t.player().id()));}}
 @Test void staleStateAndReusedPayload(){var t=tree();String request=id();game.spin(t.player(),request,2000,0);assertEquals("STALE_STATE",assertThrows(GameService.ApiError.class,()->game.spin(t.player(),id(),2000,0)).code);assertEquals("REQUEST_REUSED",assertThrows(GameService.ApiError.class,()->game.spin(t.player(),request,5000,0)).code);}
 @Test void freeSpinLocksBetAndDoesNotDebit(){var t=tree();db.update("UPDATE wallets SET balance=0,free_spins=2,locked_bet=2000 WHERE player_id=?",t.player().id());assertEquals("BET_LOCKED",assertThrows(GameService.ApiError.class,()->game.spin(t.player(),id(),5000,0)).code);var r=game.spin(t.player(),id(),2000,0);assertTrue(r.freeSpin());assertEquals(r.outcome().winCents(),r.balanceCents());assertEquals(1+r.outcome().freeAward(),r.freeSpins());assertEquals(0,db.queryForObject("SELECT wager_cents FROM round_ledger WHERE player_id=?",Long.class,t.player().id()));}
 @Test void failedSpinLeavesWalletUnchanged(){var t=tree();db.update("UPDATE wallets SET balance=0 WHERE player_id=?",t.player().id());assertEquals("INSUFFICIENT_FUNDS",assertThrows(GameService.ApiError.class,()->game.spin(t.player(),id(),2000,0)).code);assertEquals(0,game.wallet(t.player().id(),false).revision());}
 @Test void autoCountersAreSeparateAndFinalBonusDrains(){var t=tree();String pid=t.player().id();db.update("UPDATE wallets SET free_spins=2,locked_bet=2000 WHERE player_id=?",pid);var job=auto.start(t.player(),id(),10,2000,0,true);auto.process(pid);assertEquals(0,auto.job(pid).completed());assertEquals(1,auto.job(pid).freeCompleted());assertEquals("AUTO_ACTIVE",assertThrows(GameService.ApiError.class,()->game.spin(t.player(),id(),2000,1)).code);
  db.update("UPDATE wallets SET free_spins=0,locked_bet=0 WHERE player_id=?",pid);db.update("UPDATE auto_jobs SET next_at=0 WHERE player_id=?",pid);auto.process(pid);assertEquals(1,auto.job(pid).completed());assertEquals(1,auto.job(pid).freeCompleted());
  db.update("UPDATE auto_jobs SET paid_done=10,next_at=0 WHERE player_id=?",pid);db.update("UPDATE wallets SET free_spins=1,locked_bet=2000 WHERE player_id=?",pid);auto.process(pid);assertEquals(10,auto.job(pid).completed());assertEquals(2,auto.job(pid).freeCompleted());assertEquals(game.wallet(pid,false).freeSpins()>0,auto.job(pid).active());auto.stop(t.player(),job.runId());assertFalse(auto.job(pid).active());long rev=game.wallet(pid,false).revision();auto.process(pid);assertEquals(rev,game.wallet(pid,false).revision());}
 @Test void concurrentAutoWorkersCannotDoubleSpin()throws Exception{var t=tree();auto.start(t.player(),id(),10,2000,0,true);try(var pool=Executors.newFixedThreadPool(4)){var jobs=new ArrayList<Future<?>>();for(int i=0;i<4;i++)jobs.add(pool.submit(()->auto.process(t.player().id())));for(var f:jobs)f.get(15,TimeUnit.SECONDS);}assertEquals(1,auto.job(t.player().id()).completed());assertEquals(1,game.wallet(t.player().id(),false).revision());}
 @Test void transfersReserveRefundAndApproveExactlyOnce()throws Exception{var t=tree();String request=id();var w=chips.request(t.player(),request,"WITHDRAWAL",12345,"test");assertEquals(987655,game.wallet(t.player().id(),false).balanceCents());assertEquals(w.id(),chips.request(t.player(),request,"WITHDRAWAL",12345,"test").id());assertEquals(987655,game.wallet(t.player().id(),false).balanceCents());chips.decide(t.agent(),w.id(),false);chips.decide(t.agent(),w.id(),false);assertEquals(1000000,game.wallet(t.player().id(),false).balanceCents());db.update("UPDATE wallets SET balance=100000 WHERE player_id=?",t.agent().id());var d=chips.request(t.player(),id(),"DEPOSIT",54321,"test");assertEquals(1000000,game.wallet(t.player().id(),false).balanceCents());try(var pool=Executors.newFixedThreadPool(2)){var a=pool.submit(()->chips.decide(t.agent(),d.id(),true));var b=pool.submit(()->chips.decide(t.agent(),d.id(),true));a.get(15,TimeUnit.SECONDS);b.get(15,TimeUnit.SECONDS);}assertEquals(1054321,game.wallet(t.player().id(),false).balanceCents());assertEquals(0,reports.report(t.player(),"week",reports.today()).netCents());var outsider=tree();assertEquals("FORBIDDEN",assertThrows(GameService.ApiError.class,()->chips.decide(outsider.agent(),d.id(),true)).code);}
 void ledger(Tree t,Accounts.User p,long time,long bet,long payout,boolean free,long rev){db.update("INSERT INTO round_ledger(player_id,request_id,agent_id,super_agent_id,nominal_bet,wager_cents,payout_cents,is_free,wallet_revision,response_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,'{}',?)",p.id(),id(),t.agent().id(),t.sa().id(),2000,bet,payout,free,rev,time);}
 @Test void weeklyTimezoneBoundariesFreePayoutsAndIsolation(){var t=tree();var p=reports.period("week",LocalDate.of(2026,8,5));assertEquals("2026-08-03",p.start());assertEquals(Instant.parse("2026-08-02T17:00:00Z").toEpochMilli(),p.from());ledger(t,t.player(),p.from()-1,2000,0,false,1);ledger(t,t.player(),p.from(),2000,100,false,2);ledger(t,t.player(),p.to()-1,0,500,true,3);ledger(t,t.player(),p.to(),2000,10000,false,4);var result=reports.report(t.agent(),"week",LocalDate.of(2026,8,5));assertEquals(2000,result.wagerCents());assertEquals(600,result.payoutCents());assertEquals(-1400,result.netCents());assertEquals(1,result.players().getFirst().freeSpins());assertEquals(0,reports.report(tree().agent(),"week",LocalDate.of(2026,8,5)).players().size());var ranks=(List<Reports.Rank>)reports.ranking("week",LocalDate.of(2026,8,5)).get("players");assertEquals(2000,ranks.stream().filter(r->r.displayName().equals(t.player().displayName())).findFirst().orElseThrow().wagerCents());}
 @Test void commissionModesAndSnapshotApproval(){var t=tree();var winner=create(t.root(),t.agent(),Accounts.Role.PLAYER);LocalDate date=LocalDate.of(2026,7,6);var p=reports.period("week",date);db.update("UPDATE accounts SET created_at=? WHERE id=?",p.from()-1,t.agent().id());ledger(t,t.player(),p.from(),100000,20000,false,1);ledger(t,winner,p.from(),100000,130000,false,1);var settings=reports.settings();reports.settings(t.root(),3000,"POSITIVE_PLAYER",settings.revision());reports.closeWeek(date);var s=reports.settlements(t.agent(),date).getFirst();assertEquals(80000,s.lossBaseCents());assertEquals(24000,s.commissionCents());assertEquals(50000,Reports.lossBase(s.players(),"NET_AGENT"));assertEquals(15000,Reports.commission(50000,3000));
  reports.decide(t.root(),t.agent().id(),date,"APPROVE",2500,s.revision(),"reviewed");var approved=reports.settlements(t.agent(),date).getFirst();assertEquals(20000,approved.commissionCents());reports.decide(t.root(),t.agent().id(),date,"PAID",2500,approved.revision(),"record only");assertEquals("PAID",reports.settlements(t.agent(),date).getFirst().status());reports.closeWeek(date);assertEquals(1,reports.settlements(t.agent(),date).size());assertEquals(1000000,game.wallet(t.player().id(),false).balanceCents());assertThrows(GameService.ApiError.class,()->reports.decide(t.agent(),t.agent().id(),date,"PAID",2500,2,""));}
 @Test void loginLockoutAndPasswordRevokesSessions(){var t=tree();for(int i=0;i<5;i++)assertEquals("BAD_LOGIN",assertThrows(GameService.ApiError.class,()->accounts.login(t.player().username(),"incorrect")).code);assertEquals("LOGIN_LOCKED",assertThrows(GameService.ApiError.class,()->accounts.login(t.player().username(),"test-only-user-password")).code);db.update("UPDATE accounts SET locked_until=0 WHERE id=?",t.player().id());var login=accounts.login(t.player().username(),"test-only-user-password");accounts.password(login.auth(),"test-only-user-password","another-test-password");assertThrows(GameService.ApiError.class,()->accounts.authenticate(login.token()));assertNotNull(accounts.login(t.player().username(),"another-test-password"));}
 @Test void apiRejectsOriginCsrfAndForgedFields()throws Exception{mvc.perform(post("/api/login")).andExpect(status().isForbidden());mvc.perform(post("/api/login").header("X-Game-Client","web").header("Origin","https://attacker.invalid")).andExpect(status().isForbidden());var t=tree();var login=accounts.login(t.player().username(),"test-only-user-password");var c=new Cookie("ACE_SESSION",login.token());mvc.perform(post("/api/spins").cookie(c).header("X-Game-Client","web").contentType(MediaType.APPLICATION_JSON).content("{\"requestId\":\""+id()+"\",\"betCents\":2000,\"expectedRevision\":0}")).andExpect(status().isForbidden());mvc.perform(post("/api/spins").cookie(c).header("X-Game-Client","web").header("X-CSRF-Token",login.auth().csrf()).contentType(MediaType.APPLICATION_JSON).content("{\"requestId\":\""+id()+"\",\"betCents\":2000,\"expectedRevision\":0,\"balance\":999999}")).andExpect(status().isBadRequest());mvc.perform(get("/api/me")).andExpect(status().isUnauthorized());mvc.perform(get("/")).andExpect(status().isOk());}
}
