package philip.emerald.ace.Utils;
import philip.emerald.ace.superace.RtpSchedule;
import philip.emerald.ace.superace.GameService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import java.util.*;
import java.util.concurrent.*;
import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:upgrade;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1","spring.datasource.username=sa","spring.datasource.password=","ace.creator-user=creator","ace.zone=Asia/Manila","ace.creator-password=test-only-creator-password","ace.jwt-secret=test-only-secret-at-least-32-characters","ace.jobs-enabled=false","ace.spin-cooldown-ms=0"})
class UpgradeTest {
 @Autowired Accounts accounts;@Autowired HierarchyChips chips;@Autowired GameService game;@Autowired JdbcTemplate db;@Autowired RtpSchedule rtp;
 String id(){return UUID.randomUUID().toString();}
 Accounts.User creator(){return accounts.login("creator","test-only-creator-password").auth().user();}
 Accounts.User make(Accounts.User parent,Accounts.Role role){String name=id().replace("-","");return accounts.create(creator(),name,name,"test-only-user-password",role,parent.id());}
 @Test void registrationCodeJwtRefreshAndRevoke(){var sa=make(creator(),Accounts.Role.SUPER_AGENT);var a=make(sa,Accounts.Role.AGENT);String name=id().replace("-","");var login=accounts.register(name,"New player","test-only-user-password",a.publicCode());assertTrue(login.auth().user().publicCode().matches("[0-9]{6}"));assertEquals(a.id(),login.auth().user().parentId());assertEquals(3,login.token().split("\\.").length);assertEquals(name,accounts.authenticate(login.token()).user().username());assertThrows(GameService.ApiError.class,()->accounts.authenticate(login.token()+"x"));var next=accounts.refresh(login.refresh());assertThrows(GameService.ApiError.class,()->accounts.refresh(login.refresh()));assertThrows(GameService.ApiError.class,()->accounts.authenticate(login.token()));assertNotNull(accounts.authenticate(next.token()));accounts.logout(next.token());assertThrows(GameService.ApiError.class,()->accounts.refresh(next.refresh()));}
 @Test void movePlayerPromotionAndScope(){var sa=make(creator(),Accounts.Role.SUPER_AGENT);var a=make(sa,Accounts.Role.AGENT);var b=make(sa,Accounts.Role.AGENT);var p=make(a,Accounts.Role.PLAYER);var outsider=make(creator(),Accounts.Role.SUPER_AGENT);assertThrows(GameService.ApiError.class,()->accounts.change(outsider,p.id(),Accounts.Role.PLAYER,b.id(),true));var moved=accounts.change(sa,p.id(),Accounts.Role.PLAYER,b.id(),true);assertFalse(accounts.inScope(a,moved));assertTrue(accounts.inScope(b,moved));var promoted=accounts.change(sa,p.id(),Accounts.Role.AGENT,sa.id(),true);assertEquals(Accounts.Role.AGENT,promoted.role());assertThrows(GameService.ApiError.class,()->accounts.change(sa,p.id(),Accounts.Role.SUPER_AGENT,creator().id(),true));assertEquals(Accounts.Role.SUPER_AGENT,accounts.change(creator(),p.id(),Accounts.Role.SUPER_AGENT,creator().id(),true).role());}
 @Test void transfersConserveAndRetryExactlyOnce()throws Exception{var sa=make(creator(),Accounts.Role.SUPER_AGENT);var a=make(sa,Accounts.Role.AGENT);var p=make(a,Accounts.Role.PLAYER);chips.move(creator(),id(),a.id(),"ISSUE",20000);long total=game.wallet(a.id(),false).balanceCents()+game.wallet(p.id(),false).balanceCents();String request=id();try(var executor=Executors.newFixedThreadPool(2)){var x=executor.submit(()->chips.move(a,request,p.id(),"GIVE",10000));var y=executor.submit(()->chips.move(a,request,p.id(),"GIVE",10000));x.get(20,TimeUnit.SECONDS);y.get(20,TimeUnit.SECONDS);}assertEquals(10000,game.wallet(a.id(),false).balanceCents());assertEquals(total,game.wallet(a.id(),false).balanceCents()+game.wallet(p.id(),false).balanceCents());assertThrows(GameService.ApiError.class,()->chips.move(a,id(),p.id(),"GIVE",10001));chips.move(a,id(),p.id(),"TAKE",5000);assertEquals(15000,game.wallet(a.id(),false).balanceCents());assertThrows(GameService.ApiError.class,()->chips.move(a,id(),p.id(),"ISSUE",100));}
 @Test void rtpBoundaryAndBonusPin(){long start=1000;assertEquals("INTRO_97",RtpSchedule.profileAt(start,start+604799999));assertEquals("STANDARD_96",RtpSchedule.profileAt(start,start+604800000));var sa=make(creator(),Accounts.Role.SUPER_AGENT);var a=make(sa,Accounts.Role.AGENT);var p=make(a,Accounts.Role.PLAYER);db.update("UPDATE wallets SET free_spins=1,locked_bet=5000,bonus_profile='INTRO_97' WHERE player_id=?",p.id());db.update("UPDATE rtp_schedule SET starts_at=0");game.spin(p,id(),5000,0);assertEquals("INTRO_97",db.queryForObject("SELECT rtp_profile FROM round_ledger WHERE player_id=?",String.class,p.id()));}
}
