package philip.emerald.ace.colorgame;
import philip.emerald.ace.Utils.*;
import philip.emerald.ace.superace.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.test.util.AopTestUtils;
import org.springframework.jdbc.core.JdbcTemplate;
import java.util.*;
import java.util.concurrent.*;
import java.security.SecureRandom;
import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:jackpot;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1","spring.datasource.username=sa","spring.datasource.password=","ace.creator-user=creator","ace.creator-password=test-only-creator-password","ace.zone=Asia/Manila","ace.jobs-enabled=false","ace.jwt-secret=test-only-secret-at-least-32-characters"})
class ColorJackpotServiceTest {
 @Autowired JdbcTemplate db;@Autowired Accounts accounts;@Autowired ColorJackpotService jackpot;@Autowired ColorGameService color;@Autowired LobbyGameService lobby;@Autowired GameService club;@Autowired ChipNotifications notices;
 @BeforeEach void reset(){for(String t:List.of("color_jackpot_awards","color_jackpot_bets","color_jackpot_rounds","color_jackpot_journal"))db.update("DELETE FROM "+t);db.update("UPDATE color_jackpot_pools SET balance_cents=CASE WHEN mode='LOBBY' THEN 3000000 ELSE 0 END,remainder_units=0,contributed_cents=0,awarded_cents=0,revision=0");ReflectionTestUtils.setField((Object)AopTestUtils.getTargetObject(jackpot),"random",new SecureRandom(){@Override public int nextInt(int bound){return 100;}});}
 Accounts.User user(){String id=UUID.randomUUID().toString();db.update("INSERT INTO accounts(id,username,display_name,password_hash,role,created_at) VALUES(?,?,?,'test','PLAYER',0)",id,id,id);db.update("INSERT INTO wallets(player_id,balance) VALUES(?,12345)",id);db.update("INSERT INTO lobby_wallets(player_id,balance) VALUES(?,1000000)",id);return accounts.user(id);}
 void fixture(String mode,long id,boolean blue,Map<String,Long> bets){long start=id*15000;db.update("DELETE FROM color_game_rounds WHERE round_id=?",id);db.update("INSERT INTO color_game_rounds VALUES(?,?,?,?,?)",id,start,start+10000,start+15000,blue?"{\"dice\":[\"BLUE\",\"BLUE\",\"BLUE\"]}":"{\"dice\":[\"RED\",\"GREEN\",\"BLUE\"]}");db.update("INSERT INTO color_jackpot_rounds(mode,round_id,enabled) VALUES(?,?,?)",mode,id,mode.equals("LOBBY"));for(var e:bets.entrySet())db.update("INSERT INTO color_jackpot_bets VALUES(?,?,?,?,?)",mode,e.getKey(),UUID.randomUUID().toString(),id,e.getValue());}
 @Test void sharedAwardCreditsOnceAndOfflineNoticeIsOwned()throws Exception{var a=user();var b=user();fixture("LOBBY",11,true,Map.of(a.id(),10000L,b.id(),40000L));jackpot.settleDue("LOBBY",174999);assertEquals(0,db.queryForObject("SELECT COUNT(*) FROM color_jackpot_awards",Integer.class));
  try(var threads=Executors.newFixedThreadPool(4)){var calls=new ArrayList<Future<?>>();for(int i=0;i<8;i++)calls.add(threads.submit(()->jackpot.settleDue("LOBBY",175000)));for(var f:calls)f.get(15,TimeUnit.SECONDS);}
  long prize=150025;assertEquals(1000000+30005,lobby.wallet(a.id(),false).balanceCents());assertEquals(1000000+120020,lobby.wallet(b.id(),false).balanceCents());assertEquals(12345,club.wallet(a.id(),false).balanceCents());assertEquals(3000500-prize,db.queryForObject("SELECT balance_cents FROM color_jackpot_pools WHERE mode='LOBBY'",Long.class));assertEquals(2,db.queryForObject("SELECT COUNT(*) FROM color_jackpot_awards",Integer.class));assertEquals(2,db.queryForObject("SELECT COUNT(*) FROM color_jackpot_journal",Integer.class));var notice=notices.unread(a).stream().filter(n->n.kind().equals("JACKPOT")).findFirst().orElseThrow();assertEquals("MINOR",notice.tier());assertThrows(GameService.ApiError.class,()->notices.read(b,notice.id()));notices.read(a,notice.id());notices.read(a,notice.id());assertTrue(notices.unread(a).isEmpty());jackpot.settleDue("LOBBY",999999);assertEquals(1000000+30005,lobby.wallet(a.id(),false).balanceCents());}
 @Test void noTargetNoBetsAndDisabledClubNeverAward(){var a=user();fixture("LOBBY",12,false,Map.of(a.id(),101L));fixture("LOBBY",13,true,Map.of());fixture("CLUB",14,true,Map.of(a.id(),99999L));jackpot.settleDue("LOBBY",999999);jackpot.settleDue("CLUB",999999);assertEquals(3000001,db.queryForObject("SELECT balance_cents FROM color_jackpot_pools WHERE mode='LOBBY'",Long.class));assertEquals(1,db.queryForObject("SELECT remainder_units FROM color_jackpot_pools WHERE mode='LOBBY'",Integer.class));assertEquals(0,db.queryForObject("SELECT balance_cents FROM color_jackpot_pools WHERE mode='CLUB'",Long.class));assertEquals(0,db.queryForObject("SELECT COUNT(*) FROM color_jackpot_awards",Integer.class));}
 @Test void creatorTopUpIsIdempotentAndScoped(){var creator=accounts.user(db.queryForObject("SELECT id FROM accounts WHERE username='creator'",String.class));var a=user();String key=UUID.randomUUID().toString();assertThrows(GameService.ApiError.class,()->jackpot.topUp(a,"LOBBY",key,500));jackpot.topUp(creator,"LOBBY",key,500);jackpot.topUp(creator,"LOBBY",key,500);assertEquals(3000500,jackpot.snapshot("LOBBY").balanceCents());assertThrows(GameService.ApiError.class,()->jackpot.topUp(creator,"LOBBY",key,600));assertThrows(GameService.ApiError.class,()->jackpot.topUp(creator,"CLUB",key,500));assertThrows(GameService.ApiError.class,()->jackpot.snapshot("BAD"));}
 @Test void actualAcceptedBetsReserveOnlyStakeAndReplayDoesNotContributeTwice()throws Exception{var a=user();long time=System.currentTimeMillis();if(time%15000>7000)Thread.sleep(15000-time%15000+50);long id=System.currentTimeMillis()/15000;var r=color.play(a,"LOBBY",id,UUID.randomUUID().toString(),ColorGameEngine.Side.RED,500,0);assertEquals(999500,lobby.wallet(a.id(),false).balanceCents());assertEquals(r,color.play(a,"LOBBY",id,r.requestId(),r.side(),500,0));assertEquals(1,db.queryForObject("SELECT COUNT(*) FROM color_jackpot_bets WHERE player_id=?",Integer.class,a.id()));db.update("UPDATE color_game_rounds SET outcome_json='{\"dice\":[\"BLUE\",\"BLUE\",\"BLUE\"]}' WHERE round_id=?",id);jackpot.settleDue("LOBBY",r.revealAt());long balance=lobby.wallet(a.id(),false).balanceCents();assertTrue(balance>999500);color.settle("LOBBY",a.id(),r.revealAt());assertEquals(balance,lobby.wallet(a.id(),false).balanceCents());assertEquals(5,db.queryForObject("SELECT contributed_cents FROM color_jackpot_pools WHERE mode='LOBBY'",Long.class));}
}
