package vn.emerald.ace;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
@Service
public class Chips {
 private final GameService game;private final Accounts accounts;
 public Chips(GameService game,Accounts accounts){this.game=game;this.accounts=accounts;}
 public record Transfer(String id,String playerId,String displayName,String kind,long amountCents,String status,String reference,long createdAt,Long decidedAt,String decidedBy){}
 Transfer map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new Transfer(r.getString("id"),r.getString("player_id"),r.getString("display_name"),r.getString("kind"),r.getLong("amount_cents"),r.getString("status"),r.getString("reference_text"),r.getLong("created_at"),(Long)r.getObject("decided_at"),r.getString("decided_by"));}
 String select="SELECT t.*,a.display_name FROM chip_transfers t JOIN accounts a ON a.id=t.player_id";
 public List<Transfer> history(Accounts.User u,int page){String scope=switch(u.role()){case CREATOR->"1=1";case SUPER_AGENT->"(a.id=? OR a.parent_id=? OR a.parent_id IN (SELECT id FROM accounts WHERE parent_id=?))";case AGENT->"(a.id=? OR a.parent_id=?)";case PLAYER->"a.id=?";};var args=new ArrayList<Object>();if(u.role()!=Accounts.Role.CREATOR)args.add(u.id());if(u.role()==Accounts.Role.SUPER_AGENT){args.add(u.id());args.add(u.id());}if(u.role()==Accounts.Role.AGENT)args.add(u.id());args.add(Math.multiplyExact(page,100));return game.db().query(select+" WHERE "+scope+" ORDER BY t.created_at DESC,t.id LIMIT 100 OFFSET ?",this::map,args.toArray());}
 @Transactional public Transfer request(Accounts.User u,String requestId,String kind,long amount,String reference){accounts.require(u,Accounts.Role.PLAYER);var w=game.wallet(u.id(),true);var prior=game.db().query(select+" WHERE t.player_id=? AND t.request_id=?",this::map,u.id(),requestId);if(!prior.isEmpty()){var t=prior.getFirst();if(!t.kind().equals(kind)||t.amountCents()!=amount||!t.reference().equals(reference))throw GameService.error(409,"REQUEST_REUSED");return t;}
  if(!List.of("DEPOSIT","WITHDRAWAL").contains(kind)||amount<100||amount>100000000)throw GameService.error(400,"INVALID_AMOUNT");if(kind.equals("WITHDRAWAL")){if(w.balanceCents()<amount)throw GameService.error(409,"INSUFFICIENT_FUNDS");game.db().update("UPDATE wallets SET balance=balance-?,revision=revision+1 WHERE player_id=?",amount,u.id());}
  String id=UUID.randomUUID().toString();game.db().update("INSERT INTO chip_transfers(id,player_id,request_id,kind,amount_cents,status,reference_text,created_at) VALUES(?,?,?,?,?,'PENDING',?,?)",id,u.id(),requestId,kind,amount,reference,System.currentTimeMillis());accounts.audit(u.id(),"REQUEST_"+kind,id,Long.toString(amount));return game.db().query(select+" WHERE t.id=?",this::map,id).getFirst();
 }
 @Transactional public Transfer decide(Accounts.User u,String id,boolean approve){accounts.hierarchyLock();u=accounts.user(u.id());var found=game.db().query(select+" WHERE t.id=?",this::map,id);if(found.isEmpty())throw GameService.error(404,"NOT_FOUND");var first=found.getFirst();var target=accounts.user(first.playerId());if(u.role()==Accounts.Role.PLAYER||!accounts.inScope(u,target))throw GameService.error(403,"FORBIDDEN");var ids=new ArrayList<>(List.of(u.id(),target.id()));Collections.sort(ids);for(String account:ids)game.wallet(account,true);var t=game.db().query(select+" WHERE t.id=? FOR UPDATE",this::map,id).getFirst();String status=approve?"APPROVED":"REJECTED";if(!t.status().equals("PENDING")){if(t.status().equals(status))return t;throw GameService.error(409,"ALREADY_DECIDED");}
  if(approve&&u.role()!=Accounts.Role.CREATOR){if(t.kind().equals("DEPOSIT")){if(game.wallet(u.id(),false).balanceCents()<t.amountCents())throw GameService.error(409,"INSUFFICIENT_FUNDS");game.db().update("UPDATE wallets SET balance=balance-?,revision=revision+1 WHERE player_id=?",t.amountCents(),u.id());}else game.db().update("UPDATE wallets SET balance=balance+?,revision=revision+1 WHERE player_id=?",t.amountCents(),u.id());}
  if((approve&&t.kind().equals("DEPOSIT"))||(!approve&&t.kind().equals("WITHDRAWAL")))game.db().update("UPDATE wallets SET balance=balance+?,revision=revision+1 WHERE player_id=?",t.amountCents(),target.id());
  if(approve&&u.role()!=Accounts.Role.CREATOR)game.db().update("INSERT INTO chip_transfers(id,player_id,request_id,kind,amount_cents,status,reference_text,created_at,decided_at,decided_by) VALUES(?,?,?,?,?,'APPROVED',?,?,?,?)",UUID.randomUUID().toString(),u.id(),t.id(),t.kind().equals("DEPOSIT")?"WITHDRAWAL":"DEPOSIT",t.amountCents(),"Approved player request "+t.id(),System.currentTimeMillis(),System.currentTimeMillis(),u.id());
  game.db().update("UPDATE chip_transfers SET status=?,decided_at=?,decided_by=? WHERE id=?",status,System.currentTimeMillis(),u.id(),id);accounts.audit(u.id(),status+"_"+t.kind(),id,Long.toString(t.amountCents()));return game.db().query(select+" WHERE t.id=?",this::map,id).getFirst();
 }
}
