const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),cp=require('node:child_process'),fs=require('node:fs');
function sql(s){const output=cp.execFileSync(process.env.ACE_JAVA,['-cp',process.env.ACE_H2_JAR,'org.h2.tools.Shell','-url',process.env.DB_URL,'-user','sa','-password','','-sql',s],{encoding:'utf8'});assert(!/Error:/i.test(output),output);}
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.ACE_TEST_URL);await page.waitForFunction(()=>typeof cjpFetch==='function');await page.evaluate(()=>showView('colorGameView'));await page.waitForFunction(()=>cjpState?.enabled);assert.equal(await page.evaluate(()=>cjpState.balanceCents),3000000);await page.locator('#cgJackpotHelp').tap();await page.waitForFunction(()=>!cjpBusy);assert(await page.locator('#cjpTopUp').isHidden());assert.equal(await page.locator('.cjp-levels article').count(),4);assert.match(await page.locator('#cjpRules').textContent(),/1 of 216/);assert.match(await page.locator('#cjpLevels').textContent(),/0.1%/);await page.locator('#cgJackpotClose').tap();
 const actor=await page.evaluate(async()=>{await api('register','POST',{username:'jackpot'+Date.now(),password:'123456',rePassword:'123456'});await connect();return player;});
 // Scope is enforced at the HTTP boundary, not just by hiding the form.
 assert.equal(await page.evaluate(async()=>{try{await api('color-game/jackpot/top-up','POST',{requestId:requestUuid(),amountCents:100});return 200}catch(e){return e.status}}),403);
 const round=Math.floor(Date.now()/15000)-10,start=round*15000;
 sql(`INSERT INTO color_game_rounds VALUES(${round},${start},${start+10000},${start+15000},'{"dice":["BLUE","BLUE","BLUE"]}'); INSERT INTO color_jackpot_rounds(mode,round_id,enabled) VALUES('LOBBY',${round},TRUE); INSERT INTO color_jackpot_bets VALUES('LOBBY','${actor.id}','00000000-0000-0000-0000-000000000035',${round},10000);`);
 const state=await page.evaluate(()=>api('color-game/jackpot?mode=LOBBY')),awards=await page.evaluate(()=>api('color-game/jackpot/awards?mode=LOBBY'));assert.equal(awards.length,1);const award=awards[0],level=state.levels.find(l=>l.tier===award.tier);assert.equal(award.amountCents,Math.floor(3000100*level.prizeBps/10000));assert.equal(state.balanceCents,3000100-award.amountCents);assert.equal((await page.evaluate(()=>api('me?mode=LOBBY'))).balanceCents,actor.balanceCents+award.amountCents);assert.equal((await page.evaluate(()=>api('me?mode=CLUB'))).balanceCents,0);
 await page.waitForFunction(()=>!cgBusy);await page.evaluate(()=>pollReceipts());await page.waitForFunction(()=>receiptCurrent?.kind==='JACKPOT');assert.match(await page.locator('#receiptTitle').textContent(),/Jackpot won/);assert.match(await page.locator('#receiptSender').textContent(),new RegExp(award.tier));assert(await page.locator('#chipReceipt').evaluate(e=>e.classList.contains('jackpot-receipt')));if(process.env.ACE_SCREENSHOTS){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await page.screenshot({timeout:60000,path:process.env.ACE_SCREENSHOTS+'/jackpot-phone-award.png'});}await page.locator('#receiptRead').tap();
 await page.reload();await page.waitForFunction(()=>ready);await page.evaluate(()=>showView('colorGameView'));await page.waitForFunction(()=>cjpState?.enabled);await page.locator('#cgJackpotHelp').tap();await page.waitForFunction(()=>document.getElementById('cjpMine').textContent.includes('JACKPOT')||document.getElementById('cjpMine').textContent.includes('#'));assert.match(await page.locator('#cjpMine').textContent(),new RegExp('#'+round));assert.equal((await page.evaluate(()=>api('notifications'))).filter(n=>n.kind==='JACKPOT').length,0);assert.equal((await page.evaluate(()=>api('me?mode=LOBBY'))).balanceCents,actor.balanceCents+award.amountCents);await page.evaluate(()=>setLanguage('fil'));assert.match(await page.locator('#cjpRules').textContent(),/Tatlong ASUL/);await page.evaluate(()=>setLanguage('en'));await page.locator('#cgJackpotClose').tap();
 await page.waitForFunction(()=>!cgLocked()&&!busy&&!polling);await page.evaluate(()=>switchMode('CLUB'));await page.waitForFunction(()=>gameMode==='CLUB'&&cjpState?.mode==='CLUB');assert.equal(await page.evaluate(()=>cjpState.enabled),false);assert.equal(await page.evaluate(()=>cjpState.balanceCents),0);await page.locator('#cgJackpotHelp').tap();assert.match(await page.locator('#cjpRules').textContent(),/not enabled/);assert(await page.locator('#cjpTopUp').isHidden());await page.locator('#cgJackpotClose').tap();
 const creatorContext=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'}),creator=await creatorContext.newPage();creator.on('pageerror',e=>errors.push(e.message));await creator.goto(process.env.ACE_TEST_URL);await creator.waitForFunction(()=>typeof cjpFetch==='function');await creator.evaluate(async()=>{await api('login','POST',{username:'creator',password:'test-creator-password'});await connect();await showView('colorGameView')});await creator.waitForFunction(()=>cjpState?.enabled);await creator.locator('#cgJackpotHelp').click();await creator.waitForFunction(()=>!cjpBusy);assert(await creator.locator('#cjpTopUp').isVisible());const before=await creator.evaluate(()=>cjpState.balanceCents);await creator.locator('#cjpAmount').fill('10');await creator.locator('#cjpAdd').click();await creator.waitForFunction(()=>document.getElementById('cjpMessage').textContent==='Pool updated');assert.equal(await creator.evaluate(()=>cjpState.balanceCents),before+1000);if(process.env.ACE_SCREENSHOTS)await creator.screenshot({timeout:60000,path:process.env.ACE_SCREENSHOTS+'/jackpot-creator.png'});assert.deepEqual(errors,[]);
 console.log('PASS Jackpot: real pool/HTTP settlement, exact tier award, notification/reload/read, role authorization, Creator funding, Lobby/Club isolation, English/Filipino and phone landscape.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
