const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const reference=[['GREEN','WHITE','YELLOW'],['GREEN','RED','WHITE'],['GREEN','PINK','WHITE'],['BLUE','BLUE','RED'],['GREEN','GREEN','WHITE'],['BLUE','PINK','RED'],['BLUE','RED','RED'],['WHITE','WHITE','YELLOW'],['BLUE','PINK','YELLOW'],['GREEN','GREEN','WHITE']];
 const rows=Array.from({length:20},(_,i)=>({tableRoundId:200-i,createdAt:Date.now()-i*15000-30000,outcome:{dice:reference[i%10]}}));let data=rows;
 await page.route(/\/api\/color-game\/table\/history/,r=>r.fulfill({json:data}));
 await page.goto(process.env.ACE_TEST_URL);await page.waitForFunction(()=>typeof cgLoad==='function');await page.evaluate(()=>showView('colorGameView'));await page.waitForFunction(()=>cgHistoryRows.length===20);await page.locator('#cgHistoryButton').click();
 assert.equal(await page.locator('#cgHistoryList .cg-history-row').count(),10);assert.equal(await page.locator('#cgHistoryList .cg-mini-dice .cg-swatch').count(),30);assert.equal(await page.locator('#cgHistoryList .latest').count(),1);assert.equal(await page.locator('#cgHistoryPage').textContent(),'1–10 / 20');
 const colors=['YELLOW','WHITE','PINK','BLUE','RED','GREEN'],dice=rows.flatMap(r=>r.outcome.dice);for(const c of colors)assert.equal(await page.locator('#cgFrequency .cg-frequency-card.'+c+' small').textContent(),(dice.filter(v=>v===c).length*100/dice.length).toFixed(2)+'%');
 await page.locator('[data-history-id="199"]').click();assert.match(await page.locator('#cgHistoryDetail').textContent(),/#199/);assert.equal(await page.locator('[data-history-id="199"]').getAttribute('aria-pressed'),'true');
 await page.locator('#cgHistoryNext').click();assert.equal(await page.locator('#cgHistoryPage').textContent(),'11–20 / 20');assert.equal(await page.locator('#cgHistoryList .latest').count(),0);assert(await page.locator('#cgHistoryNext').isDisabled());assert.match(await page.locator('#cgHistoryDetail').textContent(),/#190/);await page.locator('#cgHistoryPrev').click();
 for(const width of [1440,844,760,390,320]){await page.setViewportSize({width,height:width===844?390:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page overflow '+width);const dialog=await page.locator('#cgHistoryDialog').boundingBox();assert(dialog.x>=-1&&dialog.x+dialog.width<=width+1,'dialog overflow '+width);for(const id of ['cgHistoryClose','cgHistoryRefresh','cgHistoryNext']){const box=await page.locator('#'+id).boundingBox();assert(box.width>=44&&box.height>=44,'touch '+id);}if(process.env.ACE_SCREENSHOTS){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await page.screenshot({path:process.env.ACE_SCREENSHOTS+'/history-'+width+'.png',fullPage:true});}}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>setLanguage('fil'));assert.match(await page.locator('#cgHistorySample').textContent(),/natapos na laro/);await page.evaluate(()=>setLanguage('en'));
 data=rows.slice(0,3);await page.locator('#cgHistoryRefresh').click();await page.waitForFunction(()=>cgHistoryRows.length===3);assert.equal(await page.locator('#cgHistoryPage').textContent(),'1–3 / 3');assert(await page.locator('#cgHistoryNext').isDisabled());
 data=[];await page.locator('#cgHistoryRefresh').click();await page.waitForFunction(()=>cgHistoryRows.length===0);assert.equal(await page.locator('#cgHistoryList .cg-history-row').count(),0);assert.equal(await page.locator('#cgFrequency small').first().textContent(),'—');assert.equal(await page.locator('#cgHistoryDetail').textContent(),'');
 await page.keyboard.press('Escape');assert(!(await page.locator('#cgHistoryDialog').evaluate(d=>d.open)));assert.deepEqual(errors,[]);console.log('PASS History: API fixtures, exact frequencies, 20 results / 2 pages, three vertical colors, selection, refresh, empty state, Filipino, Escape and 5 responsive widths.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
