const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
for(const v of [{width:390,height:844,dpr:3},{width:844,height:390,dpr:3},{width:360,height:800,dpr:2},{width:320,height:568,dpr:1},{width:1440,height:900,dpr:1}]){
 const context=await browser.newContext({viewport:{width:v.width,height:v.height},deviceScaleFactor:v.dpr,isMobile:v.width<1000,hasTouch:v.width<1000}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/*',async route=>{if(route.request().resourceType()==='document'){const response=await route.fetch();return route.fulfill({response,body:(await response.text()).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'')});}return route.continue()});
 await p.goto(process.env.ACE_TEST_URL);await p.evaluate(()=>{window.$=id=>document.getElementById(id);window.filipino={};window.activeView='colorGameView';window.showView=async id=>activeView=id;document.querySelectorAll('main').forEach(e=>e.hidden=e.id!=='colorGameView')});await p.addScriptTag({url:process.env.ACE_TEST_URL+'/color-landscape.js'});await p.addScriptTag({url:process.env.ACE_TEST_URL+'/color-dice-3d.js'});
 assert(await p.evaluate(()=>CG3D.roll({dice:['RED','PINK','GREEN']},{instant:true})));const d=await p.evaluate(()=>CG3D.debug());assert(d.available,'real WebGL required');assert.deepEqual(d.colors,['RED','PINK','GREEN']);assert(d.contacts>0);assert(d.top.every(x=>x.alignment>.995));
 const target=Math.min(3,Math.max(v.dpr,720/Math.min(v.width,v.height)));assert(Math.abs(d.pixelRatio-Math.min(target,Math.sqrt(1500000/(d.cssWidth*d.cssHeight))))<.01);assert(Math.abs(d.bufferWidth-d.cssWidth*d.pixelRatio)<1.1);assert(Math.abs(d.bufferHeight-d.cssHeight*d.pixelRatio)<1.1);assert(d.bufferWidth*d.bufferHeight<=1500000);assert(d.pixelRatio>1.5||v.width===1440);console.log('PASS HD',JSON.stringify({viewport:v,ratio:d.pixelRatio,buffer:[d.bufferWidth,d.bufferHeight],css:[d.cssWidth,d.cssHeight]}));
 if(v.width===844){
  await p.evaluate(()=>{window.movingRoll=CG3D.roll({dice:['BLUE','WHITE','YELLOW']})});await p.waitForFunction(()=>CG3D.debug().active&&CG3D.debug().frames>0);const first=await p.evaluate(()=>CG3D.debug().positions);await p.waitForTimeout(450);assert.notDeepEqual(await p.evaluate(()=>CG3D.debug().positions),first);assert(await p.evaluate(()=>movingRoll));assert.deepEqual(await p.evaluate(()=>CG3D.debug().colors),['BLUE','WHITE','YELLOW']);
  if(process.env.ACE_SCREENSHOTS){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await p.screenshot({path:process.env.ACE_SCREENSHOTS+'/color-hd-landscape.png',timeout:60000});}
  await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>document.body.classList.contains('cg-rotated'));await p.waitForTimeout(150);assert.deepEqual(await p.evaluate(()=>CG3D.debug().colors),['BLUE','WHITE','YELLOW']);
 }
 assert.equal(await p.evaluate(async()=>{const r=CG3D.roll({dice:['BLUE','RED','WHITE']});CG3D.stop();return await r}),false);
 await p.evaluate(()=>document.querySelector('#cgWebgl canvas').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));assert.equal(await p.evaluate(()=>CG3D.roll({dice:['RED','RED','RED']},{instant:true})),false);assert.deepEqual(errors,[]);await context.close();
}console.log('PASS HD rendering, real physics and colors, resize/orientation, cancellation and GPU-loss fallback; no JS errors.');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
