const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox']});try{
 const ctx=await browser.newContext({reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACE_TEST_URL);await p.waitForFunction(()=>typeof cgLoad==='function');await p.evaluate(async()=>{await api('register','POST',{username:'recover'+Date.now(),password:'123456',rePassword:'123456'});await connect();await showView('colorGameView')});
 const fresh=()=>p.waitForFunction(()=>cgBetting()&&cgState.bettingClosesAt-cgNow()>7500&&!cgSending&&!cgFetching&&!cgBusy,null,{timeout:25000});await fresh();
 let release,heldResolve;const held=new Promise(r=>heldResolve=r),gate=new Promise(r=>release=r);let intercepted=false;
 await p.route('**/api/color-game/bets?*',async route=>{if(intercepted)return route.continue();intercepted=true;const response=await route.fetch();heldResolve();await gate;await route.fulfill({response});});
 await p.evaluate(()=>{void cgFetch()});await held;await p.locator('[data-cg-side=RED]').click();await p.waitForFunction(()=>cgBets.length===1&&!cgSending);release();await p.waitForFunction(()=>!cgFetching);assert.equal(await p.evaluate(()=>cgBets.length),1,'old poll must not erase accepted bet');await p.unroute('**/api/color-game/bets?*');
 await fresh();const before=await p.evaluate(()=>balance);let lost=false,requestId;
 await p.route('**/api/color-game/rounds?*',async route=>{if(route.request().method()!=='POST'||lost)return route.continue();lost=true;requestId=route.request().postDataJSON().requestId;await route.fetch();await route.abort('connectionfailed');});
 await p.locator('[data-cg-side=BLUE]').click();await p.waitForFunction(()=>cgQueue.length===0&&!cgSending&&cgBets.some(b=>b.side==='BLUE'),null,{timeout:10000});assert.equal(await p.evaluate(()=>balance),before-5);assert.equal(await p.evaluate(id=>cgBets.filter(b=>b.requestId===id).length,requestId),1);await p.unroute('**/api/color-game/rounds?*');
 await ctx.setOffline(true);await p.waitForTimeout(5000);assert(await p.locator('[data-cg-side=RED]').isDisabled());await ctx.setOffline(false);await p.waitForFunction(()=>!cgNetworkError&&!cgFetching,null,{timeout:15000});
 await p.waitForFunction(()=>!cgLocked(),null,{timeout:20000});await p.evaluate(()=>showView('dragonTigerView'));
 const victory=await p.evaluate(()=>{const row={tableRoundId:987654321,betCents:500,payoutCents:1000,outcome:{winner:'DRAGON'}};dtCelebrate({...row,payoutCents:0});const loss=dtVictory.hidden;dtCelebrate({...row,payoutCents:500});const refund=dtVictory.hidden;dtCelebrate(row);const win=!dtVictory.hidden&&$('dtVictoryAmount').textContent.includes('5');const particles=dtVictory.querySelectorAll('.dt-victory-coins i').length;dtHideVictory();dtCelebrate(row);return {loss,refund,win,particles,deduped:dtVictory.hidden}});assert.deepEqual(victory,{loss:true,refund:true,win:true,particles:0,deduped:true});assert.deepEqual(errors,[]);console.log('PASS recovery: delayed snapshot, accepted response lost/retry charged once, offline betting lock/reconnect, Dragon Tiger win/refund/loss/deduplication/reduced motion.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
