const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
const p=await browser.newPage({viewport:{width:1280,height:850},reducedMotion:'no-preference'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACE_TEST_URL);await p.waitForFunction(()=>!!window.CG3D&&typeof cgLoad==='function');await p.evaluate(()=>showView('colorGameView'));await p.waitForFunction(()=>cgState&&!cgFetching&&!cgBusy);await p.evaluate(()=>{clearInterval(0);activeView='test';cgDice({dice:['RED','PINK','GREEN']});window.testRoll=CG3D.roll({dice:['RED','PINK','GREEN']});});
await p.waitForFunction(()=>CG3D.debug().frames>0);const first=await p.evaluate(()=>CG3D.debug());assert(first.available);assert(first.contacts>0);assert(first.frames>100);await p.waitForTimeout(400);const moving=await p.evaluate(()=>CG3D.debug());assert.notDeepEqual(first.quaternions,moving.quaternions);assert.notDeepEqual(first.positions,moving.positions);if(process.env.ACE_SCREENSHOTS){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await p.screenshot({path:process.env.ACE_SCREENSHOTS+'/dice-tumble.png',fullPage:true})}assert(await p.evaluate(()=>testRoll));let final=await p.evaluate(()=>CG3D.debug());assert.deepEqual(final.colors,['RED','PINK','GREEN']);assert(final.top.every(t=>t.alignment>.995));assert(final.positions.every(p=>p[1]>.45&&p[1]<.6));
for(const dice of [['YELLOW','WHITE','BLUE'],['PINK','PINK','RED'],['RED','RED','RED']]){assert(await p.evaluate(dice=>CG3D.roll({dice},{instant:true}),dice));assert.deepEqual(await p.evaluate(()=>CG3D.debug().colors),dice)}
for(const width of [320,390,760,844,1440]){await p.setViewportSize({width,height:width===844?390:900});await p.waitForTimeout(60);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);if(process.env.ACE_SCREENSHOTS)await p.screenshot({path:process.env.ACE_SCREENSHOTS+'/webgl-'+width+'.png',fullPage:true})}
// Reset cancels the pending render without allowing an old result to reappear.
assert.equal(await p.evaluate(async()=>{const roll=CG3D.roll({dice:['BLUE','WHITE','YELLOW']});CG3D.stop();return await roll}),false);assert(!(await p.locator('#cgCase').getAttribute('class')).includes('webgl-dice'));
// Lost GPU context must resolve the reveal through the CSS fallback, never leave betting busy.
await p.evaluate(()=>{window.lossRoll=CG3D.roll({dice:['WHITE','BLUE','PINK']});const c=document.querySelector('#cgWebgl canvas');c.dispatchEvent(new Event('webglcontextlost',{cancelable:true}));cgReveal({dice:['RED','PINK','WHITE']})});assert.equal(await p.evaluate(()=>lossRoll),false);await p.waitForFunction(()=>!cgBusy,{},{timeout:6000});assert(!(await p.locator('#cgCase').getAttribute('class')).includes('webgl-dice'));assert.equal(await p.locator('.cg-die.RED .cf-4').count(),1);assert.deepEqual(errors,[]);console.log('PASS WebGL physics: actual renderer, collisions, motion, flat stable top faces, all six colors/repeated colors, five widths, cancellation and GPU-loss fallback.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
