const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),cp=require('node:child_process');
const sql=s=>cp.execFileSync(process.env.ACE_JAVA,['-cp',process.env.ACE_H2_JAR,'org.h2.tools.Shell','-url',process.env.DB_URL,'-user','sa','-password','','-sql',s],{stdio:'pipe'});
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox']});try{const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'no-preference'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACE_TEST_URL);await p.waitForFunction(()=>typeof cgLoad==='function');await p.evaluate(async()=>{await api('register','POST',{username:'colors'+Date.now(),password:'123456',rePassword:'123456'});await connect();await showView('colorGameView')});await p.waitForFunction(()=>cgBetting()&&cgState.bettingClosesAt-cgNow()>8000&&!cgFetching&&!cgBusy,{}, {timeout:25000}).catch(async e=>{console.log(await p.evaluate(()=>({activeView,ready,cgState,cgFetching,cgBusy,status:document.getElementById('cgStatus').textContent,errors:document.body.innerText.slice(-1000)})));throw e});
 const mapping=await p.evaluate(()=>{const rows=[];for(const c of cgColors){cgDice({dice:[c,c,c]});rows.push(...[...document.querySelectorAll('#cgDice .cg-die')].map(d=>({color:c,top:d.querySelector('.cf-4').classList.contains(c),result:d.querySelector('.cf-4').classList.contains('result-face'),symbol:d.querySelector('.cf-4').textContent,expected:cgSymbols[cgColors.indexOf(c)],label:d.querySelector('small').textContent,expectedLabel:t(c),unique:new Set([...d.querySelectorAll('.cg-cube-face')].map(f=>cgColors.find(x=>f.classList.contains(x)))).size})));}cgDice();return rows});for(const row of mapping){assert(row.top&&row.result);assert.equal(row.symbol,row.expected);assert.equal(row.label,row.expectedLabel);assert.equal(row.unique,6)};
 const before=await p.evaluate(()=>balance),round=await p.evaluate(()=>cgState.roundId);await p.locator('[data-cg-chip="10"]').click();for(const c of ['RED','YELLOW','WHITE'])await p.locator('[data-cg-side='+c+']').click();await p.waitForFunction(()=>cgBets.length===3&&!cgSending&&!cgQueue.length);assert.equal(await p.evaluate(()=>balance),before-30);assert(await p.locator('[data-cg-side=GREEN]').isDisabled());assert(!(await p.locator('[data-cg-side=RED]').isDisabled()));
 const blocked=await p.evaluate(async()=>{try{await api('color-game/rounds','POST',{requestId:requestUuid(),tableRoundId:cgState.roundId,side:'GREEN',betCents:1000,expectedRevision:revision});return 'accepted'}catch(e){return e.code}});assert.equal(blocked,'COLOR_LIMIT');assert.equal((await p.evaluate(()=>api('me'))).balanceCents,Math.round((before-30)*100));
 sql(`UPDATE color_game_rounds SET outcome_json='{"dice":["GREEN","RED","RED"]}' WHERE round_id=${round}`);
 await p.waitForFunction(()=>cgBusy&&(cgAnimations.length===6||(window.CG3D?.debug().active&&window.CG3D.debug().frames>=100)),{}, {timeout:20000});const motion=await p.evaluate(()=>cgAnimations.length?cgAnimations[0].effect.getKeyframes().length:window.CG3D.debug().frames);assert(motion>=100);assert.equal(await p.locator('.cg-cube').count(),3);await p.waitForFunction(id=>cgShown===id&&!cgBusy,round);assert.equal(await p.evaluate(()=>cgBets.reduce((n,b)=>n+b.payoutCents,0)),3000);assert.equal(await p.evaluate(()=>balance),before);assert.match(await p.locator('#cgResult').textContent(),/Total bet 30.*Total returned 30.*Net 0/);assert.equal(await p.locator('.ace-victory').count(),0);
 assert.deepEqual(await p.locator('#cgDice .cf-4').evaluateAll(es=>es.map(e=>['YELLOW','WHITE','PINK','BLUE','RED','GREEN'].find(c=>e.classList.contains(c)))),['GREEN','RED','RED']);
 if(process.env.ACE_SCREENSHOTS){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await p.screenshot({path:process.env.ACE_SCREENSHOTS+'/color-example.png',fullPage:true})}
 // The same-colour top-up remains available and a new round clears the three-colour limit.
 await p.waitForFunction(()=>cgBetting()&&cgState.bettingClosesAt-cgNow()>8000&&!cgFetching&&!cgBusy,{}, {timeout:25000});assert.equal(await p.evaluate(()=>cgSelected().size),0);await p.evaluate(()=>{cgChip=5;cgPlay('RED');cgPlay('YELLOW');cgPlay('WHITE');cgPlay('BLUE');cgPlay('RED')});await p.waitForFunction(()=>cgBets.length===4&&!cgSending&&!cgQueue.length);assert.equal(await p.evaluate(()=>cgSelected().size),3);assert.equal(await p.evaluate(()=>cgBets.filter(b=>b.side==='RED').length),2);assert.equal(await p.evaluate(()=>cgBets.some(b=>b.side==='BLUE')),false);
 for(const width of [320,390,760,844,1440]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))}assert.deepEqual(errors,[]);console.log('PASS Color face mapping (all 6 colors, top symbol and label) plus V27: exact red/yellow/white 10 each -> green/red/red returns 30, net zero; no false-win overlay; fourth color rejected server/client without debit; pending queue limit and top-ups; new-round reset; ballistic dice and five responsive widths.');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
