const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox'],env:{...process.env}});try{
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.ACE_TEST_URL);await page.waitForFunction(()=>typeof cgLoad==='function');await page.evaluate(()=>showView('colorGameView'));await page.waitForFunction(()=>cgBetting());
 await page.locator('[data-cg-side=RED]').click();assert(await page.locator('#loginDialog').evaluate(e=>e.open));await page.locator('#previewTheme').click();
 await page.evaluate(async username=>{await api('register','POST',{username,password:'123456',rePassword:'123456'});await connect();await showView('colorGameView');},'color'+Date.now());await page.waitForFunction(()=>ready&&cgState&&!cgFetching);
 assert.equal(await page.locator('[data-cg-side]').count(),6);assert.equal(await page.locator('#cgDice .cg-die').count(),3);
 for(const width of [320,390,760,844,1440]){await page.setViewportSize({width,height:width===844?390:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow '+width);for(const selector of ['[data-cg-chip="5"]','[data-cg-side=RED]']){const r=await page.locator(selector).boundingBox();assert(r.width>=44&&r.height>=44,'touch target '+selector);}if(process.env.ACE_SCREENSHOTS){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await page.screenshot({path:process.env.ACE_SCREENSHOTS+'/color-'+width+'.png',fullPage:true});}}
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>cgBetting()&&cgState.bettingClosesAt-cgNow()>7500&&!cgFetching&&!cgBusy,{},{timeout:20000});const round=await page.evaluate(()=>cgState.roundId),before=await page.evaluate(()=>balance);
 await page.locator('[data-cg-chip="5"]').click();await page.locator('[data-cg-side=RED]').click({clickCount:2,delay:65});await page.locator('[data-cg-chip="10"]').click();await page.locator('[data-cg-side=BLUE]').click();await page.waitForFunction(()=>cgBets.length===3&&!cgSending&&cgQueue.length===0);
 assert.equal(await page.evaluate(()=>balance),before-20);assert.equal(await page.locator('[data-cg-side=RED] .cg-stack').getAttribute('data-count'),'2');assert.equal(await page.locator('[data-cg-side=RED] .cg-stack i').count(),2);assert(await page.evaluate(()=>cgBets.every(b=>!b.outcome&&b.payoutCents===0)));
 const accepted=await page.evaluate(()=>cgBets[0]);await page.evaluate(async b=>{const w=await api('me');await api('color-game/rounds','POST',{requestId:b.requestId,tableRoundId:b.tableRoundId,side:b.side,betCents:b.betCents,expectedRevision:w.revision});},accepted);assert.equal((await page.evaluate(()=>api('me'))).balanceCents,(before-20)*100);
 await page.reload();await page.waitForFunction(()=>ready);await page.evaluate(()=>showView('colorGameView'));await page.waitForFunction(()=>cgBets.length===3);await page.waitForFunction(id=>cgShown===id&&!cgBusy&&cgBets.every(b=>b.outcome),round,{timeout:20000});const settled=await page.evaluate(()=>cgBets);let expected=0;for(const b of settled){const n=b.outcome.dice.filter(c=>c===b.side).length;assert.equal(b.payoutCents,n?(n+1)*b.betCents:0);expected+=b.payoutCents;}assert.equal(await page.evaluate(()=>balance),before-20+expected/100);assert.equal(await page.locator('#cgDice .hidden-die').count(),0);
 if(process.env.ACE_SCREENSHOTS)await page.screenshot({path:process.env.ACE_SCREENSHOTS+'/color-dice-result.png',fullPage:true});await page.locator('#cgHistoryButton').click();await page.waitForFunction(()=>cgHistoryRows.length>0);assert.equal(await page.locator('#cgFrequency>div').count(),6);assert(await page.locator('.cg-history-row').count()>0);await page.locator('#cgHistoryClose').click();
 await page.locator('#cgSound').click();await page.locator('#cgSound').click();assert(await page.evaluate(()=>sound&&audioCtx?.state==='running'));
 await page.evaluate(()=>setLanguage('fil'));assert.equal(await page.locator('[data-cg-side=RED] b').textContent(),'PULA');await page.evaluate(()=>setLanguage('en'));
 const otherContext=await browser.newContext({reducedMotion:'reduce'}),other=await otherContext.newPage();await other.goto(process.env.ACE_TEST_URL);await other.waitForFunction(()=>typeof api==='function');await other.evaluate(async username=>{await api('register','POST',{username,password:'123456',rePassword:'123456'});await connect();},'colorOther'+Date.now());
 await page.waitForFunction(()=>cgBetting()&&cgState.bettingClosesAt-cgNow()>7000&&!cgBusy&&!cgFetching,{},{timeout:20000});await page.locator('[data-cg-chip="5"]').click();await page.locator('[data-cg-side=GREEN]').click({clickCount:2,delay:65});await page.waitForFunction(()=>cgBets.length===2&&!cgSending);const shared=await page.evaluate(()=>cgState.roundId);
 await other.evaluate(async roundId=>{const w=await api('me?mode=LOBBY');await api('color-game/rounds?mode=LOBBY','POST',{requestId:requestUuid(),tableRoundId:roundId,side:'GREEN',betCents:2000,expectedRevision:w.revision});},shared);
 await page.waitForFunction(()=>cgCrowd?.sides.find(x=>x.side==='GREEN')?.othersCents===2000);assert.match(await page.locator('[data-cg-side=GREEN] .cg-others').textContent(),/20/);const clubPool=await page.evaluate(id=>api('color-game/crowd?mode=CLUB&roundId='+id),shared);assert(clubPool.sides.every(s=>s.ownCents===0&&s.othersCents===0));
 if(process.env.ACE_SCREENSHOTS)await page.screenshot({path:process.env.ACE_SCREENSHOTS+'/color-multiplayer.png',fullPage:true});
 for(let attempt=0;attempt<12;attempt++){await page.waitForFunction(()=>!cgLocked()&&!busy&&!polling&&!modeChanging,{},{timeout:20000});const mode=await page.evaluate(async()=>{await switchMode('CLUB');return gameMode});if(mode==='CLUB')break;await page.waitForTimeout(100);}assert.equal(await page.evaluate(()=>gameMode),'CLUB');assert.equal(await page.evaluate(()=>balance),0);await page.locator('[data-cg-side=GREEN]').click();assert.match(await page.locator('#cgStatus').textContent(),/insufficient|balance|enough/i);
 assert.deepEqual(errors,[]);console.log('PASS Color Game: responsive desktop/mobile, guest/register, stacked chips, hidden outcomes, exact payouts, retry/reload, history, Filipino, audio, two players and wallet isolation.');await otherContext.close();
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
