const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.setDefaultTimeout(30000);p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACE_TEST_URL);await p.waitForFunction(()=>typeof cgScreenLayout==='function');await p.evaluate(()=>showView('colorGameView'));await p.waitForFunction(()=>document.body.classList.contains('cg-rotated'));
 for(const viewport of [{width:390,height:844},{width:844,height:390},{width:667,height:375},{width:360,height:800}]){console.log('Viewport',viewport.width,viewport.height);await p.setViewportSize(viewport);await p.waitForFunction(v=>{const r=document.getElementById('colorGameView').getBoundingClientRect();return document.body.classList.contains('cg-rotated')===(v.height>v.width)&&Math.abs(r.width-v.width)<2&&Math.abs(r.height-v.height)<2},viewport,{timeout:8000}).catch(async e=>{console.log(await p.evaluate(()=>({width:innerWidth,height:innerHeight,vw:visualViewport.width,vh:visualViewport.height,scale:visualViewport.scale,classes:document.body.className,rect:document.getElementById('colorGameView').getBoundingClientRect().toJSON()})));throw e});assert.equal(await p.evaluate(()=>document.body.classList.contains('cg-rotated')),viewport.height>viewport.width);const r=await p.locator('#colorGameView').boundingBox();assert(r.x>=-1&&r.y>=-1&&r.x+r.width<=viewport.width+1&&r.y+r.height<=viewport.height+1,'rotated surface bounds');for(const sel of ['[data-cg-side=RED]','[data-cg-side=GREEN]','[data-cg-chip="5"]','#cgExit','#cgHistoryButton']){const b=await p.locator(sel).boundingBox();assert(b.width>=43&&b.height>=43,'tap target '+sel);assert(b.x>=-1&&b.y>=-1&&b.x+b.width<=viewport.width+1&&b.y+b.height<=viewport.height+1,'visible control '+sel);}await p.locator('[data-cg-chip="10"]').tap();assert.equal(await p.evaluate(()=>cgChip),10);await p.locator('#cgHistoryButton').tap();assert(await p.locator('#cgHistoryDialog').evaluate(d=>d.open));if(process.env.ACE_SCREENSHOTS&&viewport.width===844){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await p.screenshot({timeout:60000,path:process.env.ACE_SCREENSHOTS+'/phone-history-'+viewport.width+'.png'});}await p.locator('#cgHistoryClose').tap();await p.locator('#cgJackpotHelp').tap();assert(await p.locator('#cgJackpotDialog').evaluate(d=>d.open));await p.locator('#cgJackpotClose').tap();if(process.env.ACE_SCREENSHOTS&&viewport.width===844)await p.screenshot({timeout:60000,path:process.env.ACE_SCREENSHOTS+'/phone-game-'+viewport.width+'.png'});}
 await p.waitForFunction(()=>cgBetting()&&!cgBusy);await p.locator('[data-cg-side=RED]').tap();assert(await p.locator('#loginDialog').evaluate(d=>d.open));await p.locator('#previewTheme').tap();
 // A denied native fullscreen request must preserve usable CSS landscape.
 await p.evaluate(()=>{document.documentElement.requestFullscreen=()=>Promise.reject(new Error('not supported'))});await p.locator('#cgFullscreen').tap();assert(await p.evaluate(()=>document.body.classList.contains('cg-wide')));
 await p.evaluate(async()=>{await api('register','POST',{username:'landscape'+Date.now(),password:'123456',rePassword:'123456'});await connect();await showView('colorGameView')});await p.waitForFunction(()=>cgBetting()&&cgState.bettingClosesAt-cgNow()>7000&&!cgFetching&&!cgBusy,{}, {timeout:25000});await p.locator('[data-cg-chip="5"]').tap();await p.locator('[data-cg-side=RED]').tap();await p.waitForFunction(()=>cgBets.length===1&&!cgSending);assert.equal(await p.evaluate(()=>cgBets[0].side),'RED');
 await p.waitForFunction(()=>!cgLocked()&&!busy&&!polling,{}, {timeout:25000});await p.locator('#cgExit').tap();await p.waitForFunction(()=>activeView==='gameView');assert(!(await p.evaluate(()=>document.body.classList.contains('cg-wide'))));assert.equal(await p.locator('#gameView').evaluate(e=>getComputedStyle(e).transform),'none');assert.deepEqual(errors,[]);console.log('PASS Phone landscape: portrait CSS rotation, native landscape, visible touch controls, dialogs, fullscreen rejection, real wager and cleanup on exit.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
