const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),cp=require('node:child_process');
const sql=s=>cp.execFileSync(process.env.ACE_JAVA,['-cp',process.env.ACE_H2_JAR,'org.h2.tools.Shell','-url',process.env.DB_URL,'-user','sa','-password','','-sql',s],{stdio:'pipe'});
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox']});try{
 const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACE_TEST_URL);await p.waitForFunction(()=>typeof crLoad==='function');await p.evaluate(()=>showView('crashView'));await p.waitForFunction(()=>crState&&!crPoll);await p.locator('#crAction').click();assert(await p.locator('#loginDialog').evaluate(e=>e.open));await p.locator('#previewTheme').click();
 await p.evaluate(async()=>{await api('register','POST',{username:'crash'+Date.now(),password:'123456',rePassword:'123456'});await connect();await showView('crashView');});await p.waitForFunction(()=>ready&&crState&&!crPoll);
 // Mark today's reward as already processed in this isolated fixture so scheduler grants do not change wager assertions.
 const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());sql(`INSERT INTO lobby_daily_rewards(id,player_id,reward_date,amount_cents,created_at,read_at) SELECT RANDOM_UUID(),a.id,DATE '${day}',0,1,1 FROM accounts a WHERE a.role='PLAYER' AND NOT EXISTS(SELECT 1 FROM lobby_daily_rewards d WHERE d.player_id=a.id AND d.reward_date=DATE '${day}'); UPDATE lobby_daily_rewards SET read_at=1`);
 for(const width of [320,390,760,844,1440]){await p.setViewportSize({width,height:width===844?390:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);const action=await p.locator('#crAction').boundingBox();assert(action.height>=44);if(process.env.ACE_SCREENSHOTS){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await p.screenshot({path:process.env.ACE_SCREENSHOTS+'/crash-'+width+'.png',fullPage:true});}}
 await p.setViewportSize({width:390,height:844});
 async function fresh(point){sql('UPDATE crash_rounds SET next_at=0');await p.evaluate(()=>crLoad());await p.waitForFunction(()=>!crPoll);const id=await p.evaluate(()=>crState.roundId),flight=Date.now()+10000,crash=flight+Math.ceil(Math.log(point/100)*8000);sql(`UPDATE crash_rounds SET flight_at=${flight},crash_at=${crash},next_at=${crash+5000},crash_bps=${point} WHERE round_id=${id}`);await p.evaluate(()=>crLoad());return id;}
 const round=await fresh(300),before=await p.evaluate(()=>balance);let dropped=false;
 await p.route('**/api/crash/bets?*',async route=>{if(route.request().method()!=='POST'||dropped)return route.continue();dropped=true;await route.fetch();await route.abort('connectionfailed');});
 await p.locator('#crAction').click();await p.waitForFunction(()=>!crPending&&!crSending&&crMine()?.status==='ACTIVE',null,{timeout:10000});assert.equal(await p.evaluate(()=>balance),before-5);await p.unroute('**/api/crash/bets?*');
 const receipt=await p.evaluate(()=>crMine());assert.equal(receipt.autoCashoutBps,200);assert.equal(await p.evaluate(()=>crState.crashBps),null);assert.equal(await p.evaluate(()=>crState.nextRoundAt),null);await p.evaluate(()=>switchMode('CLUB'));assert.equal(await p.evaluate(()=>gameMode),'LOBBY');
 await p.reload();await p.waitForFunction(()=>ready);await p.evaluate(()=>showView('crashView'));await p.waitForFunction(()=>crMine()?.status==='ACTIVE');await ctx.setOffline(true);await p.waitForTimeout(18000);await ctx.setOffline(false);await p.waitForFunction(()=>crBets.find(b=>b.tableRoundId===crState.roundId)?.status==='CASHED_OUT'||crBets.some(b=>b.status==='CASHED_OUT'),null,{timeout:12000});assert.equal(await p.evaluate(()=>balance),before+5);const settled=await p.evaluate(id=>crBets.find(b=>b.requestId===id),receipt.requestId);assert.equal(settled.payoutCents,1000);assert.equal(settled.cashoutBps,200);
 const manualRound=await fresh(800);await p.locator('#crAutoEnabled').uncheck();await p.locator('#crAction').click();await p.waitForFunction(()=>crMine()?.status==='ACTIVE'&&!crSending);await p.waitForFunction(()=>crState.phase==='FLYING');await p.locator('#crAction').click();await p.waitForFunction(()=>crMine()?.status==='CASHED_OUT'&&!crSending);const manual=await p.evaluate(()=>crMine());assert.equal(manual.payoutCents,Math.floor(manual.betCents*manual.cashoutBps/100));const retry=await p.evaluate(b=>api('crash/cashout','POST',{requestId:b.requestId}),manual);assert.equal(retry.payoutCents,manual.payoutCents);
 await p.evaluate(()=>setLanguage('fil'));assert.match(await p.locator('#crAction').textContent(),/Susunod/);await p.evaluate(()=>setLanguage('en'));await p.locator('#crSound').click();await p.locator('#crSound').click();assert(await p.evaluate(()=>sound));
 await p.evaluate(()=>switchMode('CLUB'));await p.waitForFunction(()=>gameMode==='CLUB'&&!modeChanging);assert.equal(await p.evaluate(()=>balance),0);assert.equal(await p.evaluate(()=>crBets.length),0);await fresh(300);await p.locator('#crAction').click();await p.waitForFunction(()=>!crSending&&!crPending);assert.equal(await p.evaluate(()=>balance),0);assert.equal(await p.evaluate(()=>crBets.length),0);
 assert.deepEqual(errors,[]);console.log('PASS Crash packaged JAR: guest/register, 5 responsive widths, hidden crash point, lost response retry, reload, offline server auto cashout, manual payout/idempotency, wallet lock/isolation, Filipino and sound.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
