const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox']});try{
const p=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'no-preference'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACE_TEST_URL);await p.waitForFunction(()=>typeof arLoad==='function');await p.evaluate(async()=>{await api('register','POST',{username:'motion'+Date.now(),password:'123456',rePassword:'123456'});await connect();await selectArcade('PLINKO');});await p.waitForFunction(()=>ready&&arConfig&&!arLoading);
await p.evaluate(()=>{window.samples=[];window.boardBuilds=0;const draw=arDraw,make=arMakePlinkoBoard;arPlinkoBoard=null;arMakePlinkoBoard=()=>{boardBuilds++;return make()};arDraw=(o,x)=>{if(o)samples.push({p:x,time:performance.now()});return draw(o,x)};});
for(let n=0;n<3;n++){await p.evaluate(()=>{samples=[]});await p.locator('#arPlay').click();await p.waitForFunction(()=>arBusy);await p.waitForFunction(()=>!arBusy&&!arPending);const frames=await p.evaluate(()=>samples);assert(frames.length>25,'visible drop must render multiple frames');assert.equal(frames[0].p,0);assert.equal(frames.at(-1).p,1);assert(frames.some(f=>f.p>.3&&f.p<.7));assert.equal(await p.locator('.ar-bin.hit').getAttribute('data-bin'),String(await p.evaluate(()=>arLast.outcome.slot)));await p.evaluate(()=>hideVictory());}
assert.equal(await p.evaluate(()=>boardBuilds),1,'static board reused');await p.evaluate(()=>{for(const v of [-.001,NaN,Infinity,-Infinity,0,1,1.1])arDraw(arLast.outcome,v)});
// Slow response: no old landed ball/result; click remains locked until same request resolves.
await p.route('**/api/arcade/PLINKO/rounds?*',async r=>{if(r.request().method()==='POST')await new Promise(x=>setTimeout(x,700));await r.continue()});await p.locator('#arPlay').click();assert.match(await p.locator('#arResult').textContent(),/Receiving/);assert(await p.locator('#arPlay').isDisabled());await p.waitForFunction(()=>arAnimationDone!==null);
// Simulate background notification deterministically: final drawing must precede wallet/result updates.
await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await p.waitForFunction(()=>!arBusy&&!arPending);assert.equal(await p.evaluate(()=>samples.at(-1).p),1);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));hideVictory()});await p.waitForFunction(()=>!arLoading);await p.unroute('**/api/arcade/PLINKO/rounds?*');
await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#arPlay').click();await p.waitForFunction(()=>!arBusy&&!arPending);assert.equal(await p.evaluate(()=>samples.at(-1).p),1);let notices=0;await p.route('**/api/notifications?*',r=>{notices++;return r.fulfill({status:401,contentType:'application/json',body:'{"code":"UNAUTHORIZED"}'})});await p.route('**/api/refresh?*',r=>r.fulfill({status:401,contentType:'application/json',body:'{"code":"UNAUTHORIZED"}'}));await p.evaluate(async()=>{try{await api('notifications')}catch{}});assert.equal(await p.evaluate(()=>ready),false);assert(await p.locator('#loginDialog').evaluate(d=>d.open));const count=notices;await p.evaluate(async()=>{await pollReceipts();await syncAuto(false)});await p.waitForTimeout(3200);assert.equal(notices,count,'no repeated polling after expired session');assert.equal((await p.request.get(process.env.ACE_TEST_URL+'/favicon.svg')).status(),200);assert.deepEqual(errors,[]);console.log('PASS Plinko motion: 3 repeated visible drops, intermediate frames, cached board, slow response UI, input lock, background final frame, reduced motion exact landing, negative/nonfinite progress guards, expired-session polling stop and favicon.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
