const {chromium}=require(process.env.ACE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ACE_CHROMIUM,headless:true,args:['--no-sandbox']});try{const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ACE_TEST_URL);await p.waitForFunction(()=>typeof arLoad==='function');await p.evaluate(()=>selectArcade('SAKLA'));await p.waitForFunction(()=>arConfig&&!arLoading);await p.locator('#arPlay').click();assert(await p.locator('#loginDialog').evaluate(e=>e.open));await p.locator('#previewTheme').click();await p.evaluate(async()=>{await api('register','POST',{username:'sakla'+Date.now(),password:'123456',rePassword:'123456'});await connect();await selectArcade('SAKLA')});await p.waitForFunction(()=>arConfig&&ready&&!arLoading);
 for(const width of [320,390,760,844,1440]){await p.setViewportSize({width,height:width===844?390:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);assert.equal(await p.locator('[data-sk-pair]').count(),20);const target=await p.locator('[data-sk-pair="19"]').boundingBox();assert(target.height>=44);if(process.env.ACE_SCREENSHOTS){fs.mkdirSync(process.env.ACE_SCREENSHOTS,{recursive:true});await p.screenshot({path:process.env.ACE_SCREENSHOTS+'/sakla-'+width+'.png',fullPage:true})}}
 await p.locator('[data-sk-pair="19"]').click();const before=await p.evaluate(()=>balance);let dropped=false;await p.route('**/api/arcade/SAKLA/rounds?*',async route=>{if(route.request().method()!=='POST'||dropped)return route.continue();dropped=true;await route.fetch();await route.abort('connectionfailed')});await p.locator('#arPlay').click();await p.waitForFunction(()=>arPending&&!arBusy);const id=await p.evaluate(()=>arPending.body.requestId);await p.reload();await p.waitForFunction(()=>ready);await p.evaluate(()=>showView('arcadeView'));await p.waitForFunction(()=>arLast&&!arBusy&&!arPending);const row=await p.evaluate(()=>arLast);assert.equal(row.requestId,id);assert.equal(row.selection,19);assert.equal(row.payoutCents,row.outcome.slot===19?9500:0);assert.equal(await p.evaluate(()=>balance),before-5+row.payoutCents/100);assert.equal(new Set(row.outcome.values).size,row.outcome.values.length);await p.unroute('**/api/arcade/SAKLA/rounds?*');
 await p.evaluate(()=>setLanguage('fil'));assert.equal(await p.locator('#arPlay').textContent(),'Ipamahagi ang Sakla');await p.evaluate(()=>setLanguage('en'));await p.evaluate(()=>switchMode('CLUB'));await p.waitForFunction(()=>gameMode==='CLUB'&&!arLoading&&!modeChanging);assert.equal(await p.evaluate(()=>balance),0);assert.equal(await p.evaluate(()=>arRows.length),0);
 // Shared win: no loss/returned stake celebration; deduplicate actual wins.
 await p.evaluate(()=>{hideVictory();celebrateWin('arcadeView','loss',500,0);celebrateWin('arcadeView','refund',500,500)});assert.equal(await p.locator('.ace-victory').count(),0);await p.evaluate(()=>celebrateWin('arcadeView','win',500,1500));assert.equal(await p.locator('.ace-victory').count(),1);await p.evaluate(()=>{hideVictory();celebrateWin('arcadeView','win',500,1500)});assert.equal(await p.locator('.ace-victory').count(),0);
 // Dice test uses a presentation-only fixture; financial engine is tested separately.
 await p.evaluate(()=>switchMode('LOBBY'));await p.waitForFunction(()=>!modeChanging&&!arLoading);await p.evaluate(()=>showView('colorGameView'));await p.waitForFunction(()=>cgState&&!cgFetching);await p.emulateMedia({reducedMotion:'no-preference'});await p.evaluate(()=>{cgBets=[];cgReveal({dice:['RED','GREEN','BLUE']})});assert.equal(await p.locator('.cg-cube-face').count(),18);assert(await p.evaluate(()=>cgBusy&&cgAnimations.length===6));await p.waitForFunction(()=>!cgBusy);assert.deepEqual(await p.locator('#cgDice .cg-die').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('aria-label'))),['RED','GREEN','BLUE']);assert.equal(await p.locator('.ace-victory').count(),0);assert.equal(await p.evaluate(()=>cgAnimations.length),0);
 assert.deepEqual(errors,[]);console.log('PASS Sakla + effects: guest, register, five widths, 20 pairs, lost response/reload once, selection/payout, Club isolation, Filipino, positive-net-only celebration, 3D dice lifecycle.');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
