/* Run against a disposable server created by simple_auth_check.py. */
const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const {JSDOM}=require(process.env.ACE_JSDOM||'jsdom');
const base=process.env.ACE_TEST_URL,root=path.join(__dirname,'../client');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:base,runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,jar=new Map(),errors=[];w.TextEncoder=TextEncoder;w.AbortController=AbortController;
w.addEventListener('error',e=>errors.push(e.message));w.matchMedia=()=>({matches:true,addEventListener(){}});
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLElement.prototype.scrollIntoView=function(){};
w.fetch=async(url,options={})=>{const response=await fetch(new URL(url,base),{...options,headers:{...options.headers,Cookie:[...jar].map(([k,v])=>k+'='+v).join('; ')}});for(const c of response.headers.getSetCookie()){const [name,...value]=c.split(';')[0].split('=');if(value.join('='))jar.set(name,value.join('='));else jar.delete(name)}return response;};
for(const file of ['i18n.js','game.js','portal.js','hierarchy.js','receipts.js','modes.js','roles.js','mobile.js'])new vm.Script(fs.readFileSync(path.join(root,file),'utf8')).runInContext(dom.getInternalVMContext());
const wait=async(fn)=>{for(let i=0;i<200;i++){if(fn())return;await new Promise(r=>setTimeout(r,25))}throw Error('UI timeout')};
(async()=>{await wait(()=>w.document.getElementById('connection').textContent==='Guest');const d=w.document;d.getElementById('menuToggle').click();assert(d.getElementById('mobileMenu').open);assert.equal(d.getElementById('mobileMenu').querySelector('.app-nav'),d.querySelector('.app-nav'));d.getElementById('menuClose').click();assert(!d.getElementById('mobileMenu').open);d.getElementById('registerNav').click();const f=d.getElementById('registerForm');assert.deepEqual([...f.querySelectorAll('input')].map(e=>e.name),['username','password','rePassword']);const username='ui'+Date.now();f.elements.username.value=username;f.elements.password.value='12345';await f.onsubmit({preventDefault(){}});assert(d.getElementById('registerError').textContent);assert(!jar.has('ACE_SESSION'));f.elements.password.value='123456';f.elements.rePassword.value='123456';await f.onsubmit({preventDefault(){}});assert(w.eval('ready'));assert.equal(w.eval('player.username'),username);assert(!d.getElementById('loginDialog').open);assert.equal(w.eval('gameMode'),'LOBBY');assert.equal(w.eval('balance'),10000);await wait(()=>!w.eval('polling'));await w.switchMode('CLUB');assert.equal(w.eval('balance'),0);assert.equal(d.getElementById('currencyLabel').textContent,'CHIPS · CLUB');await wait(()=>!w.eval('polling'));await w.switchMode('LOBBY');assert.equal(w.eval('balance'),10000);assert.equal(d.getElementById('chipForm'),null);
const adminResponse=await fetch(new URL('/api/login',base),{method:'POST',headers:{'Content-Type':'application/json','X-Game-Client':'web'},body:JSON.stringify({username:'creator',password:'test-creator-password'})});const admin=await adminResponse.json();const adminCookies=adminResponse.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');
const credit=await fetch(new URL('/api/chips/move',base),{method:'POST',headers:{'Content-Type':'application/json','X-Game-Client':'web','X-CSRF-Token':admin.csrf,Cookie:adminCookies},body:JSON.stringify({requestId:crypto.randomUUID(),targetId:w.eval('player.id'),direction:'GIVE',amountCents:1200})});assert.equal(credit.status,200);await w.pollReceipts();await wait(()=>d.getElementById('chipReceipt').open);assert(d.getElementById('receiptAmount').textContent.includes('12'));await d.getElementById('receiptRead').onclick();assert(!d.getElementById('chipReceipt').open);assert.equal((await w.api('notifications')).length,0);
await d.getElementById('logout').onclick();assert.equal(w.eval('player'),null);assert(!w.eval('ready'));assert.equal(w.eval('balance'),0);assert(!jar.has('ACE_SESSION'));assert(!jar.has('ACE_REFRESH'));assert(d.getElementById('spin').disabled);const login=d.getElementById('loginForm');login.elements.username.value=username;login.elements.password.value='wrong6';login.dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true}));await wait(()=>!login.querySelector('button').disabled);assert(d.getElementById('loginError').textContent);login.elements.password.value='123456';login.dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true}));await wait(()=>w.eval('ready')&&!login.querySelector('button').disabled);assert.equal(w.eval('player.username'),username);await d.getElementById('logout').onclick();d.getElementById('registerNav').click();f.elements.username.value=username;f.elements.password.value='123456';f.elements.rePassword.value='123456';await f.onsubmit({preventDefault(){}});assert(d.getElementById('registerError').textContent.includes('DUPLICATE'));w.eval("setLanguage('fil')");assert.equal(f.elements.password.closest('label').querySelector('span').textContent,'Password (6+ na character)');async function uiLogin(username,password){w.showLogin();login.elements.username.value=username;login.elements.password.value=password;login.dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true}));await wait(()=>w.eval('player?.username')===username&&!login.querySelector('button').disabled);}
await uiLogin('creator','test-creator-password');await w.showView('accountsView');assert(!d.querySelector('[data-view="accountsView"]').hidden);assert(d.querySelector('[data-view="gameView"]').hidden);assert(!d.getElementById('settingsForm').hidden);assert(d.getElementById('chipDirection').querySelector('[value="ISSUE"]'));
const saName='sa'+Date.now(),agentName='ag'+Date.now();const sa=await w.api('accounts','POST',{username:saName,displayName:saName,password:'123456',role:'SUPER_AGENT',parentId:w.eval('player.id')});const ag=await w.api('accounts','POST',{username:agentName,displayName:agentName,password:'123456',role:'AGENT',parentId:sa.id});
await d.getElementById('logout').onclick();await uiLogin(saName,'123456');await w.showView('accountsView');assert.deepEqual([...d.getElementById('newRole').options].map(o=>o.value),['AGENT','PLAYER']);assert(d.getElementById('settingsForm').hidden);assert(!d.getElementById('chipDirection').querySelector('[value="ISSUE"]'));
await d.getElementById('logout').onclick();await uiLogin(agentName,'123456');await w.showView('accountsView');assert.deepEqual([...d.getElementById('newRole').options].map(o=>o.value),['PLAYER']);assert(d.querySelector('[data-view="rankingView"]').hidden);assert(d.getElementById('settingsForm').hidden);
assert.equal(errors.length,0,errors.join('\n'));console.log('PASS DOM + live server: three fields, Lobby/Club switching, chip receipt popup/acknowledgment; reject five-character password; register six; logout clears cookies/wallet; wrong login; correct login; duplicate signup; Filipino.');})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>w.close());
