/* Disposable H2 + real Chromium integration. Never uses production data. */
const {spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const base='http://127.0.0.1:18083',root=path.resolve(__dirname,'..');
const log=fs.openSync('/tmp/ace-v13-live.log','w');let server,browser;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function start(){server=spawn(process.env.ACE_JAVA||'java',['-Dloader.path='+process.env.ACE_H2,'-cp',path.join(root,'server/target/super-ace-online-13.0.0.jar'),'org.springframework.boot.loader.launch.PropertiesLauncher'],{env:{...process.env,PORT:'18083',DB_URL:'jdbc:h2:file:/tmp/ace-v13-live;MODE=MySQL;DATABASE_TO_LOWER=TRUE',DB_USER:'sa',DB_PASSWORD:'',CREATOR_USER:'creator',CREATOR_PASSWORD:'temporary-creator-password',JWT_SECRET:'temporary-test-secret-at-least-32-characters',SPIN_COOLDOWN_MS:'0'},stdio:['ignore',log,log]});for(let i=0;i<120;i++){try{const r=await fetch(base+'/api/health');if(r.ok)return}catch{}if(server.exitCode!==null)throw Error('Server exited; inspect live log');await delay(250)}throw Error('Startup timeout')}
async function stop(){if(server&&server.exitCode===null){server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));}}
async function api(context,p,data,csrf,method=data?'POST':'GET'){const r=await context.request.fetch(base+'/api/'+p,{method,headers:{'X-Game-Client':'web','X-CSRF-Token':csrf||''},...(data?{data}:{})});if(!r.ok())throw Error(p+' '+r.status()+' '+await r.text());return r.json()}
(async()=>{await start();browser=await chromium.launch({headless:true,executablePath:process.env.ACE_CHROME,args:['--no-sandbox']});const admin=await browser.newContext();let me=await api(admin,'login',{username:'creator',password:'temporary-creator-password'});const suffix=Date.now(),pass='temporary-player-password';async function create(role,parent,name){return api(admin,'accounts',{username:name+suffix,displayName:name,password:pass,role,parentId:parent},me.csrf)}const sa=await create('SUPER_AGENT',me.id,'super'),agent=await create('AGENT',sa.id,'agent');
 const context=await browser.newContext({viewport:{width:1280,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.getElementById('connection').textContent==='Guest');assert.equal(await page.locator('#loginDialog').evaluate(e=>e.open),false);assert.equal(await page.locator('#spin').isDisabled(),true);for(const theme of ['emerald','ruby','sapphire','neon','classic']){await page.locator('#theme-'+theme).click();assert.equal(await page.locator('body').getAttribute('data-theme'),theme)}await page.selectOption('#language','fil');assert.equal(await page.locator('html').getAttribute('lang'),'fil');await page.selectOption('#language','en');await page.locator('#testSound').click();assert.equal(await page.evaluate(()=>audioCtx?.state),'running');await page.locator('#signInNav').click();await page.locator('#loginDialog > button').filter({hasText:'Register'}).click();await page.locator('#registerForm [name=username]').fill('player'+suffix);await page.locator('#registerForm [name=displayName]').fill('Test Player');await page.locator('#registerForm [name=password]').fill(pass);await page.locator('#registerForm [name=agentCode]').fill(agent.publicCode);await page.locator('#registerForm button').click();await page.waitForFunction(()=>ready&&player?.role==='PLAYER');assert.match(await page.evaluate(()=>player.publicCode),/^\d{6}$/);await page.locator('#spin').click();await page.waitForFunction(()=>!busy&&revision>0);assert.equal(await page.evaluate(()=>pending),null);await page.screenshot({path:'/tmp/ace-v13-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/ace-v13-mobile.png',fullPage:true});
 const wallet=await page.evaluate(()=>player);await api(admin,'chips/move',{requestId:crypto.randomUUID(),targetId:agent.id,direction:'ISSUE',amountCents:50000},me.csrf);const agentCtx=await browser.newContext(),agentMe=await api(agentCtx,'login',{username:agent.username,password:pass});const transfer={requestId:crypto.randomUUID(),targetId:wallet.id,direction:'GIVE',amountCents:10000};await api(agentCtx,'chips/move',transfer,agentMe.csrf);await api(agentCtx,'chips/move',transfer,agentMe.csrf);assert.equal((await api(agentCtx,'me')).balanceCents,40000);
 await page.evaluate(()=>showView('chipsView'));assert.ok(await page.locator('#chipTable tbody tr').count()>0);await page.evaluate(()=>showView('gameView'));await page.evaluate(()=>syncAuto(false));await page.evaluate(()=>clearTimeout(pollTimer));const w=await api(context,'me');const runId=crypto.randomUUID();await api(context,'auto/start',{runId,count:10,betCents:w.freeSpins?w.lockedBetCents:2000,expectedRevision:w.revision,turbo:true},w.csrf);await page.close();await delay(2500);const state=await api(context,'auto');assert.ok(state.wallet.revision>w.revision);const beforeRestart=state.wallet.revision;await stop();await start();await delay(2500);const resumed=await api(context,'auto');assert.ok(resumed.wallet.revision>=beforeRestart);assert.equal(resumed.job.runId,runId);await api(context,'auto/stop',{runId},w.csrf);
 const refreshed=await api(context,'refresh',{});assert.notEqual(refreshed.csrf,w.csrf);const cookies=await context.cookies();assert.ok(cookies.find(c=>c.name==='ACE_SESSION').httpOnly);assert.equal(cookies.find(c=>c.name==='ACE_SESSION').value.split('.').length,3);
 assert.equal(errors.length,0,errors.join('\n'));console.log('PASS Chromium: guest, registration, 5 themes, EN/Filipino, audio running, spin, chip idempotency/history, background autoplay, restart persistence, refresh JWT.');await browser.close();browser=null;await stop();})().catch(async e=>{console.error(e);if(browser)await browser.close();await stop();process.exitCode=1});
