package philip.emerald.ace.Utils;
import philip.emerald.ace.superace.GameService;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.time.temporal.TemporalAdjusters;
import java.util.*;
import java.math.BigInteger;

@Service
public class Reports {
 final GameService game;final Accounts accounts;final ZoneId zone;
 public Reports(GameService game,Accounts accounts,@Value("${ace.zone}")String zone){this.game=game;this.accounts=accounts;this.zone=ZoneId.of(zone);}
 public record Period(String type,String start,String endExclusive,String timezone,long from,long to){}
 public record Row(String playerId,String displayName,String agentId,String agentName,long wagerCents,long payoutCents,long netCents,long spins,long paidSpins,long freeSpins){}
 public record Report(Period period,List<Row> players,long wagerCents,long payoutCents,long netCents){}
 public record Rank(int rank,String displayName,long wagerCents){}
 public record Settings(int commissionBps,String commissionMode,long revision){}
 public record Settlement(String agentId,String agentName,String weekStart,long wagerCents,long payoutCents,long lossBaseCents,int rateBps,String commissionMode,long commissionCents,String status,long revision,long closedAt,Long paidAt,String note,List<Row> players){}
 public Period period(String type,LocalDate anchor){LocalDate start,end;switch(type){case "day"-> {start=anchor;end=start.plusDays(1);}case "week"->{start=anchor.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));end=start.plusWeeks(1);}case "month"->{start=anchor.withDayOfMonth(1);end=start.plusMonths(1);}case "year"->{start=anchor.withDayOfYear(1);end=start.plusYears(1);}default->throw GameService.error(400,"INVALID_PERIOD");}return new Period(type,start.toString(),end.toString(),zone.toString(),start.atStartOfDay(zone).toInstant().toEpochMilli(),end.atStartOfDay(zone).toInstant().toEpochMilli());}
 public LocalDate today(){return LocalDate.now(zone);}
 public Report report(Accounts.User actor,String type,LocalDate anchor){return query(actor,period(type,anchor));}
 Report query(Accounts.User actor,Period p){String scope=switch(actor.role()){case CREATOR->"1=1";case SUPER_AGENT->"r.super_agent_id=?";case AGENT->"r.agent_id=?";case PLAYER->"r.player_id=?";};var args=new ArrayList<Object>(List.of(p.from(),p.to()));if(actor.role()!=Accounts.Role.CREATOR)args.add(actor.id());
  var rows=game.db().query("SELECT r.player_id,a.display_name,r.agent_id,COALESCE(g.display_name,'LUCKY SEVEN') agent_name,SUM(r.wager_cents) wager,SUM(r.payout_cents) payout,COUNT(*) spins,SUM(CASE WHEN r.is_free THEN 1 ELSE 0 END) free FROM round_ledger r JOIN accounts a ON a.id=r.player_id LEFT JOIN accounts g ON g.id=r.agent_id WHERE r.created_at>=? AND r.created_at<? AND "+scope+" GROUP BY r.player_id,a.display_name,r.agent_id,g.display_name ORDER BY a.display_name,r.player_id",(r,n)->new Row(r.getString("player_id"),r.getString("display_name"),r.getString("agent_id"),r.getString("agent_name"),r.getLong("wager"),r.getLong("payout"),r.getLong("payout")-r.getLong("wager"),r.getLong("spins"),r.getLong("spins")-r.getLong("free"),r.getLong("free")),args.toArray());long wager=rows.stream().mapToLong(Row::wagerCents).sum(),payout=rows.stream().mapToLong(Row::payoutCents).sum();return new Report(p,rows,wager,payout,payout-wager);
 }
 public Map<String,Object> ranking(String type,LocalDate date){if(!List.of("day","week").contains(type))throw GameService.error(400,"INVALID_PERIOD");var p=period(type,date);var ranks=game.db().query("SELECT a.display_name,SUM(r.wager_cents) wager FROM round_ledger r JOIN accounts a ON a.id=r.player_id WHERE r.created_at>=? AND r.created_at<? GROUP BY a.id,a.display_name HAVING SUM(r.wager_cents)>0 ORDER BY wager DESC,a.id LIMIT 10",(r,n)->new Rank(n+1,r.getString(1),r.getLong(2)),p.from(),p.to());return Map.of("period",p,"players",ranks);}
 public Settings settings(){return game.db().query("SELECT * FROM app_settings WHERE id=1",(r,n)->new Settings(r.getInt("commission_bps"),r.getString("commission_mode"),r.getLong("revision"))).getFirst();}
 static void validateRate(int rate){if(rate<0||rate>10000)throw GameService.error(400,"INVALID_RATE");}
 @Transactional public Settings settings(Accounts.User u,int bps,String mode,long revision){accounts.require(u,Accounts.Role.CREATOR);validateRate(bps);if(!List.of("POSITIVE_PLAYER","NET_AGENT").contains(mode))throw GameService.error(400,"INVALID_MODE");if(game.db().update("UPDATE app_settings SET commission_bps=?,commission_mode=?,revision=revision+1 WHERE id=1 AND revision=?",bps,mode,revision)!=1)throw GameService.error(409,"STALE_STATE");accounts.audit(u.id(),"COMMISSION_SETTINGS","1",bps+" "+mode);return settings();}
 static long commission(long base,int rate){return BigInteger.valueOf(base).multiply(BigInteger.valueOf(rate)).add(BigInteger.valueOf(5000)).divide(BigInteger.valueOf(10000)).longValueExact();}
 static long lossBase(List<Row> rows,String mode){var eligible=rows.stream().filter(r->!r.playerId().equals(r.agentId())).toList();return mode.equals("NET_AGENT")?Math.max(0,eligible.stream().mapToLong(r->r.wagerCents()-r.payoutCents()).sum()):eligible.stream().mapToLong(r->Math.max(0,r.wagerCents()-r.payoutCents())).sum();}
 // Each weekly snapshot is immutable; approval can select a rate, but never changes game totals.
 @Transactional public void closeWeek(LocalDate start){var p=period("week",start);if(Instant.now().isBefore(LocalDate.parse(p.endExclusive()).atTime(6,0).atZone(zone).toInstant()))return;
  game.db().queryForObject("SELECT id FROM app_settings WHERE id=1 FOR UPDATE",Integer.class);var settings=settings();
  var agents=game.db().query("SELECT * FROM accounts WHERE (role='AGENT' AND created_at<?) OR id IN (SELECT agent_id FROM round_ledger WHERE created_at>=? AND created_at<?)",accounts::map,p.to(),p.from(),p.to());
  for(var agent:agents){if(game.db().queryForObject("SELECT COUNT(*) FROM weekly_settlements WHERE agent_id=? AND week_start=?",Integer.class,agent.id(),p.start())>0)continue;var historicalSuper=game.db().queryForList("SELECT super_agent_id FROM round_ledger WHERE agent_id=? AND created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 1",String.class,agent.id(),p.from(),p.to());String owner=historicalSuper.isEmpty()?agent.parentId():historicalSuper.getFirst();var scoped=new Accounts.User(agent.id(),agent.username(),agent.displayName(),Accounts.Role.AGENT,owner,agent.enabled(),agent.commissionBps(),agent.publicCode());var report=query(scoped,p);long base=lossBase(report.players(),settings.commissionMode());int rate=agent.commissionBps()==null?settings.commissionBps():agent.commissionBps();
   game.db().update("INSERT INTO weekly_settlements(agent_id,super_agent_id,week_start,wager_cents,payout_cents,loss_base_cents,rate_bps,commission_mode,commission_cents,status,revision,closed_at,details_json) VALUES(?,?,?,?,?,?,?,?,?,'DRAFT',0,?,?)",agent.id(),owner,p.start(),report.wagerCents(),report.payoutCents(),base,rate,settings.commissionMode(),commission(base,rate),System.currentTimeMillis(),game.encode(report.players()));
  }
 }
 public List<LocalDate> missingWeeks(){Long first=game.db().queryForObject("SELECT MIN(created_at) FROM (SELECT created_at FROM accounts WHERE role='AGENT' UNION ALL SELECT created_at FROM round_ledger) dates",Long.class);if(first==null)return List.of();var date=Instant.ofEpochMilli(first).atZone(zone).toLocalDate().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));var end=today().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));var weeks=new ArrayList<LocalDate>();for(;date.isBefore(end);date=date.plusWeeks(1))weeks.add(date);return weeks;}
 Settlement map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new Settlement(r.getString("agent_id"),r.getString("display_name"),r.getString("week_start"),r.getLong("wager_cents"),r.getLong("payout_cents"),r.getLong("loss_base_cents"),r.getInt("rate_bps"),r.getString("commission_mode"),r.getLong("commission_cents"),r.getString("status"),r.getLong("revision"),r.getLong("closed_at"),(Long)r.getObject("paid_at"),r.getString("note"),Arrays.asList(game.decode(r.getString("details_json"),Row[].class)));}
 public List<Settlement> settlements(Accounts.User u,LocalDate anchor){if(u.role()==Accounts.Role.PLAYER)throw GameService.error(403,"FORBIDDEN");String scope=switch(u.role()){case CREATOR->"1=1";case SUPER_AGENT->"s.super_agent_id=?";default->"s.agent_id=?";};var args=new ArrayList<Object>();args.add(period("week",anchor).start());if(u.role()!=Accounts.Role.CREATOR)args.add(u.id());return game.db().query("SELECT s.*,a.display_name FROM weekly_settlements s JOIN accounts a ON a.id=s.agent_id WHERE s.week_start=? AND "+scope+" ORDER BY a.display_name,s.agent_id",this::map,args.toArray());}
 @Transactional public void decide(Accounts.User u,String agentId,LocalDate week,String action,int rate,long revision,String note){accounts.require(u,Accounts.Role.CREATOR);validateRate(rate);var list=game.db().queryForList("SELECT * FROM weekly_settlements WHERE agent_id=? AND week_start=? FOR UPDATE",agentId,week.toString());if(list.isEmpty())throw GameService.error(404,"NOT_FOUND");var row=list.getFirst();if(((Number)row.get("revision")).longValue()!=revision)throw GameService.error(409,"STALE_STATE");String state=(String)row.get("status");
  if(action.equals("APPROVE")&&state.equals("DRAFT"))game.db().update("UPDATE weekly_settlements SET status='APPROVED',rate_bps=?,commission_cents=?,approved_by=?,note=?,revision=revision+1 WHERE agent_id=? AND week_start=?",rate,commission(((Number)row.get("loss_base_cents")).longValue(),rate),u.id(),note,agentId,week.toString());
  else if(action.equals("PAID")&&state.equals("APPROVED"))game.db().update("UPDATE weekly_settlements SET status='PAID',paid_at=?,note=?,revision=revision+1 WHERE agent_id=? AND week_start=?",System.currentTimeMillis(),note,agentId,week.toString());else throw GameService.error(409,"INVALID_TRANSITION");accounts.audit(u.id(),"SETTLEMENT_"+action,agentId+":"+week,note);
 }
}
